<script setup>
import {computed,nextTick,ref} from 'vue'
import {VueFlow,useVueFlow,MarkerType} from '@vue-flow/core'
import '@vue-flow/core/dist/style.css'
import '@vue-flow/core/dist/theme-default.css'
import GlassWindow from '../GlassWindow.vue'
import LearnedRuleEvidence from '../LearnedRuleEvidence.vue'
import PolicyGraphNode from './PolicyGraphNode.vue'
import PolicyNodeForm from './PolicyNodeForm.vue'
import {types,nodeLabel,newNode,nodeIssue,graphDocument,connectionIssue,scopeTypes,ruleTypes} from './model.js'
const props=defineProps({nodes:{type:Array,required:true},edges:{type:Array,required:true},readonly:Boolean,rules:{type:Array,default:()=>[]},policyId:String})
const emit=defineEmits(['update:nodes','update:edges'])
const mode=ref('visual'),editor=ref(null),isNew=ref(false),selectedEdge=ref(null),connectionOpen=ref(false),source=ref(''),target=ref(''),error=ref(''),undoStack=ref([]),redoStack=ref([])
const graphNodes=computed({get:()=>props.nodes,set:value=>emit('update:nodes',value)}),graphEdges=computed({get:()=>props.edges,set:value=>emit('update:edges',value)})
const flowId=`policy-${props.policyId}`,flow=useVueFlow({id:flowId})
const snapshot=()=>JSON.stringify(graphDocument(props.nodes,props.edges))
function remember(){undoStack.value.push(snapshot());if(undoStack.value.length>50)undoStack.value.shift();redoStack.value=[]}
function restore(value){const graph=JSON.parse(value);emit('update:nodes',graph.nodes);emit('update:edges',graph.edges);editor.value=null;selectedEdge.value=null}
function undo(){if(!undoStack.value.length||props.readonly)return;redoStack.value.push(snapshot());restore(undoStack.value.pop())}
function redo(){if(!redoStack.value.length||props.readonly)return;undoStack.value.push(snapshot());restore(redoStack.value.pop())}
async function fit(){await nextTick();await flow.fitView({padding:.2,duration:150})}
async function switchMode(value){mode.value=value;if(value==='visual')fit()}
function add(type){if(props.readonly)return;error.value='';editor.value=newNode(type,props.nodes.length);isNew.value=true}
function inspect(id){const node=props.nodes.find(n=>n.id===id);if(!node)return;isNew.value=false;editor.value=JSON.parse(JSON.stringify(graphDocument([node],[]).nodes[0]));const d=editor.value.data;if(node.type==='schedule'){d.startTime=d.start||d.startTime;d.endTime=d.end||d.endTime;delete d.start;delete d.end}if(node.type==='mfaGate'){d.localPort=d.targetPort||d.localPort;delete d.targetPort}}
function applyNode(){if(props.readonly||nodeIssue(editor.value))return;remember();const node=JSON.parse(JSON.stringify(editor.value));emit('update:nodes',isNew.value?[...props.nodes,node]:props.nodes.map(n=>n.id===node.id?{...n,type:node.type,data:node.data}:n));editor.value=null;fit()}
function removeNode(){if(props.readonly)return;remember();const id=editor.value.id;emit('update:nodes',props.nodes.filter(n=>n.id!==id));emit('update:edges',props.edges.filter(e=>e.source!==id&&e.target!==id));editor.value=null}
function duplicate(){if(props.readonly)return;const copy=JSON.parse(JSON.stringify(editor.value));copy.id=crypto.randomUUID();copy.data.name=`${nodeLabel(copy)} copy`;copy.position={x:copy.position.x+40,y:copy.position.y+80};editor.value=copy;isNew.value=true}
function connect(value){if(props.readonly)return;error.value=connectionIssue(props.nodes,props.edges,value);if(error.value)return;remember();emit('update:edges',[...props.edges,{id:crypto.randomUUID(),source:value.source,target:value.target}]);connectionOpen.value=false}
function disconnect(id){if(props.readonly)return;remember();emit('update:edges',props.edges.filter(e=>e.id!==id));selectedEdge.value=null}
function arrange(){if(props.readonly)return;remember();const levels=new Map(),visiting=new Set();function level(id){if(levels.has(id))return levels.get(id);if(visiting.has(id))return 0;visiting.add(id);const parents=props.edges.filter(e=>e.target===id);const depth=parents.length?1+Math.max(...parents.map(e=>level(e.source))):0;visiting.delete(id);levels.set(id,depth);return depth}const rows=new Map();emit('update:nodes',props.nodes.map(n=>{const col=level(n.id),row=rows.get(col)||0;rows.set(col,row+1);return {...n,position:{x:50+col*330,y:50+row*180}}}));fit()}
const nodeConnections=computed(()=>editor.value?props.edges.filter(e=>e.source===editor.value.id||e.target===editor.value.id):[])
const compiled=computed(()=>props.rules.filter(r=>r.sourceNodeId===editor.value?.id))
const name=id=>nodeLabel(props.nodes.find(n=>n.id===id)||{type:'Missing node'})
const connectIssue=computed(()=>connectionIssue(props.nodes,props.edges,{source:source.value,target:target.value}))
defineExpose({fit,resetHistory(){undoStack.value=[];redoStack.value=[]}})
</script>
<template><div class="policy-editor">
  <nav class="policy-editor-tabs" role="tablist" aria-label="Policy editor mode"><button id="policy-visual-tab" role="tab" :aria-selected="mode==='visual'" aria-controls="policy-visual-panel" :class="{active:mode==='visual'}" @click="switchMode('visual')">Visual editor</button><button id="policy-form-tab" role="tab" :aria-selected="mode==='form'" aria-controls="policy-form-panel" :class="{active:mode==='form'}" @click="switchMode('form')">Form editor</button></nav>
  <div class="node-palette" aria-label="Policy node palette"><button v-for="type in types" :key="type[0]" class="button small secondary" :disabled="readonly" :title="readonly?'This policy is read-only':`Add ${type[2]}`" @click="add(type[0])"><i class="mdi" :class="`mdi-${type[1]}`" aria-hidden="true"></i>{{type[2]}}</button></div>
  <div class="editor-tools" aria-label="Policy editing tools"><template v-if="!readonly"><button class="button small secondary" :disabled="nodes.length<2" @click="connectionOpen=true;error=''">Connect nodes</button><button class="button small secondary" :disabled="!undoStack.length" @click="undo">Undo</button><button class="button small secondary" :disabled="!redoStack.length" @click="redo">Redo</button></template><span v-else class="hint">Read-only policy · select a node to inspect its details.</span><span class="graph-count">{{nodes.length}} nodes · {{edges.length}} connections</span></div>
  <p v-if="error" class="error-msg" role="alert">{{error}}</p>
  <section v-show="mode==='visual'" id="policy-visual-panel" role="tabpanel" aria-labelledby="policy-visual-tab">
    <div class="canvas-controls"><button class="button small secondary" aria-label="Zoom in" @click="flow.zoomIn()">+</button><button class="button small secondary" aria-label="Zoom out" @click="flow.zoomOut()">−</button><button class="button small secondary" @click="fit">Fit view</button><button v-if="!readonly" class="button small secondary" :disabled="!nodes.length" @click="arrange">Arrange nodes</button><small>Drag the canvas to pan. Drag a scope’s right connector to a rule’s left connector.</small></div>
    <div class="policy-flow"><VueFlow :id="flowId" v-model:nodes="graphNodes" v-model:edges="graphEdges" :nodes-draggable="!readonly" :nodes-connectable="!readonly" :edges-updatable="false" :delete-key-code="null" :min-zoom=".15" :max-zoom="2" :default-edge-options="{type:'smoothstep',markerEnd:MarkerType.ArrowClosed}" fit-view-on-init @connect="connect" @node-click="({node})=>inspect(node.id)" @node-drag-start="remember" @edge-click="({edge})=>selectedEdge=edge" @pane-ready="fit">
      <template v-for="type in types" :key="type[0]" #[`node-${type[0]}`]="node"><PolicyGraphNode v-bind="node" :connectable="!readonly" @details="inspect" /></template>
    </VueFlow><div v-if="!nodes.length" class="canvas-empty">{{readonly?'This policy has no graph nodes.':'Add a rule or scope to start. Both editors share the same policy.'}}</div></div>
  </section>
  <section v-if="mode==='form'" id="policy-form-panel" role="tabpanel" aria-labelledby="policy-form-tab" class="form-editor"><p class="hint">Select a row to edit all rule fields. Scope connections apply in both editors; explicit rule values take precedence.</p><div class="table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Configuration</th><th>Connected scopes</th><th></th></tr></thead><tbody><tr v-for="node in nodes" :key="node.id" @click="inspect(node.id)"><td><button class="node-link" @click.stop="inspect(node.id)">{{nodeLabel(node)}}</button></td><td>{{types.find(t=>t[0]===node.type)?.[2]||node.type}}</td><td>{{ruleTypes.includes(node.type)?`${node.data.direction==='out'?'Outbound':'Inbound'} · ${node.data.protocol||'TCP'} · local ${node.data.localPort||'Any'} / remote ${node.data.remotePort||'Any'}`:node.type==='portGroup'?node.data.ports:node.type==='addressGroup'?node.data.addresses:node.type==='profile'?node.data.profile:node.type==='schedule'?`${node.data.start||node.data.startTime}–${node.data.end||node.data.endTime}`:'MFA metadata'}}</td><td>{{edges.filter(e=>e.target===node.id).map(e=>name(e.source)).join(', ')||'None'}}</td><td><button class="button small secondary" @click.stop="inspect(node.id)">{{readonly?'Details':'Edit'}}</button></td></tr><tr v-if="!nodes.length"><td colspan="5">No nodes yet. Choose a node type and select Add node.</td></tr></tbody></table></div></section>
  <details v-if="edges.length" class="connection-list"><summary>Connections ({{edges.length}})</summary><div v-for="edge in edges" :key="edge.id"><span>{{name(edge.source)}} → {{name(edge.target)}}</span><button v-if="!readonly" class="button small secondary" :aria-label="`Disconnect ${name(edge.source)} from ${name(edge.target)}`" @click="disconnect(edge.id)">Disconnect</button></div></details>
  <GlassWindow :model-value="!!editor" @update:model-value="editor=null" :title="readonly?'Node details':isNew?'Add policy node':'Edit policy node'" width="720px"><form v-if="editor" @submit.prevent="applyNode" class="node-dialog"><PolicyNodeForm :node="editor" :readonly="readonly" /><section v-if="nodeConnections.length"><h3>Connections</h3><p v-for="edge in nodeConnections" :key="edge.id">{{name(edge.source)}} → {{name(edge.target)}}</p></section><section v-if="compiled.length"><h3>Last compiled rule</h3><p v-for="rule in compiled" :key="rule.sourceNodeId">{{rule.action}} {{rule.direction}} {{rule.protocol}} · local {{rule.localPort}} / remote {{rule.remotePort}} · {{rule.remoteAddress}} · {{rule.profile}}<small v-if="rule.schedule"> · {{rule.schedule.start}}–{{rule.schedule.end}} {{rule.schedule.timezone}}</small></p></section><LearnedRuleEvidence v-if="editor.data.evidence" :evidence="editor.data.evidence" /><div class="form-actions"><button v-if="!readonly&&!isNew" type="button" class="button danger" @click="removeNode">Delete node</button><button v-if="!readonly&&!isNew" type="button" class="button secondary" @click="duplicate">Duplicate</button><button type="button" class="button secondary" @click="editor=null">{{readonly?'Close':'Cancel'}}</button><button v-if="!readonly" class="button primary" :disabled="!!nodeIssue(editor)">Apply to draft</button></div></form></GlassWindow>
  <GlassWindow v-model="connectionOpen" title="Connect policy nodes" width="560px"><form class="form-grid" @submit.prevent="connect({source,target})"><label>Source scope<select v-model="source" aria-label="Source scope"><option value="">Choose a scope</option><option v-for="node in nodes.filter(n=>scopeTypes.includes(n.type))" :key="node.id" :value="node.id">{{nodeLabel(node)}}</option></select></label><label>Target node<select v-model="target" aria-label="Target node"><option value="">Choose a node</option><option v-for="node in nodes.filter(n=>n.type!=='mfaGate')" :key="node.id" :value="node.id">{{nodeLabel(node)}}</option></select></label><p class="hint">Connect port, address, profile or schedule scopes to rules. Scope chains inherit through their connections.</p><p v-if="source&&target&&connectIssue" class="error-msg" role="alert">{{connectIssue}}</p><div class="form-actions"><button type="button" class="button secondary" @click="connectionOpen=false">Cancel</button><button class="button primary" :disabled="!!connectIssue">Connect</button></div></form></GlassWindow>
  <GlassWindow :model-value="!!selectedEdge" @update:model-value="selectedEdge=null" title="Connection details" width="480px"><template v-if="selectedEdge"><p>{{name(selectedEdge.source)}} → {{name(selectedEdge.target)}}</p><p class="hint">The target inherits unset values from the source scope.</p><button v-if="!readonly" class="button danger" @click="disconnect(selectedEdge.id)">Disconnect</button></template></GlassWindow>
</div></template>
<style scoped>
.policy-editor{min-width:0}.node-palette{display:flex;flex-wrap:wrap;gap:6px;padding:12px 14px;border-bottom:1px solid var(--border)}.policy-editor-tabs{display:flex;gap:4px;border-bottom:1px solid var(--border);padding:0 14px}.policy-editor-tabs button{font:inherit;font-weight:700;border:0;border-bottom:2px solid transparent;background:none;color:var(--muted);padding:12px 16px;cursor:pointer}.policy-editor-tabs button.active{background:color-mix(in srgb,var(--cyan) 9%,transparent);border-bottom-color:var(--cyan);color:var(--field-value)}.editor-tools,.canvas-controls{display:flex;align-items:center;gap:8px;flex-wrap:wrap;padding:12px 14px;border-bottom:1px solid var(--border)}.editor-tools label{display:flex;align-items:center;gap:8px;font-size:12px}.editor-tools select{max-width:180px}.graph-count{margin-left:auto;font-size:12px;color:var(--muted)}.canvas-controls small{font-size:11px;color:var(--muted);flex:1;min-width:180px}.policy-flow{height:clamp(360px,54vh,640px);position:relative;background:var(--panel)}.policy-flow :deep(.vue-flow__pane){background-image:radial-gradient(var(--border) 1px,transparent 1px);background-size:20px 20px}.policy-flow :deep(.vue-flow__edge-path){stroke:var(--muted);stroke-width:2}.canvas-empty{position:absolute;top:45%;width:100%;text-align:center;padding:16px;color:var(--muted);pointer-events:none}.form-editor{padding:14px;min-width:0}.form-editor table{min-width:760px}.form-editor td{max-width:320px;white-space:normal;overflow-wrap:anywhere}.form-editor tbody tr{cursor:pointer}.node-link{border:0;background:none;color:var(--field-value);text-align:left;padding:0;cursor:pointer;font:inherit;font-weight:700}.connection-list{padding:12px 16px;border-top:1px solid var(--border)}.connection-list summary{cursor:pointer;font-weight:600}.connection-list>div{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:8px 0;overflow-wrap:anywhere}.node-dialog{display:grid;gap:18px;min-width:0}.node-dialog h3{font-size:13px;margin:0 0 8px}.node-dialog p{font-size:12px;overflow-wrap:anywhere}.node-dialog .form-actions{flex-wrap:wrap}.node-dialog section{border-top:1px solid var(--border);padding-top:12px}@media(max-width:600px){.graph-count{margin-left:0;flex-basis:100%}.policy-editor-tabs{padding:0}.editor-tools label{flex-basis:100%}.canvas-controls small{flex-basis:100%}.policy-flow{height:400px}}
</style>
