<script setup>
import {ref,onMounted} from 'vue'
import {api} from '../../services/api.js'
const fields={application:'Application',environment:'Environment',workload_role:'Workload role',business_owner:'Business owner',criticality:'Criticality'}
const settings=ref({enabled:false,dependencyAlerts:false,rules:[]}),groups=ref([]),source=ref('azure-tag'),field=ref('application'),match=ref(''),value=ref(''),error=ref(''),message=ref(''),busy=ref(false)
async function load(){try{const [s,g]=await Promise.all([api('/settings/application-metadata'),api('/node-groups')]);settings.value={enabled:s.enabled,dependencyAlerts:s.dependencyAlerts,rules:s.rules};groups.value=g}catch(e){error.value=e.message}}
function add(){if(!match.value.trim())return;const r={id:crypto.randomUUID(),source:source.value};if(source.value==='azure-tag')Object.assign(r,{field:field.value,tag:match.value.trim()});else Object.assign(r,{[source.value==='ad-ou'?'dn':'groupId']:match.value.trim(),values:{[field.value]:value.value.trim()||null}});settings.value.rules.push(r);match.value='';value.value=''}
async function save(){busy.value=true;error.value='';message.value='';try{await api('/settings/application-metadata',{method:'PUT',body:settings.value});const result=await api('/application-proposals/refresh',{method:'POST',body:{}});message.value=`Saved. ${result.created} proposals created in this batch. Review pending changes in each asset’s Application ownership details.`}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(load)
</script>
<template><section class="metadata-sources"><h3>Application metadata sources</h3><p class="muted">Approved mappings create proposals from Azure tags, AD organizational units and node groups. Each change needs review before it can affect dynamic membership or policy targets.</p><p v-if="error" class="error-msg" role="alert">{{error}}</p><p v-if="message" role="status">{{message}}</p><div class="actions"><label class="switch-field"><input v-model="settings.enabled" type="checkbox" role="switch"><span class="switch-control" aria-hidden="true"></span><span>Refresh metadata proposals</span></label><label class="switch-field"><input v-model="settings.dependencyAlerts" type="checkbox" role="switch"><span class="switch-control" aria-hidden="true"></span><span>Notify on new observed dependencies</span></label></div><form class="source-form" @submit.prevent="add"><label>Source<select v-model="source" @change="match=''"> <option value="azure-tag">Azure tag</option><option value="ad-ou">AD organizational unit</option><option value="node-group">Node group</option></select></label><label>Metadata field<select v-model="field"><option v-for="(label,key) in fields" :key="key" :value="key">{{label}}</option></select></label><label>{{source==='azure-tag'?'Tag key':source==='ad-ou'?'OU distinguished name':'Node group'}}<select v-if="source==='node-group'" v-model="match" required><option value="">Select group</option><option v-for="g in groups" :key="g.id" :value="g.id">{{g.name}}</option></select><input v-else v-model="match" :placeholder="source==='ad-ou'?'OU=Servers,DC=example,DC=com':'application'" required></label><label v-if="source!=='azure-tag'">Value<select v-if="field==='criticality'" v-model="value" required><option value="">Select criticality</option><option v-for="v in ['low','medium','high','critical']" :key="v">{{v}}</option></select><input v-else v-model="value" maxlength="120" required></label><button class="button secondary" :disabled="settings.rules.length>=100">Add mapping</button></form><div class="table-wrap"><table><thead><tr><th>Source</th><th>Match</th><th>Metadata</th><th></th></tr></thead><tbody><tr v-for="(r,index) in settings.rules" :key="r.id"><td>{{r.source}}</td><td>{{r.tag||r.dn||groups.find(g=>g.id===r.groupId)?.name||r.groupId}}</td><td>{{r.field?fields[r.field]+' ← tag value':Object.entries(r.values).map(([k,v])=>fields[k]+': '+v).join(' · ')}}</td><td><button class="button small secondary" @click="settings.rules.splice(index,1)">Remove mapping</button></td></tr></tbody></table></div><button class="button primary" :disabled="busy" @click="save">Save source mappings</button></section></template>
<style scoped>.metadata-sources{border-top:1px solid var(--border);margin-top:20px;padding-top:16px;min-width:0}.source-form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;align-items:end;margin:16px 0}.source-form label{display:grid;gap:6px}.actions{display:flex;gap:16px;flex-wrap:wrap;margin:16px 0}.table-wrap{overflow:auto;max-width:100%;margin:16px 0}table{width:100%}td{max-width:50ch;overflow-wrap:anywhere}@media(max-width:850px){.source-form{grid-template-columns:1fr}}</style>
