<script setup>
import {ref,onMounted,watch} from 'vue'
import {api,session} from '../../services/api.js'
import MetadataSources from './MetadataSources.vue'
import GlassWindow from '../GlassWindow.vue'
const props=defineProps({kind:String}),result=ref({items:[],total:0}),page=ref(1),application=ref(''),connectionId=ref(''),connections=ref([]),error=ref(''),busy=ref(false),detail=ref(null)
async function load(){busy.value=true;error.value='';try{result.value=await api((props.kind==='applications'?'/mapping/applications':'/mapping/cloud-context')+'?'+new URLSearchParams({page:page.value,pageSize:25,...(application.value?{application:application.value}:{}),...(connectionId.value?{connectionId:connectionId.value}:{})}))}catch(e){error.value=e.message}finally{busy.value=false}}
async function refreshCloud(){busy.value=true;error.value='';try{await api(`/discovery/azure/connections/${connectionId.value}/network-context`,{method:'POST',body:{}});await load()}catch(e){error.value=e.message}finally{busy.value=false}}
watch(()=>props.kind,()=>{page.value=1;load()});onMounted(async()=>{await load();if(props.kind==='cloud')try{connections.value=await api('/discovery/azure/connections')}catch(e){error.value=e.message}})
</script>
<template><section class="panel glass"><div class="panel-title"><h2>{{kind==='applications'?'Application dependencies':'Cloud network configuration'}}</h2></div><div class="body"><p v-if="error" class="error-msg">{{error}}</p><p class="muted">{{kind==='applications'?'Dependencies come from observed traffic. Review the evidence before proposing an allow rule.':'Configured VNets, NICs, security groups and routes do not prove reachability. Service tags, NAT and effective path evaluation remain indeterminate.'}}</p><form class="actions" @submit.prevent="page=1;load()"><input v-if="kind==='applications'" v-model="application" placeholder="Application name" aria-label="Application name"><select v-else v-model="connectionId" aria-label="Azure network connection"><option value="">All connections</option><option v-for="c in connections" :key="c.id" :value="c.id">{{c.name}}</option></select><button class="button secondary" :disabled="busy">Search</button><button v-if="kind==='cloud'&&['admin','owner'].includes(session.user?.role)" type="button" class="button secondary" :disabled="busy||!connectionId" @click="refreshCloud">Read cloud configuration</button></form><div class="table-wrap"><table v-if="kind==='applications'"><thead><tr><th>Source application</th><th>Destination application</th><th>Endpoints</th><th>Service</th><th>Last observed</th><th></th></tr></thead><tbody><tr v-for="r in result.items" :key="r.map_key"><td>{{r.source_application||'Unassigned'}}</td><td>{{r.destination_application||'Unassigned'}}</td><td>{{r.source_ip}} → {{r.destination_ip}}</td><td>{{r.protocol}} / {{r.destination_port}}</td><td>{{new Date(r.last_seen_at).toLocaleString()}}</td><td><a :href="r.activitiesUrl">Flow evidence</a></td></tr></tbody></table><table v-else><thead><tr><th>Resource</th><th>Type</th><th>Evidence</th><th>Captured</th><th></th></tr></thead><tbody><tr v-for="r in result.items" :key="r.resource_id"><td>{{r.snapshot.name||r.resource_id}}</td><td>{{r.kind}}</td><td>Configured · path indeterminate</td><td>{{new Date(r.observed_at).toLocaleString()}}</td><td><button class="button small secondary" @click="detail=r">Details</button></td></tr></tbody></table></div><p v-if="!result.items.length">No matching evidence.</p><div class="actions"><span>{{result.total}} records · Page {{page}}</span><button class="button secondary" :disabled="page===1||busy" @click="page--;load()">Previous</button><button class="button secondary" :disabled="page*25>=result.total||busy" @click="page++;load()">Next</button></div><MetadataSources v-if="kind==='applications'&&['owner','admin'].includes(session.user?.role)"/></div><GlassWindow :model-value="!!detail" title="Configured cloud resource" @update:model-value="detail=null"><pre>{{JSON.stringify(detail?.snapshot,null,2)}}</pre></GlassWindow></section></template>
<style scoped>.body{padding:16px;min-width:0}.actions{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin:16px 0}.table-wrap{max-width:100%;overflow:auto}table{width:100%}td{max-width:45ch;overflow-wrap:anywhere}pre{padding:16px;white-space:pre-wrap;overflow-wrap:anywhere}</style>
