import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import {spawnSync} from 'node:child_process'
const dir=fs.mkdtempSync(os.tmpdir()+'/winfire-contain-');process.env.DATA_DIR=dir;process.env.NODE_ENV='test'
const {db,run,one,id}=await import('../src/db.js')
const {containmentPreview,queueContainment,containment,restoreContainment,processContainment,blockedAddressRanges}=await import('../src/services/containment.js')
const {linuxContainmentCommand}=await import('../src/linuxContainment.js')
const user={id:id(),role:'owner',email:'contain@example.test'};run('INSERT INTO users(id,email,password_hash,role) VALUES(?,?,?,?)',user.id,user.email,'fixture',user.role)
run("INSERT INTO app_settings(key,value) VALUES('local_asset_cidrs','[\"10.42.0.0/24\"]') ON CONFLICT(key) DO UPDATE SET value=excluded.value")
for(const [key,transport] of [['windows','winrm'],['linux','ssh'],['switch','snmp']])run('INSERT INTO nodes(id,hostname,ip,transport,connection_mode,os_version) VALUES(?,?,?,?,?,?)',key,key,'10.42.0.'+({windows:1,linux:2,switch:3}[key]),transport,'agentless','10.0.26100')
const input={nodeIds:['windows','linux'],reason:'Disposable isolation test',seconds:600,protectedCidrs:['10.42.0.10/32'],incidentId:'INC-test'}
const calls=[],states=new Map(),driver={async health(n){calls.push(['health',n.id])},async start(n,args){calls.push(['start',n.id]);const result={phase:'applied',nativeRecovery:true};states.set(args.id,result);return result},async restore(n,args){calls.push(['restore',n.id]);const result={phase:'restored',nativeRecovery:true};states.set(args.id,result);return result}}
test.after(()=>{db.close();fs.rmSync(dir,{recursive:true,force:true})})
test('preview excludes unsupported transports and requires configured controller peers and pilot authorization',()=>{assert.equal(containmentPreview(input,user).canStart,false);assert.throws(()=>queueContainment(input,user),/authorized pilot/);process.env.WINFIRE_CONTAINMENT_CONTROL_CIDRS='10.42.0.100/32';process.env.WINFIRE_POLICY_SAFETY_PILOT_NODES='windows,linux';assert.equal(containmentPreview(input,user).canStart,true);assert.equal(containmentPreview({...input,nodeIds:['switch']},user).targets[0].supported,false);const ranges=blockedAddressRanges(['0.0.0.0/1','128.0.0.0/1','::/0']);assert.deepEqual(ranges,[]);assert.deepEqual(blockedAddressRanges(['10.0.0.0/8','::/0']),['0.0.0.0-9.255.255.255','11.0.0.0-255.255.255.255'])})
test('containment persists per-node outcomes and explicit restore affects only its transaction IDs',async()=>{const j=queueContainment(input,user);await processContainment({driver});assert.equal(containment(j.id).status,'active');assert.equal(calls.filter(([op])=>op==='start').length,2);assert.throws(()=>queueContainment(input,user),/unresolved/);restoreContainment(j.id,'Incident resolved',user);await processContainment({driver});assert.equal(containment(j.id).status,'restored');assert.ok(containment(j.id).targets.every(t=>t.status==='restored'));assert.equal(calls.filter(([op])=>op==='restore').length,2)})
test('lost start reply and offline restore remain visible until a verified retry',async()=>{const j=queueContainment({...input,nodeIds:['linux']},user);await processContainment({driver:{...driver,async start(n,args){await driver.start(n,args);throw Error('Reply lost')},async restore(){throw Error('Offline')}}});assert.equal(containment(j.id).status,'partial');assert.equal(containment(j.id).targets[0].status,'restore-failed');restoreContainment(j.id,'Reconnect and restore',user);await processContainment({driver});assert.equal(containment(j.id).status,'restored')})
test('expired controller jobs restore instead of rearming or extending host leases',async()=>{const j=queueContainment({...input,nodeIds:['windows']},user);await processContainment({driver});const writes=calls.filter(([op])=>op==='start').length;await processContainment({driver,at:Date.now()+700000});assert.equal(containment(j.id).status,'restored');assert.equal(calls.filter(([op])=>op==='start').length,writes)})
test('Linux helper is generated from a fixed script and rejects arbitrary operations/arguments',()=>{assert.throws(()=>linuxContainmentCommand('execute',{id:id()}),/Unsupported/);assert.throws(()=>linuxContainmentCommand('containment_start',{id:id(),seconds:600,protectedCidrs:['x; rm']}),/CIDR/);assert.match(linuxContainmentCommand('containment_restore',{id:id()}),/^sudo -n python3 -c /);const r=spawnSync('python3',['-c',`import importlib.util\ns=importlib.util.spec_from_file_location('helper','api/sidecar/linux_containment.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m)\nr=m.rules('wfcontain_test',['10.42.0.100/32','::1/128'],600)\nassert 'flags timeout' in r and 'meta nfproto @lease drop' in r and 'flush' not in r\nassert r.index('ip saddr 10.42.0.100/32 return') < r.index('meta nfproto @lease drop')\n`],{encoding:'utf8'});assert.equal(r.status,0,r.stderr)})
test('native nftables expiry and restore preserve foreign rules in an isolated network namespace',{timeout:15000},t=>{const probe=spawnSync('unshare',['--user','--map-root-user','--net','true'],{encoding:'utf8',timeout:3000});if(probe.status!==0)return t.skip('User/network namespaces are unavailable');const r=spawnSync('unshare',['--user','--map-root-user','--net','python3','api/tests/linux_containment_native.py'],{encoding:'utf8',timeout:12000});assert.equal(r.status,0,r.stderr)})
