import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {execFileSync} from 'node:child_process'
import supertest from 'supertest'
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'winfire-connections-'))
process.env.DATA_DIR=dir;process.env.NODE_ENV='test';process.env.BOOTSTRAP_EMAIL='connections@example.test';process.env.BOOTSTRAP_PASSWORD='connections-test-123'
const {app}=await import('../src/app.js')
const {db,run,one,all}=await import('../src/db.js')
const {bootstrap}=await import('../src/security.js')
const {canonicalIp,normalizeCidrs,subnetMatcher,outsideLocal,boundaryState,inventoryEligibleIp}=await import('../src/services/networkBoundary.js')
const {processInternetIndex,listConnections,connectionSummary,connectionDetails,connectionEndpoints}=await import('../src/services/internetConnections.js')
const {processPeerDns,peerDetails,enqueuePeer,pruneInternetPeers}=await import('../src/services/internetPeers.js')
const {compactDueEvents}=await import('../src/maintenance.js')
const {recordNetworkFlow,mappingRows}=await import('../src/services/networkMapping.js')
const {registerHost}=await import('../src/networkDiscovery.js')
test.after(()=>{db.close();fs.rmSync(dir,{recursive:true,force:true})})
const cidrs=['192.168.10.0/24','2001:db8:1::/64','8.8.4.0/24']
const configure=values=>run("INSERT INTO app_settings(key,value) VALUES('local_asset_cidrs',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",JSON.stringify(values))
function drain(limit=2){for(let i=0;i<100;i++){processInternetIndex({limit});if(!boundaryState().pending&&!one('SELECT event_id FROM internet_event_queue LIMIT 1'))return}throw Error('Index did not finish')}
const at='2026-09-24T10:00:00.000Z'
function event(id,src='192.168.10.10',dst='1.1.1.1',direction='out',action='allow',node='host'){
  run("INSERT INTO log_events(id,node_id,event_id,action,src_ip,src_port,dst_ip,dst_port,direction,protocol,program,event_type,event_time) VALUES(?,?,5156,?,?,50000,?,443,?,'TCP','browser.exe','firewall',?)",id,node,action,src,dst,direction,at)
  recordNetworkFlow(node,{srcIp:src,srcPort:50000,dstIp:dst,dstPort:443,direction,action,protocol:'TCP',eventType:'firewall',eventTime:at})
}
let auth
test('boundary validates dual-stack scopes, mapped addresses, /0 and special peers',()=>{
  configure([]);assert.equal(boundaryState().configurationNeeded,true)
  assert.equal(outsideLocal('1.1.1.1',[]),false)
  assert.deepEqual(normalizeCidrs(['192.168.10.0/24\\n2001:db8:1::/64']),['192.168.10.0/24','2001:db8:1::/64'])
  assert.equal(canonicalIp('::ffff:c0a8:0a0a'),'192.168.10.10')
  assert.equal(subnetMatcher('192.168.10.0/24')('::ffff:192.168.10.10'),true)
  assert.equal(subnetMatcher('0.0.0.0/0')('255.1.2.3'),true)
  assert.equal(subnetMatcher('::/0')('2001:4860::1'),true)
  assert.equal(subnetMatcher('2001:db8::/32')('2001:db8:1::1'),true)
  for(const bad of ['10.0.0.1','10.0.0.1/','10.0.0.1/-1','10.0.0.1/33','::/129','10.0.0.0/8/4','garbage/3'])assert.throws(()=>subnetMatcher(bad))
  for(const special of ['127.0.0.1','::1','169.254.1.1','fe80::1','224.0.0.1','ff02::1','255.255.255.255','0.0.0.0','::','bad'])assert.equal(outsideLocal(special,cidrs),false,special)
  assert.equal(outsideLocal('10.0.0.1',cidrs),true)
  assert.equal(outsideLocal('100.64.0.1',cidrs),true)
  assert.equal(outsideLocal('8.8.4.4',cidrs),false)
  assert.equal(outsideLocal('192.168.10.10',['192.168.0.0/16','192.168.10.0/24']),false)
  assert.equal(outsideLocal('2001:4860::1',['192.168.10.0/24']),true)
  assert.equal(outsideLocal('192.168.10.255',cidrs),false)
})
test('retained indexing resumes, compaction is equivalent, stable event IDs and filters agree',async()=>{
  configure(cidrs);await bootstrap();const login=await supertest(app).post('/api/v1/auth/login').send({email:process.env.BOOTSTRAP_EMAIL,password:process.env.BOOTSTRAP_PASSWORD}).expect(200);auth=r=>r.set('Authorization','Bearer '+login.body.accessToken)
  run("INSERT INTO nodes(id,hostname,ip) VALUES('host','Workstation','192.168.10.10'),('router','Gateway','192.168.10.1')")
  run("UPDATE nodes SET device_type='router' WHERE id='router'")
  event('raw');event('blocked','192.168.10.10','10.7.0.1','out','block');event('v6','2001:db8:1::10','2001:4860:4860::8888');event('internal','192.168.10.10','8.8.4.4');event('multicast','192.168.10.10','224.0.0.1');event('inbound','9.9.9.9','192.168.10.10','in');event('legacy-inbound','192.168.10.10','9.9.9.9','in');event('forwarded','192.168.10.22','1.0.0.1','out','allow','router')
  run("DELETE FROM internet_event_queue WHERE event_id<>'raw'") // Simulate retained history predating queue triggers.
  run('UPDATE internet_index_state SET active_revision=NULL,desired_revision=NULL,cursor=0,high_water=0 WHERE id=1')
  processInternetIndex({limit:2});const cursor=boundaryState().cursor;assert.ok(cursor>0);assert.equal(listConnections({}).total,0)
  execFileSync(process.execPath,['--input-type=module','-e',"import {processInternetIndex} from './api/src/services/internetConnections.js';import {db} from './api/src/db.js';processInternetIndex({limit:2});db.close()"],{env:process.env})
  assert.ok(boundaryState().cursor>cursor);drain()
  const initial=listConnections({});assert.equal(initial.total,4);assert.equal(initial.limit,25);assert.equal(initial.summary.peers,4);assert.equal(initial.summary.blocked,1)
  assert.equal(listConnections({direction:'in'}).total,2)
  assert.equal(listConnections({ip:'10.0.0.0/8'}).items[0].event_id,'blocked')
  assert.equal(listConnections({protocol:'6',port:443,q:'workstation',limit:1,page:2}).items.length,1)
  const detail=connectionDetails('raw');assert.equal(detail.event.id,'raw');assert.ok(detail.mappingReferences.length);assert.equal(detail.ruleEligible,true)
  assert.equal(connectionDetails('forwarded').ruleEligible,false)
  assert.equal(connectionDetails('legacy-inbound').local_ip,'192.168.10.10');assert.equal(connectionDetails('legacy-inbound').peer_ip,'9.9.9.9')
  const activity=await auth(supertest(app).get('/api/v1/logs/search?id=raw&hideLoopback=false')).expect(200);assert.equal(activity.body.items[0].id,'raw')
  assert.equal(one('SELECT count(*) n FROM nodes').n,2)
  const before=initial.items.map(r=>[r.id,r.peer_ip,r.program]).sort();compactDueEvents(new Date(),100);drain()
  assert.deepEqual(listConnections({}).items.map(r=>[r.id,r.peer_ip,r.program]).sort(),before)
  assert.equal(mappingRows({external:'1'}).total,6)
  const summary=await auth(supertest(app).get('/api/v1/internet/connections/summary?action=block')).expect(200);assert.equal(summary.body.events,1)
  const exported=await auth(supertest(app).get('/api/v1/internet/connections/export')).expect(200);assert.equal(exported.body.total,4)
  await supertest(app).get('/api/v1/internet/connections').expect(401)
  await auth(supertest(app).get('/api/v1/internet/connections?ip=invalid')).expect(400)
})
test('CIDR changes publish atomically, keep historical scope, and never register external assets',async()=>{
  const before=connectionSummary({});configure([...cidrs,'10.0.0.0/8']);assert.equal(boundaryState().pending,true)
  processInternetIndex({limit:1});assert.equal(connectionSummary({}).events,before.events);assert.equal(mappingRows({external:'1'}).total,6)
  drain();assert.equal(connectionSummary({}).events,3);assert.equal(mappingRows({external:'1'}).total,5)
  const row=one("SELECT * FROM internet_connections WHERE event_id='blocked' AND revision=(SELECT active_revision FROM internet_index_state)");assert.equal(row.outside,0);assert.equal(row.original_scope,'outside');assert.notEqual(row.original_revision,row.revision)
  configure(cidrs);drain();assert.equal(connectionSummary({}).events,4)
  assert.equal(inventoryEligibleIp('10.7.0.1'),false);assert.equal((await registerHost('10.7.0.1','test')).skipped,true);assert.equal(one('SELECT count(*) n FROM nodes').n,2)
  const roaming=connectionEndpoints({src_ip:'10.7.2.1',dst_ip:'8.8.8.8',direction:'out'}, {ip:'192.168.10.10'},cidrs);assert.equal(roaming.attribution,'reported-direction-roaming');assert.equal(roaming.local,'10.7.2.1')
  const ambiguous=connectionEndpoints({src_ip:'10.7.2.1',dst_ip:'8.8.8.8'}, {ip:'192.168.10.1',device_type:'router'},cidrs);assert.equal(ambiguous.direction,'unknown');assert.equal(ambiguous.attribution,'ambiguous')
})
test('auditors read connections, exclusions apply consistently, and reindexing is idempotent',async()=>{
  const user=one('SELECT password_hash FROM users WHERE email=?',process.env.BOOTSTRAP_EMAIL)
  run("INSERT INTO users(id,email,password_hash,role,email_verified) VALUES('auditor','auditor@connections.test',?,'auditor',1)",user.password_hash)
  const login=await supertest(app).post('/api/v1/auth/login').send({email:'auditor@connections.test',password:process.env.BOOTSTRAP_PASSWORD}).expect(200)
  const read=req=>req.set('Authorization','Bearer '+login.body.accessToken)
  const peerId=connectionDetails('blocked').peer_id
  for(const route of ['/internet/connections','/internet/connections/summary','/internet/connections/export','/internet/connections/raw',`/internet/peers/${peerId}`])await read(supertest(app).get('/api/v1'+route)).expect(200)
  await read(supertest(app).post(`/api/v1/internet/peers/${peerId}/resolve`)).send({}).expect(403)
  run("INSERT INTO node_groups(id,name) VALUES('test-group','Test group')")
  run("INSERT INTO node_group_members(group_id,node_id) VALUES('test-group','host')")
  assert.equal(listConnections({groupId:'test-group',from:at,to:at}).total,3)
  assert.equal(listConnections({from:'2026-09-25T00:00:00Z'}).total,0)
  run('INSERT OR IGNORE INTO internet_event_queue(event_id) SELECT id FROM log_events');drain()
  assert.equal(listConnections({}).total,4)
  const ignored=await auth(supertest(app).post('/api/v1/logs/blocked/ignore-traffic')).send({}).expect(201)
  assert.equal(listConnections({}).total,3);assert.equal(connectionSummary({action:'block'}).events,0)
  await auth(supertest(app).get('/api/v1/internet/connections/blocked')).expect(404)
  assert.equal((await auth(supertest(app).get('/api/v1/internet/connections/export')).expect(200)).body.total,3)
  const lookedUp=[];await processPeerDns({lookup:async ip=>{lookedUp.push(ip);return []}})
  assert.ok(!lookedUp.includes('10.7.0.1'),'Ignored peers must not start DNS lookups')
  await auth(supertest(app).delete(`/api/v1/settings/traffic-ignores/${ignored.body.id}`)).expect(200)
  assert.equal(listConnections({}).total,4)
  run("UPDATE internet_peers SET status='pending',next_lookup_at=NULL,checked_at=NULL,names_json='[]'")
  run('DELETE FROM internet_peer_dns_history')
  event('correction');drain();assert.equal(listConnections({}).total,5)
  run("UPDATE log_events SET dst_ip='invalid' WHERE id='correction'");drain();assert.equal(listConnections({}).total,4)
  run("DELETE FROM log_events WHERE id='correction'")
})
test('PTR jobs coalesce, retain evidence on timeout, refresh changed answers and negatively cache',async()=>{
  const at=new Date('2027-01-01T00:00:00Z'),raw=connectionDetails('raw'),id=raw.peer_id
  assert.equal(enqueuePeer(id).coalesced,true)
  const lease=new Date(at.getTime()+60000).toISOString()
  run('UPDATE internet_peers SET lease_until=?',lease)
  assert.equal(await processPeerDns({at,lookup:async()=>{throw Error('Active lease must not be claimed')}}),0)
  run('UPDATE internet_peers SET lease_until=?',new Date(at.getTime()-1).toISOString())
  const counts=new Map();await processPeerDns({at,lookup:async ip=>{counts.set(ip,(counts.get(ip)||0)+1);if(ip==='10.7.0.1')throw Object.assign(Error('no data'),{code:'ENODATA'});return ['PTR.EXAMPLE.','other.example']}})
  assert.ok([...counts.values()].every(n=>n===1));assert.deepEqual(peerDetails(id).names,['other.example','ptr.example'])
  assert.equal(peerDetails(connectionDetails('blocked').peer_id).status,'not-found')
  assert.equal(await processPeerDns({at,lookup:()=>{throw Error('Should remain cached')}}),0)
  await processPeerDns({at:new Date(at.getTime()+25*3600000),lookup:async()=>{throw Object.assign(Error('timeout'),{code:'ETIMEOUT'})}})
  assert.equal(peerDetails(id).status,'stale');assert.deepEqual(peerDetails(id).names,['other.example','ptr.example'])
  await processPeerDns({at:new Date(at.getTime()+26*3600000),lookup:async()=>['changed.example']})
  assert.deepEqual(peerDetails(id).names,['changed.example']);assert.equal(peerDetails(id).history.length,3)
  assert.equal(listConnections({hostname:'changed.example'}).total,4)
  assert.equal(one('SELECT count(*) n FROM nodes').n,2)
  run('DELETE FROM log_events');drain();pruneInternetPeers(new Date('2030-01-01T00:00:00Z'));assert.equal(one('SELECT count(*) n FROM internet_peers').n,0)
})
