import test from 'node:test'
import assert from 'node:assert/strict'
import {randomUUID} from 'node:crypto'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import supertest from 'supertest'

const dir=fs.mkdtempSync(path.join(os.tmpdir(),'winfire-access-test-'))
process.env.DATA_DIR=dir
process.env.BOOTSTRAP_EMAIL='owner@access.test'
process.env.BOOTSTRAP_PASSWORD='access-owner-password'
const {app}=await import('../src/app.js')
const {bootstrap}=await import('../src/security.js')
const {db}=await import('../src/db.js')
await bootstrap()
const request=supertest(app)
test.after(()=>{db.close();fs.rmSync(dir,{recursive:true,force:true})})

test('role permissions and resource grants scope policy, group and vault mutations',async()=>{
  const owner=await request.post('/api/v1/auth/login').send({email:'owner@access.test',password:'access-owner-password'}).expect(200)
  const asOwner=req=>req.set('Authorization',`Bearer ${owner.body.accessToken}`)
  const editorUser=await asOwner(request.post('/api/v1/users')).send({email:'editor@access.test',password:'access-editor-password',role:'editor'}).expect(201)
  const editor=await request.post('/api/v1/auth/login').send({email:'editor@access.test',password:'access-editor-password'}).expect(200)
  const asEditor=req=>req.set('Authorization',`Bearer ${editor.body.accessToken}`)
  assert.equal(db.prepare("SELECT COUNT(*) n FROM role_permissions WHERE role_id='editor' AND permission_id='portal.edit'").get().n,1)
  const policy=await asOwner(request.post('/api/v1/policies')).send({name:'Owner policy'}).expect(201)
  const group=await asOwner(request.post('/api/v1/node-groups')).send({name:'Owner group'}).expect(201)
  const node=await asOwner(request.post('/api/v1/nodes')).send({hostname:'access-node'}).expect(201)
  const graph={nodes:[{id:'rule',type:'allow',data:{name:'HTTPS',localPort:'443'}}],edges:[]}
  const version=await asOwner(request.post(`/api/v1/policies/${policy.body.id}/versions`)).send({graph}).expect(201)
  const credential=await asOwner(request.post('/api/v1/credentials')).send({name:'Owner credential',type:'local',username:'owner-user',password:'vault-secret'}).expect(201)
  const shareable=await asOwner(request.get('/api/v1/access/resources')).expect(200)
  assert.deepEqual(shareable.body.map(item=>item.type).sort(),['credential','node_group','policy','policy'])
  const shareTargets=await asOwner(request.get('/api/v1/access/users')).expect(200)
  assert.equal(shareTargets.body[0].email,'editor@access.test')
  assert.equal(shareTargets.body[0].password_hash,undefined)
  assert.deepEqual((await asEditor(request.get('/api/v1/access/resources')).expect(200)).body,[])
  const visiblePolicies=(await asEditor(request.get('/api/v1/policies')).expect(200)).body
  assert.deepEqual(visiblePolicies.map(item=>item.id),[node.body.training.generatedPolicyId])
  assert.deepEqual((await asEditor(request.get('/api/v1/node-groups')).expect(200)).body.map(item=>item.id),['winfire-global-all-nodes'])
  await asEditor(request.get(`/api/v1/policies/${policy.body.id}`)).expect(403)
  await asEditor(request.post(`/api/v1/policies/${policy.body.id}/versions`)).send({graph}).expect(403)
  await asEditor(request.post('/api/v1/drift/checks')).send({policyId:policy.body.id}).expect(403)
  await asEditor(request.post('/api/v1/verifier/runs')).send({policyId:policy.body.id}).expect(403)
  assert.deepEqual((await asEditor(request.post('/api/v1/drift/checks')).send({}).expect(201)).body.checks,[])
  assert.deepEqual((await asEditor(request.post('/api/v1/verifier/runs')).send({}).expect(201)).body.results,[])
  const driftId=randomUUID(),runId=randomUUID(),resultId=randomUUID()
  db.prepare('INSERT INTO policy_drift_checks(id,policy_id,version_id,node_id,status,diff_json) VALUES(?,?,?,?,?,?)').run(driftId,policy.body.id,version.body.id,node.body.id,'drift','{"add":[{"name":"Private rule"}]}')
  db.prepare('INSERT INTO verifier_runs(id,status,requested_by) VALUES(?,?,?)').run(runId,'complete',owner.body.user.id)
  db.prepare('INSERT INTO verifier_results(id,run_id,node_id,policy_id,port,proto,status) VALUES(?,?,?,?,?,?,?)').run(resultId,runId,node.body.id,policy.body.id,443,'TCP','fail')
  assert.deepEqual((await asEditor(request.get('/api/v1/drift/checks')).expect(200)).body,[])
  assert.deepEqual((await asEditor(request.get('/api/v1/verifier/results')).expect(200)).body,[])
  assert.deepEqual((await asEditor(request.get('/api/v1/reports/verification')).expect(200)).body,[])
  await asEditor(request.get(`/api/v1/verifier/runs/${runId}`)).expect(404)
  await asEditor(request.post(`/api/v1/node-groups/${group.body.id}/members`)).send({nodeId:node.body.id}).expect(403)
  await asEditor(request.patch(`/api/v1/credentials/${credential.body.id}`)).send({password:'unauthorized'}).expect(403)
  const privateList=await asEditor(request.get('/api/v1/credentials')).expect(200)
  assert.equal(privateList.body.some(item=>item.id===credential.body.id),false)
  for(const [type,resourceId,permission] of [['policy',policy.body.id,'write'],['node_group',group.body.id,'write'],['credential',credential.body.id,'read']])await asOwner(request.post('/api/v1/access/grants')).send({type,resourceId,userId:editorUser.body.id,permission}).expect(201)
  assert.equal((await asEditor(request.get('/api/v1/access/resources')).expect(200)).body.length,2)
  const readablePolicies=(await asEditor(request.get('/api/v1/policies')).expect(200)).body
  assert.equal(readablePolicies.some(item=>item.id===policy.body.id),true)
  assert.equal(readablePolicies.filter(item=>item.origin==='learned').length,1)
  assert.equal((await asEditor(request.get('/api/v1/node-groups')).expect(200)).body.some(item=>item.id===group.body.id),true)
  assert.equal((await asEditor(request.get('/api/v1/drift/checks')).expect(200)).body[0].id,driftId)
  assert.equal((await asEditor(request.get('/api/v1/verifier/results')).expect(200)).body[0].id,resultId)
  assert.equal((await asEditor(request.get('/api/v1/reports/verification')).expect(200)).body[0].policy,'Owner policy')
  await asEditor(request.post(`/api/v1/policies/${policy.body.id}/versions`)).send({graph}).expect(201)
  await asEditor(request.post(`/api/v1/node-groups/${group.body.id}/members`)).send({nodeId:node.body.id}).expect(200)
  const directAssignment=await asOwner(request.post(`/api/v1/policies/${policy.body.id}/assignments`)).send({nodeId:node.body.id}).expect(201)
  const groupAssignment=await asEditor(request.post(`/api/v1/policies/${policy.body.id}/assignments`)).send({nodeGroupId:group.body.id}).expect(201)
  const unassigned=await asEditor(request.delete(`/api/v1/policies/${policy.body.id}/assignments/${groupAssignment.body.id}`)).expect(200)
  assert.equal(unassigned.body.retainedByOtherAssignment,1)
  const sharedList=await asEditor(request.get('/api/v1/credentials')).expect(200)
  assert.equal(sharedList.body.some(item=>item.id===credential.body.id),true)
  assert.equal(sharedList.body.find(item=>item.id===credential.body.id).canWrite,false)
  await asEditor(request.post(`/api/v1/credentials/${credential.body.id}/assignments`)).send({nodeId:node.body.id}).expect(403)
  await asEditor(request.patch(`/api/v1/credentials/${credential.body.id}`)).send({password:'still-unauthorized'}).expect(403)
  await asOwner(request.post('/api/v1/access/grants')).send({type:'credential',resourceId:credential.body.id,userId:editorUser.body.id,permission:'write'}).expect(201)
  assert.equal((await asEditor(request.get('/api/v1/credentials')).expect(200)).body.find(item=>item.id===credential.body.id).canWrite,true)
  await asEditor(request.post(`/api/v1/credentials/${credential.body.id}/assignments`)).send({nodeId:node.body.id}).expect(201)
  await asEditor(request.patch(`/api/v1/credentials/${credential.body.id}`)).send({password:'rotated-secret'}).expect(200)
  const grants=await asOwner(request.get('/api/v1/access/grants').query({type:'policy',resourceId:policy.body.id})).expect(200)
  assert.equal(grants.body.length,1)
  await asOwner(request.delete(`/api/v1/access/grants/${grants.body[0].id}`)).expect(204)
  await asEditor(request.post(`/api/v1/policies/${policy.body.id}/versions`)).send({graph}).expect(403)
  await asEditor(request.delete(`/api/v1/policies/${policy.body.id}/assignments/${directAssignment.body.id}`)).expect(403)
  await asOwner(request.post(`/api/v1/policies/${policy.body.id}/assignments`)).send({nodeGroupId:group.body.id}).expect(201)
  await asEditor(request.delete(`/api/v1/node-groups/${group.body.id}/members/${node.body.id}`)).expect(403)
})
