import {spawnSync} from 'node:child_process'
import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
const dir=fs.mkdtempSync(os.tmpdir()+'/winfire-stage-');process.env.DATA_DIR=dir;process.env.NODE_ENV='test'
const {db,run,one,id,json}=await import('../src/db.js'),{compilePolicy}=await import('../../packages/shared/index.js')
const {queueSimulation,processSimulations,approveSimulation}=await import('../src/services/policySimulation.js')
const {deploymentPreview,queueDeployment,processDeployments,deployment,deploymentAction}=await import('../src/services/stagedDeployment.js')
const user={id:id(),role:'owner',email:'stage@example.test'};run('INSERT INTO users(id,email,password_hash,role) VALUES(?,?,?,?)',user.id,user.email,'fixture',user.role)
run("INSERT INTO app_settings(key,value) VALUES('local_asset_cidrs','[\"10.42.0.0/24\"]') ON CONFLICT(key) DO UPDATE SET value=excluded.value")
for(const n of ['canary','later'])run('INSERT INTO nodes(id,hostname,ip,transport,connection_mode,os_version) VALUES(?,?,?,?,?,?)',n,n,n==='canary'?'10.42.0.1':'10.42.0.2','winrm','agentless','10.0.26100')
const p=id(),v=id(),graph={nodes:[{id:'https',type:'allow',position:{x:0,y:0},data:{name:'HTTPS',direction:'out',protocol:'TCP',remotePort:'443',remoteAddress:'8.8.8.8'}}],edges:[]}
run('INSERT INTO policies(id,name,owner_user_id,current_version_id) VALUES(?,?,?,?)',p,'Stage test',user.id,v);run('INSERT INTO policy_versions(id,policy_id,version_no,graph_json,rules_compiled_json) VALUES(?,?,?,?,?)',v,p,1,json(graph),json(compilePolicy(graph,p)))
for(const n of ['canary','later'])run('INSERT INTO policy_assignments(id,policy_id,node_id) VALUES(?,?,?)',id(),p,n)
const s=queueSimulation(p,{baseVersionId:v,nodeIds:['canary','later'],from:new Date(Date.now()-3600000).toISOString(),to:new Date().toISOString()},user);processSimulations();approveSimulation(s.id,'Reviewed conservative empty evidence',user)
const input=()=>({simulationId:s.id,canaryNodeIds:['canary'],batchSize:1,recoverySeconds:600,healthPorts:[443],windowStart:new Date(Date.now()-1000).toISOString(),windowEnd:new Date(Date.now()+3600000).toISOString(),reason:'Disposable pilot test'})
const state=new Map(),calls=[]
let failCanary=false
const driver={async health(n){calls.push(['health',n.id]);if(failCanary&&n.id==='canary'&&[...state.values()].some(s=>s.node===n.id&&s.phase==='applied'))throw Error('Simulated application health failure');return {authenticated:true,checks:[{port:443,status:'open'}]}},async arm(n,args){calls.push(['arm',n.id]);const s={nativeRecovery:true,phase:'armed',node:n.id};state.set(args.id,s);return s},async apply(n,args){calls.push(['apply',n.id]);const s={...state.get(args.id),phase:'applied'};state.set(args.id,s);return s},async status(n,args){return state.get(args.id)},async commit(n,args){calls.push(['commit',n.id]);const s={...state.get(args.id),phase:'committed'};state.set(args.id,s);return s},async restore(n,args){calls.push(['restore',n.id]);const s={...state.get(args.id),phase:'restored'};state.set(args.id,s);return s}}
test.after(()=>{db.close();fs.rmSync(dir,{recursive:true,force:true})})
test('production remains gated and preview pins complete assigned target set',()=>{const preview=deploymentPreview(input(),user);assert.equal(preview.productionEnabled,false);assert.equal(preview.targets[0].pilotEnabled,false);assert.throws(()=>queueDeployment(input(),user),/blocked/);assert.deepEqual(preview.batches,[['canary'],['later']])})
let job
test('canary health failure restores it and prevents later batch writes',async()=>{process.env.WINFIRE_POLICY_SAFETY_PILOT_NODES='canary,later';job=queueDeployment(input(),user);failCanary=true;await processDeployments({driver});const result=deployment(job.id,user);assert.equal(result.status,'paused');assert.equal(result.targets.find(t=>t.node_id==='canary').status,'restored');assert.ok(!calls.some(([op,node])=>op==='apply'&&node==='later'));assert.equal(one('SELECT current_version_id FROM policies WHERE id=?',p).current_version_id,v)})
test('resume is explicit and commits batches before publishing pinned version; restore rolls back only that version',async()=>{failCanary=false;deploymentAction(job.id,'resume','Application dependency repaired',user);await processDeployments({driver});assert.equal(deployment(job.id,user).status,'queued');assert.equal(one('SELECT current_version_id FROM policies WHERE id=?',p).current_version_id,v);await processDeployments({driver});const result=deployment(job.id,user);assert.equal(result.status,'completed');assert.ok(result.targets.every(t=>t.status==='committed'));assert.equal(one('SELECT current_version_id FROM policies WHERE id=?',p).current_version_id,result.version_id);deploymentAction(job.id,'restore','Rollback pilot',user);await processDeployments({driver});assert.equal(deployment(job.id,user).status,'restored');assert.equal(one('SELECT current_version_id FROM policies WHERE id=?',p).current_version_id,v)})
test('lost arm reply restores the host transaction before later writes',async()=>{
 const j=queueDeployment(input(),user),broken={...driver,async arm(n,args){await driver.arm(n,args);throw Error('Reply lost after host armed recovery')}};await processDeployments({driver:broken});const result=deployment(j.id,user);assert.equal(result.status,'paused');assert.equal(result.targets.find(t=>t.node_id==='canary').status,'restored');assert.equal(result.targets.find(t=>t.node_id==='later').status,'pending');deploymentAction(j.id,'cancel','Close failed pilot',user);await processDeployments({driver});assert.equal(deployment(j.id,user).status,'restored')
})
test('partial restoration stays visible and can be retried without reapplying',async()=>{
 const j=queueDeployment(input(),user);await processDeployments({driver});deploymentAction(j.id,'cancel','Restore canary',user);await processDeployments({driver:{...driver,async restore(){throw Error('Host offline')}}});let result=deployment(j.id,user);assert.equal(result.status,'paused');assert.equal(result.targets.find(t=>t.node_id==='canary').status,'restore-failed');assert.throws(()=>deploymentAction(j.id,'resume','Unsafe retry',user),/Restore unresolved/);const writes=calls.filter(([op])=>op==='apply').length;deploymentAction(j.id,'restore','Host online again',user);await processDeployments({driver});result=deployment(j.id,user);assert.equal(result.status,'restored');assert.equal(calls.filter(([op])=>op==='apply').length,writes)
})
test('target membership change during health checks restores the canary and stops rollout',async()=>{
 const j=queueDeployment(input(),user);let changed=false;await processDeployments({driver:{...driver,async health(n,ports){const result=await driver.health(n,ports);if(!changed&&[...state.values()].some(s=>s.node===n.id&&s.phase==='applied')){run('DELETE FROM policy_assignments WHERE policy_id=? AND node_id=?',p,'later');changed=true}return result}}});assert.equal(deployment(j.id,user).status,'paused');assert.equal(deployment(j.id,user).targets.find(t=>t.node_id==='canary').status,'restored');deploymentAction(j.id,'cancel','Assignment changed',user);await processDeployments({driver});run('INSERT INTO policy_assignments(id,policy_id,node_id) VALUES(?,?,?)',id(),p,'later')
})
test('exception retirement follows verified deployment and reopens on restore',async()=>{
 const {createException,reviewException}=await import('../src/services/ruleLifecycle.js');const exception=createException(p,{versionId:v,ruleId:'https',owner:'Security',justification:'Temporary access',reviewAt:new Date(Date.now()+3600000).toISOString()},user);reviewException(exception.id,{action:'retire',reason:'Access no longer required'},user)
 const evaluation=queueSimulation(p,{baseVersionId:v,nodeIds:['canary','later'],graph:{nodes:[],edges:[]},from:new Date(Date.now()-1000).toISOString(),to:new Date().toISOString()},user);processSimulations();approveSimulation(evaluation.id,'Reviewed withdrawal',user);const j=queueDeployment({...input(),simulationId:evaluation.id},user);assert.equal(one('SELECT status FROM rule_exceptions WHERE id=?',exception.id).status,'retiring');assert.throws(()=>reviewException(exception.id,{action:'recertify',reason:'Conflicting review',reviewAt:new Date(Date.now()+3600000).toISOString()},user),/Finish or restore/);await processDeployments({driver});assert.equal(one('SELECT status FROM rule_exceptions WHERE id=?',exception.id).status,'retiring');await processDeployments({driver});assert.equal(one('SELECT status FROM rule_exceptions WHERE id=?',exception.id).status,'retired');deploymentAction(j.id,'restore','Restore previous exception',user);await processDeployments({driver});assert.equal(one('SELECT status FROM rule_exceptions WHERE id=?',exception.id).status,'retirement-requested')
})
test('a configured later-batch failure budget leaves a visible partial deployment without publishing',async()=>{const j=queueDeployment({...input(),maxFailures:1},user);await processDeployments({driver});await processDeployments({driver:{...driver,async health(n,ports){await driver.health(n,ports);if(n.id==='later'&&[...state.values()].some(s=>s.node===n.id&&s.phase==='applied'))throw Error('Later application health failed')}}});assert.equal(deployment(j.id,user).status,'partial');assert.equal(one('SELECT current_version_id FROM policies WHERE id=?',p).current_version_id,v);deploymentAction(j.id,'resume','Repair verified',user);await processDeployments({driver});assert.equal(deployment(j.id,user).status,'completed');deploymentAction(j.id,'restore','Finish threshold pilot',user);await processDeployments({driver});assert.equal(deployment(j.id,user).status,'restored')})

test('PowerShell adapter parses and fingerprints an empty prior policy group',t=>{const command=`$tokens=$null;$errors=$null;$ast=[System.Management.Automation.Language.Parser]::ParseFile((Join-Path (Get-Location) "packages/shared/policySafety.ps1"),[ref]$tokens,[ref]$errors);if($errors.Count){$errors;exit 1};$f=$ast.Find({param($n) $n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq "Fingerprint"},$true);Invoke-Expression $f.Extent.Text;$empty=Fingerprint @();$one=Fingerprint @([pscustomobject]@{name="test"});if(!$empty -or !$one -or $empty -eq $one){throw "Invalid fingerprints"}`;const r=spawnSync('pwsh',['-NoProfile','-NonInteractive','-Command',command],{encoding:'utf8',timeout:10000});if(r.error?.code==='ENOENT')return t.skip('PowerShell is unavailable');assert.equal(r.status,0,r.stderr)})
