<script setup>
import {computed,onMounted,ref} from 'vue'
import PageHeader from '../components/PageHeader.vue'
import {api,session} from '../services/api.js'

const events=ref([]),devices=ref([]),nodes=ref([]),groups=ref([]),users=ref([]),summary=ref({events:0,domains:0,devices:0,blocked:0,unmappedUsers:0})
const loading=ref(false),error=ref(''),page=ref(1),pageSize=ref(100),total=ref(0),totalPages=ref(0)
const filters=ref({q:'',domain:'',path:'',browser:'',action:'',deviceId:'',userId:'',from:'',to:''})
const sortBy=ref('time'),sortDir=ref('desc')
const policies=ref([]),policyDraft=ref([]),rulePattern=ref(''),ruleMatch=ref('hostname'),ruleAction=ref('block'),policyFailMode=ref('open'),policyComment=ref(''),policyBusy=ref(false),policyError=ref(''),policyMessage=ref('')
const enrollmentOpen=ref(false),enrollmentBusy=ref(false),enrollmentError=ref(''),enrollmentResult=ref(null),enrollmentForm=ref({target:'node',nodeId:'',nodeGroupId:'',userId:'',collectionLevel:'host'})
const canEnroll=computed(()=>['owner','admin','editor'].includes(session.user?.role))
const hasFilters=computed(()=>Object.values(filters.value).some(Boolean))
function query(){
  const params=new URLSearchParams({page:String(page.value),pageSize:String(pageSize.value),sortBy:sortBy.value,sortDir:sortDir.value})
  for(const [key,value] of Object.entries(filters.value))if(value)params.set(key,key==='from'||key==='to'?new Date(value).toISOString():value)
  return params.toString()
}
async function load(){
  loading.value=true;error.value=''
  try{
    const requests=[api(`/internet/events?${query()}`),api('/internet/summary'),api('/internet/devices'),api('/internet/policies'),api('/nodes'),api('/node-groups')]
    if(session.user?.role==='admin'||session.user?.role==='owner')requests.push(api('/users'))
    const [result,stats,listed,versions,availableNodes,availableGroups,availableUsers]=await Promise.all(requests)
    events.value=result.items;total.value=result.total;totalPages.value=result.totalPages;summary.value=stats;devices.value=listed;policies.value=versions;nodes.value=availableNodes;groups.value=availableGroups;users.value=availableUsers||[]
  }catch(cause){error.value=cause.message}
  finally{loading.value=false}
}
function apply(){page.value=1;load()}
function reset(){filters.value={q:'',domain:'',path:'',browser:'',action:'',deviceId:'',userId:'',from:'',to:''};apply()}
function sort(column){if(sortBy.value===column)sortDir.value=sortDir.value==='asc'?'desc':'asc';else{sortBy.value=column;sortDir.value='asc'};load()}
function move(next){if(next<1||next>totalPages.value)return;page.value=next;load()}
function openEnrollment(){enrollmentError.value='';enrollmentResult.value=null;enrollmentForm.value={target:'node',nodeId:nodes.value[0]?.id||'',nodeGroupId:'',userId:'',collectionLevel:'host'};enrollmentOpen.value=true}
async function createEnrollment(){enrollmentBusy.value=true;enrollmentError.value='';enrollmentResult.value=null;try{const body={collectionLevel:enrollmentForm.value.collectionLevel};if(enrollmentForm.value.target==='node')body.nodeId=enrollmentForm.value.nodeId;else body.nodeGroupId=enrollmentForm.value.nodeGroupId;if(enrollmentForm.value.userId)body.userId=enrollmentForm.value.userId;enrollmentResult.value=await api('/internet/enrollment',{method:'POST',body})}catch(cause){enrollmentError.value=cause.message}finally{enrollmentBusy.value=false}}
async function copyEnrollment(){if(!enrollmentResult.value?.token)return;try{await navigator.clipboard.writeText(enrollmentResult.value.token)}catch{enrollmentError.value='Copy failed; select the token text and copy it manually.'}}
function nodeLabel(event){return event.node_hostname||event.node_group_name||'Unmapped device'}
function addRule(){if(!rulePattern.value.trim())return;policyDraft.value.push({pattern:rulePattern.value.trim(),match:ruleMatch.value,action:ruleAction.value,nodeIds:[],nodeGroupIds:[],resourceTypes:['main_frame']});rulePattern.value=''}
async function stagePolicy(){policyBusy.value=true;policyError.value='';policyMessage.value='';try{await api('/internet/policies',{method:'POST',body:{rules:policyDraft.value,failMode:policyFailMode.value,comment:policyComment.value}});policyMessage.value='Internet policy staged. Publish it after review.';policyComment.value='';await load()}catch(error){policyError.value=error.message}finally{policyBusy.value=false}}
async function publishPolicy(policy){policyBusy.value=true;policyError.value='';try{await api(`/internet/policies/${policy.id}/publish`,{method:'POST'});policyMessage.value=`Internet policy version ${policy.version_no} published.`;await load()}catch(error){policyError.value=error.message}finally{policyBusy.value=false}}
async function rollbackPolicy(policy){policyBusy.value=true;policyError.value='';try{await api(`/internet/policies/${policy.id}/rollback`,{method:'POST'});policyMessage.value='Internet policy rolled back.';await load()}catch(error){policyError.value=error.message}finally{policyBusy.value=false}}
onMounted(load)
</script>

<template>
  <div class="view internet-view">
    <PageHeader eyebrow="NETWORK / VISIBILITY" title="Internet" description="Search browser navigation metadata collected from enrolled devices"><button class="button secondary" @click="load" :disabled="loading"><i class="mdi mdi-refresh"></i> Refresh</button></PageHeader>
    <div v-if="error" class="error-msg">{{error}}</div>
    <section class="metric-grid internet-metrics"><article class="metric glass"><div class="metric-top">EVENTS <i class="mdi mdi-web"></i></div><strong>{{summary.events.toLocaleString()}}</strong><small>retained navigation events</small></article><article class="metric glass"><div class="metric-top">DOMAINS <i class="mdi mdi-domain"></i></div><strong>{{summary.domains.toLocaleString()}}</strong><small>unique registrable domains</small></article><article class="metric glass"><div class="metric-top">DEVICES <i class="mdi mdi-monitor-eye"></i></div><strong>{{summary.devices.toLocaleString()}}</strong><small>enrolled browsers</small></article><article class="metric glass"><div class="metric-top">BLOCKED <i class="mdi mdi-cancel"></i></div><strong>{{summary.blocked.toLocaleString()}}</strong><small>policy decisions</small></article><article class="metric glass"><div class="metric-top">UNMAPPED <i class="mdi mdi-account-question-outline"></i></div><strong>{{summary.unmappedUsers.toLocaleString()}}</strong><small>events without a bound user</small></article></section>
    <section class="panel glass internet-panel"><div class="panel-title"><div><span class="eyebrow">BROWSER TELEMETRY</span><h2>Internet events</h2></div><span class="count-chip">{{total.toLocaleString()}} matching</span></div>
      <form class="internet-filters" @submit.prevent="apply"><label>Search hostname or path<input v-model.trim="filters.q" placeholder="portal.example.com or /accounts"></label><label>Domain<input v-model.trim="filters.domain" placeholder="example.com"></label><label>Path prefix<input v-model.trim="filters.path" placeholder="/admin"></label><label>Browser<select v-model="filters.browser"><option value="">All browsers</option><option value="chrome">Chrome</option><option value="edge">Edge</option><option value="firefox">Firefox</option></select></label><label>Action<select v-model="filters.action"><option value="">All actions</option><option value="observed">Observed</option><option value="allowed">Allowed</option><option value="blocked">Blocked</option></select></label><label>Device<select v-model="filters.deviceId"><option value="">All devices</option><option v-for="device in devices" :key="device.id" :value="device.id">{{device.nodeHostname||device.nodeGroupName||device.id}}</option></select></label><label>User<select v-model="filters.userId"><option value="">All users</option><option v-for="device in devices.filter(item=>item.userId)" :key="device.userId" :value="device.userId">{{device.userEmail||device.userId}}</option></select></label><label>From<input v-model="filters.from" type="datetime-local"></label><label>To<input v-model="filters.to" type="datetime-local"></label><div class="form-actions"><button class="button primary">Apply filters</button><button type="button" class="button secondary" :disabled="!hasFilters" @click="reset">Clear</button></div></form>
      <div class="table-wrap"><table><thead><tr><th :aria-sort="sortBy==='time'?(sortDir==='asc'?'ascending':'descending'):undefined"><button type="button" class="table-sort" @click="sort('time')">TIME <span>{{sortBy==='time'?(sortDir==='asc'?'↑':'↓'):''}}</span></button></th><th :aria-sort="sortBy==='domain'?(sortDir==='asc'?'ascending':'descending'):undefined"><button type="button" class="table-sort" @click="sort('domain')">DOMAIN <span>{{sortBy==='domain'?(sortDir==='asc'?'↑':'↓'):''}}</span></button></th><th :aria-sort="sortBy==='hostname'?(sortDir==='asc'?'ascending':'descending'):undefined"><button type="button" class="table-sort" @click="sort('hostname')">HOSTNAME <span>{{sortBy==='hostname'?(sortDir==='asc'?'↑':'↓'):''}}</span></button></th><th>PATH</th><th :aria-sort="sortBy==='browser'?(sortDir==='asc'?'ascending':'descending'):undefined"><button type="button" class="table-sort" @click="sort('browser')">BROWSER <span>{{sortBy==='browser'?(sortDir==='asc'?'↑':'↓'):''}}</span></button></th><th>DEVICE / NODE</th><th>USER</th><th :aria-sort="sortBy==='action'?(sortDir==='asc'?'ascending':'descending'):undefined"><button type="button" class="table-sort" @click="sort('action')">ACTION <span>{{sortBy==='action'?(sortDir==='asc'?'↑':'↓'):''}}</span></button></th></tr></thead><tbody><tr v-for="event in events" :key="event.id"><td>{{new Date(event.observed_at).toLocaleString()}}</td><td class="mono">{{event.registrable_domain}}</td><td class="mono">{{event.hostname}}</td><td class="mono">{{event.path_prefix||'—'}}</td><td>{{event.browser}}</td><td>{{nodeLabel(event)}}</td><td>{{event.user_email||'Unmapped'}}</td><td><span class="status" :class="event.action">{{event.action}}</span></td></tr><tr v-if="!events.length"><td colspan="8" class="empty-table">{{loading?'Loading…':'No Internet events match the selected filters.'}}</td></tr></tbody></table></div>
      <div class="internet-pagination"><span>Showing {{events.length?((page-1)*pageSize+1):0}}–{{Math.min(page*pageSize,total)}} of {{total}}</span><div><button class="button small secondary" :disabled="page<=1||loading" @click="move(page-1)">Previous</button><span>Page {{page}} of {{Math.max(totalPages,1)}}</span><button class="button small secondary" :disabled="page>=totalPages||loading" @click="move(page+1)">Next</button></div></div>
    </section>
    <section class="panel glass internet-devices"><div class="panel-title"><div><span class="eyebrow">ENROLLMENTS</span><h2>Browser devices</h2></div><div class="inline-actions"><span class="count-chip">{{devices.length}}</span><button v-if="canEnroll" class="button small primary" @click="openEnrollment">Create enrollment</button></div></div><div class="table-wrap"><table><thead><tr><th>DEVICE</th><th>NODE / GROUP</th><th>USER</th><th>BROWSER</th><th>VERSION</th><th>STATUS</th><th>LAST SEEN</th></tr></thead><tbody><tr v-for="device in devices" :key="device.id"><td class="mono">{{device.id}}</td><td>{{device.nodeHostname||device.nodeGroupName||'—'}}</td><td>{{device.userEmail||'Unmapped'}}</td><td>{{device.browser}}</td><td>{{device.extensionVersion}}</td><td><span class="status" :class="device.status==='active'?'reachable':'unreachable'">{{device.status}}</span></td><td>{{new Date(device.lastSeenAt).toLocaleString()}}</td></tr><tr v-if="!devices.length"><td colspan="7" class="empty-table">No browser devices enrolled.</td></tr></tbody></table></div></section>
    <GlassWindow v-model="enrollmentOpen" title="Create browser enrollment" width="620px"><form class="form-grid" @submit.prevent="createEnrollment"><p class="hint">Bind this one-time browser token to a managed node or group. Optionally select a WinFire or AD-backed operator so Internet events can be queried by user.</p><label>Target type<select v-model="enrollmentForm.target"><option value="node">Node</option><option value="group">Node group</option></select></label><label v-if="enrollmentForm.target==='node'">Node<select v-model="enrollmentForm.nodeId" required><option value="">Select node</option><option v-for="node in nodes" :key="node.id" :value="node.id">{{node.hostname}}</option></select></label><label v-else>Node group<select v-model="enrollmentForm.nodeGroupId" required><option value="">Select group</option><option v-for="group in groups" :key="group.id" :value="group.id">{{group.name}}</option></select></label><label v-if="session.user?.role==='admin'||session.user?.role==='owner'">Bind operator (optional)<select v-model="enrollmentForm.userId"><option value="">No user binding</option><option v-for="user in users" :key="user.id" :value="user.id">{{user.email}} · {{user.role}}</option></select></label><label>Collection level<select v-model="enrollmentForm.collectionLevel"><option value="host">Host only</option><option value="path">Host and path prefix</option></select></label><p v-if="enrollmentError" class="error-msg" role="alert">{{enrollmentError}}</p><div v-if="enrollmentResult" class="enrollment-result"><label>One-time token<textarea :value="enrollmentResult.token" readonly rows="2"></textarea></label><p>Assigned user: {{enrollmentResult.userEmail||'Unmapped'}} · expires {{new Date(enrollmentResult.expiresAt).toLocaleString()}}</p><button type="button" class="button secondary" @click="copyEnrollment">Copy token</button></div><div class="form-actions"><button type="button" class="button secondary" @click="enrollmentOpen=false">Close</button><button class="button primary" :disabled="enrollmentBusy||!!enrollmentResult">{{enrollmentBusy?'Creating…':'Create token'}}</button></div></form></GlassWindow>
    <section v-if="['owner','admin','editor'].includes(session.user?.role)" class="panel glass internet-policy-panel"><div class="panel-title"><div><span class="eyebrow">CONTROL</span><h2>Internet policy studio</h2></div><span class="count-chip">{{policies.length}} versions</span></div><p class="hint">Stage declarative browser rules, review the compiled scope, then publish. Existing extensions keep their last confirmed rules while disconnected.</p><div v-if="policyError" class="error-msg">{{policyError}}</div><div v-if="policyMessage" class="success-msg">{{policyMessage}}</div><div class="internet-policy-form"><input v-model.trim="rulePattern" placeholder="example.com or /admin" aria-label="Internet pattern"><select v-model="ruleMatch" aria-label="Pattern match"><option value="hostname">Hostname</option><option value="domain">Domain</option><option value="prefix">URL prefix</option></select><select v-model="ruleAction" aria-label="Rule action"><option value="block">Block</option><option value="allow">Allow</option></select><button class="button secondary" type="button" @click="addRule">Add rule</button></div><div v-if="policyDraft.length" class="table-wrap"><table><thead><tr><th>PATTERN</th><th>MATCH</th><th>ACTION</th><th></th></tr></thead><tbody><tr v-for="(rule,index) in policyDraft" :key="`${rule.pattern}-${index}`"><td class="mono">{{rule.pattern}}</td><td>{{rule.match}}</td><td><span class="status" :class="rule.action">{{rule.action}}</span></td><td><button class="button small danger" type="button" @click="policyDraft.splice(index,1)">Remove</button></td></tr></tbody></table></div><div class="internet-policy-footer"><label>Offline behavior<select v-model="policyFailMode"><option value="open">Fail open</option><option value="closed">Fail closed</option></select></label><label>Comment<input v-model.trim="policyComment" placeholder="Reason for this staged version"></label><button class="button primary" :disabled="policyBusy||!policyDraft.length" @click="stagePolicy">{{policyBusy?'Saving…':'Stage version'}}</button></div><div class="table-wrap" v-if="policies.length"><table><thead><tr><th>VERSION</th><th>STATUS</th><th>RULES</th><th>CREATED</th><th></th></tr></thead><tbody><tr v-for="policy in policies" :key="policy.id"><td>v{{policy.version_no}}</td><td>{{policy.status}}</td><td>{{policy.rules.length}}</td><td>{{new Date(policy.created_at).toLocaleString()}}</td><td class="inline-actions"><button v-if="session.user?.role==='admin'||session.user?.role==='owner'" class="button small primary" :disabled="policyBusy||policy.status==='published'" @click="publishPolicy(policy)">Publish</button><button v-if="session.user?.role==='admin'||session.user?.role==='owner'" class="button small secondary" :disabled="policyBusy||policy.status!=='published'" @click="rollbackPolicy(policy)">Rollback</button></td></tr></tbody></table></div></section>
  </div>
</template>

<style scoped>
.internet-filters{display:grid;grid-template-columns:repeat(4,minmax(140px,1fr));gap:10px;padding:16px;border-bottom:1px solid var(--border)}.internet-filters label{display:grid;gap:5px;font-size:.68rem;color:var(--muted)}.internet-filters .form-actions{align-self:end;display:flex;gap:7px;flex-wrap:wrap}.table-sort{border:0;background:transparent;color:inherit;font:inherit;padding:0;cursor:pointer}.table-sort span{color:var(--green)}.internet-pagination{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:13px 16px;font-size:.7rem;color:var(--muted)}.internet-pagination>div{display:flex;align-items:center;gap:8px}.internet-devices{margin-top:14px}.internet-policy-panel{margin-top:14px}.internet-policy-form,.internet-policy-footer{display:flex;gap:8px;align-items:end;flex-wrap:wrap;padding:14px 16px}.internet-policy-form input{flex:1;min-width:200px}.internet-policy-footer label{display:grid;gap:5px;font-size:.68rem;color:var(--muted)}.internet-policy-footer label:nth-child(2){flex:1;min-width:240px}.status.observed{color:#aab7c4}@media(max-width:950px){.internet-filters{grid-template-columns:repeat(2,minmax(140px,1fr))}}@media(max-width:600px){.internet-filters{grid-template-columns:1fr}.internet-pagination{align-items:flex-start;flex-direction:column}}
</style>
