<script setup>
import {computed,onMounted,ref} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api,session} from '../services/api.js'
const router=useRouter(),route=useRoute(),email=ref(''),password=ref(''),totp=ref(''),showTotp=ref(false),error=ref(''),working=ref(false),loginMode=ref('local')
const portalBrand=ref({companyName:'WinFire Secure',imageUrl:null})
const prompted=computed(()=>/^\/identity\?prompt=[0-9a-f-]{36}$/i.test(String(route.query.next||'')))
onMounted(async()=>{if(prompted.value)try{portalBrand.value=await api('/portal-branding')}catch{}})
async function submit(){error.value='';working.value=true;try{session.setTokens(await api(loginMode.value==='ad'?'/auth/ad/login':'/auth/login',{method:'POST',body:{email:email.value,password:password.value,totp:totp.value||undefined}}));const next=String(route.query.next||'');router.push(/^\/identity\?prompt=[0-9a-f-]{36}$/i.test(next)?next:'/')}catch(e){error.value=e.message;if(e.message.includes('TOTP'))showTotp.value=true}finally{working.value=false}}
</script>
<template><div class="login-screen"><div class="login-art"><span class="eyebrow">WINFIRE / SECURE</span><div class="login-symbol"><img src="/winfire-mark.png" alt=""></div><h1>Control every edge.<br><em>See every change.</em></h1><p>Windows Firewall policy, verification and identity protection in one control plane.</p><div class="login-grid"></div></div><form class="login-form glass" @submit.prevent="submit"><img v-if="prompted&&portalBrand.imageUrl" class="prompt-brand-image" :src="portalBrand.imageUrl" alt=""><span class="eyebrow">{{prompted?portalBrand.companyName+' ACCESS PORTAL':'OPERATOR ACCESS'}}</span><h2>{{prompted?'Confirm your identity':'Welcome back'}}</h2><p>{{prompted?'Sign in to request temporary access to the protected resource.':'Sign in to the control plane.'}}</p><div class="login-method" role="group" aria-label="Sign in method"><button type="button" :class="{active:loginMode==='local'}" @click="loginMode='local';error='';showTotp=false">WinFire account</button><button type="button" :class="{active:loginMode==='ad'}" @click="loginMode='ad';error='';showTotp=false">Active Directory</button></div><label>Email address<input v-model="email" type="email" autocomplete="username" required placeholder="you@company.com"></label><label>{{loginMode==='ad'?'AD password':'Password'}}<input v-model="password" type="password" autocomplete="current-password" required placeholder="••••••••••••"></label><label v-if="showTotp">Authenticator code<input v-model="totp" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" required placeholder="000000"></label><div v-if="error" class="error-msg">{{error}}</div><button class="primary" type="submit" :disabled="working">{{working?'Signing in…':'Sign in'}} <i class="mdi mdi-arrow-right"></i></button><RouterLink class="enroll-link" :to="{path:'/enroll-authenticator',query:prompted?{next:String(route.query.next)}:{}}">Enroll Authenticator</RouterLink><small>Authorized access only. All actions are audited.</small></form></div></template>
<style scoped>.prompt-brand-image{max-width:220px;max-height:90px;object-fit:contain;object-position:left center;margin-bottom:12px}.enroll-link{text-align:center;color:#6dc7ae;font-size:.78rem;font-weight:700;text-decoration:underline;text-underline-offset:3px}:root[data-layout=enterprise] .enroll-link{color:var(--enterprise-link,#3459a7)}.login-method{display:flex;gap:.35rem;padding:.25rem;border:1px solid var(--border);border-radius:8px}.login-method button{flex:1;min-width:0;background:transparent;color:inherit;border:0;border-radius:5px;padding:.5rem .35rem;font:inherit;font-size:.76rem;cursor:pointer}.login-method button.active{background:color-mix(in srgb,var(--cyan) 20%,var(--panel));font-weight:700}</style>
