import {createHash} from 'node:crypto'
import {z} from 'zod'
import {db,run,all,one,id,now,json,audit} from '../db.js'
import {matchesDynamicNode} from '../dynamicNodeGroups.js'
import {isLocalAssetNode,canonicalIp} from './networkBoundary.js'
import {emitNotification} from '../notifications.js'
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})},digest=v=>createHash('sha256').update(json(v)).digest('hex')
export const metadataFields=['application','environment','workload_role','business_owner','criticality']
const valuesSchema=z.object({application:z.string().trim().max(120).nullable().optional(),environment:z.string().trim().max(80).nullable().optional(),workload_role:z.string().trim().max(80).nullable().optional(),business_owner:z.string().trim().max(200).nullable().optional(),criticality:z.enum(['low','medium','high','critical']).nullable().optional()}).strict().refine(v=>Object.keys(v).length>0,'Provide at least one metadata field')
export const metadataProposalSchema=z.object({source:z.enum(['manual','azure-tag','ad-ou','node-group']),sourceRef:z.string().trim().min(1).max(1000),values:valuesSchema}).strict()
const precedence={'manual':100,'azure-tag':80,'ad-ou':60,'node-group':40}
const targetHash=node=>digest({sourceSettings:one("SELECT value FROM app_settings WHERE key='application_metadata_sources'")?.value,adDn:node.ad_dn,sources:all('SELECT id,state,evidence_json FROM asset_sources WHERE node_id=? ORDER BY id',node.id),node:metadataFields.map(f=>node[f]),groups:all('SELECT id,dynamic_rules_json,dynamic_match FROM node_groups WHERE dynamic_enabled=1 ORDER BY id'),memberships:all('SELECT group_id FROM node_group_members WHERE node_id=? ORDER BY group_id',node.id)})
function resolve(node,proposal){
 const candidates=[...all("SELECT * FROM application_metadata_proposals WHERE node_id=? AND status='approved' ORDER BY reviewed_at, rowid",node.id),proposal],latest=new Map(),values={},provenance={}
 for(const candidate of candidates){const key=candidate.source+':'+candidate.source_ref;latest.delete(key);latest.set(key,candidate);for(const field of Object.keys(JSON.parse(candidate.values_json)))values[field]=null}
 for(const candidate of [...latest.values()].sort((a,b)=>precedence[a.source]-precedence[b.source]))for(const [field,value] of Object.entries(JSON.parse(candidate.values_json))){if(value===null&&candidate.source!=='manual')continue;values[field]=value;provenance[field]={source:candidate.source,sourceRef:candidate.source_ref,proposalId:candidate.id}}
 return {values,provenance}
}
export function metadataPreview(key){const proposal=one('SELECT * FROM application_metadata_proposals WHERE id=?',key);if(!proposal)fail('Metadata proposal not found',404);const node=one('SELECT * FROM nodes WHERE id=?',proposal.node_id),resolved=resolve(node,proposal),next={...node,...resolved.values},groupChanges=[];for(const group of all('SELECT * FROM node_groups WHERE dynamic_enabled=1')){const config={enabled:true,match:group.dynamic_match,rules:JSON.parse(group.dynamic_rules_json||'[]')},before=!!one('SELECT node_id FROM node_group_members WHERE node_id=? AND group_id=?',node.id,group.id),after=matchesDynamicNode(next,config);if(before!==after)groupChanges.push({groupId:group.id,name:group.name,action:after?'add':'remove',policies:all('SELECT policy_id FROM policy_assignments WHERE node_group_id=?',group.id).map(p=>p.policy_id)})}return {...proposal,values:JSON.parse(proposal.values_json),effective:resolved.values,provenance:resolved.provenance,before:Object.fromEntries(metadataFields.map(f=>[f,node[f]])),groupChanges,stale:proposal.target_hash!==targetHash(node)}}
export function proposeMetadata(nodeId,input,actor){const node=one('SELECT * FROM nodes WHERE id=?',nodeId);if(!node||!isLocalAssetNode(node))fail('Local inventory asset not found',404);const q=metadataProposalSchema.parse(input),key=id();run('INSERT INTO application_metadata_proposals(id,node_id,source,source_ref,values_json,created_at,target_hash) VALUES(?,?,?,?,?,?,?)',key,nodeId,q.source,q.sourceRef,json(q.values),now(),targetHash(node));audit(actor,'application.metadata.propose','node',nodeId,null,q);return metadataPreview(key)}
export function reviewMetadata(key,input,actor){const q=z.object({approve:z.boolean(),reason:z.string().trim().min(1).max(1000)}).strict().parse(input),preview=metadataPreview(key);if(preview.status!=='pending'||preview.stale)fail('The proposal changed or was reviewed. Create a fresh proposal and review its target changes.',409);db.transaction(()=>{run('UPDATE application_metadata_proposals SET status=?,reviewed_at=?,reviewed_by=?,reason=? WHERE id=?',q.approve?'approved':'rejected',now(),actor,q.reason,key);if(q.approve)for(const [field,value] of Object.entries(preview.effective))run(`UPDATE nodes SET ${field}=? WHERE id=?`,value,preview.node_id);audit(actor,'application.metadata.review','node',preview.node_id,preview.before,{...q,effective:preview.effective,groupChanges:preview.groupChanges})})();return metadataPreview(key)}
export function nodeApplication(nodeId){const node=one('SELECT * FROM nodes WHERE id=?',nodeId);if(!node)fail('Node not found',404);return {values:Object.fromEntries(metadataFields.map(f=>[f,node[f]])),proposals:all('SELECT id FROM application_metadata_proposals WHERE node_id=? ORDER BY created_at DESC LIMIT 100',nodeId).map(p=>metadataPreview(p.id)),precedence}}
export function applicationDependencies(input={}){const q=z.object({application:z.string().max(120).optional(),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(250).default(25)}).parse(input),where=q.application?'WHERE s.application=? OR d.application=?':'WHERE s.application IS NOT NULL OR d.application IS NOT NULL',args=q.application?[q.application,q.application]:[],from=`FROM network_map_pairs m LEFT JOIN nodes s ON s.id=m.source_node_id LEFT JOIN nodes d ON d.id=m.destination_node_id ${where}`;return {items:all(`SELECT m.map_key,m.source_ip,m.destination_ip,m.protocol,m.destination_port,m.last_seen_at,m.connection_count,s.application source_application,d.application destination_application,s.id source_node_id,d.id destination_node_id ${from} ORDER BY m.last_seen_at DESC,m.map_key LIMIT ? OFFSET ?`,...args,q.pageSize,(q.page-1)*q.pageSize).map(r=>({...r,evidence:'observed',activitiesUrl:'/logs?srcIp='+encodeURIComponent(r.source_ip)+'&dstIp='+encodeURIComponent(r.destination_ip),suggestion:{action:'review',remoteAddress:r.destination_ip,remotePort:r.destination_port,protocol:r.protocol,automaticallyAllowed:false}})),total:one(`SELECT count(*) n ${from}`,...args).n,page:q.page,pageSize:q.pageSize}}
export const serviceTemplates=[{id:'directory',name:'Active Directory',version:1,role:'domain-controller',ports:[53,88,389,464,636,3268,3269],protocols:['TCP','UDP'],notes:'DNS, Kerberos and LDAP only. RPC and SMB require separate scoped review.'},{id:'dns',name:'DNS',version:1,role:'dns-server',ports:[53],protocols:['TCP','UDP']},{id:'kerberos',name:'Kerberos',version:1,role:'domain-controller',ports:[88,464],protocols:['TCP','UDP']},{id:'files',name:'SMB file services',version:1,role:'file-server',ports:[445],protocols:['TCP']},{id:'backup',name:'Backup service',version:1,role:'backup-server',ports:[],protocols:['TCP']},{id:'management',name:'Host management',version:1,role:'management-server',ports:[],protocols:['TCP']}].map(t=>({...t,platforms:['Windows'],direction:'out',requiresEndpointRoles:true}))
export function templateGraph(input){const q=z.object({templateId:z.string(),endpointNodeIds:z.array(z.string()).min(1).max(100),ports:z.array(z.number().int().min(1).max(65535)).max(32).optional()}).strict().parse(input),t=serviceTemplates.find(t=>t.id===q.templateId);if(!t)fail('Service template not found',404);const nodes=q.endpointNodeIds.map(key=>one('SELECT * FROM nodes WHERE id=?',key));if(nodes.some(n=>!n||!isLocalAssetNode(n)||!canonicalIp(n.ip)||n.workload_role!==t.role))fail(`Every endpoint must be a local asset with the reviewed role ${t.role}`);const ports=t.ports.length?t.ports:q.ports;if(!ports?.length)fail('Explicit service ports are required for this template');const prefix=id().slice(0,8),graph={nodes:t.protocols.map((protocol,i)=>({id:`${prefix}-${i}`,type:'allow',position:{x:80+i*280,y:80},data:{name:`${t.name} v${t.version}`,direction:'out',protocol,remotePort:ports.join(','),remoteAddress:[...new Set(nodes.map(n=>canonicalIp(n.ip)))].join(','),localPort:'Any',profile:'Any'}})),edges:[]};return {template:t,graph,endpointNodeIds:q.endpointNodeIds,requiresSimulation:true,requiresStagedDeployment:true}}

export const metadataSourcesSchema=z.object({enabled:z.boolean().default(false),dependencyAlerts:z.boolean().default(false),rules:z.array(z.discriminatedUnion('source',[
 z.object({id:z.string().min(1).max(80),source:z.literal('azure-tag'),tag:z.string().trim().min(1).max(128),field:z.enum(metadataFields)}).strict(),
 z.object({id:z.string().min(1).max(80),source:z.literal('ad-ou'),dn:z.string().trim().min(1).max(1000),values:valuesSchema}).strict(),
 z.object({id:z.string().min(1).max(80),source:z.literal('node-group'),groupId:z.string().min(1),values:valuesSchema}).strict()
])).max(100).default([])}).strict().refine(v=>new Set(v.rules.map(r=>r.id)).size===v.rules.length,'Mapping IDs must be unique')
export function metadataSources(){return JSON.parse(one("SELECT value FROM app_settings WHERE key='application_metadata_sources'")?.value||'{"enabled":false,"dependencyAlerts":false,"rules":[]}')}
export function saveMetadataSources(input,actor){const q=metadataSourcesSchema.parse(input);for(const r of q.rules)if(r.source==='node-group'&&!one('SELECT id FROM node_groups WHERE id=?',r.groupId))fail('Mapped node group does not exist');const before=metadataSources(),value={...q,updatedAt:now(),alertsSince:q.dependencyAlerts?(before.alertsSince||now()):null};run("INSERT INTO app_settings(key,value) VALUES('application_metadata_sources',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",json(value));audit(actor,'application.sources.save','settings','application_metadata_sources',before,value);return value}
export function refreshMetadataSources({limit=200}={}){
 const config=metadataSources();if(!config.enabled)return {created:0,scanned:0}
 const cursor=one("SELECT value FROM app_settings WHERE key='application_metadata_cursor'")?.value||'',size=Math.min(200,Math.max(1,limit)),nodes=all('SELECT * FROM nodes WHERE id>? ORDER BY id LIMIT ?',cursor,size);let created=0
 for(const node of nodes){
  if(!isLocalAssetNode(node))continue
  const activeRefs=new Set()
  function propose(source,sourceRef,values){
   const checked=valuesSchema.safeParse(values);if(!checked.success)return
   const last=one('SELECT * FROM application_metadata_proposals WHERE node_id=? AND source=? AND source_ref=? ORDER BY rowid DESC LIMIT 1',node.id,source,sourceRef)
   if(last&&last.values_json===json(checked.data)&&(last.status!=='pending'||last.target_hash===targetHash(node)))return
   db.transaction(()=>{run("UPDATE application_metadata_proposals SET status='superseded' WHERE node_id=? AND source_ref=? AND status='pending'",node.id,sourceRef);proposeMetadata(node.id,{source,sourceRef,values:checked.data},null)})();created++
  }
  for(const mapping of config.rules){
   const candidates=[]
   if(mapping.source==='azure-tag'){
    for(const source of all("SELECT id,evidence_json FROM asset_sources WHERE node_id=? AND state='linked' AND provider LIKE 'azure%'",node.id)){const tags=JSON.parse(source.evidence_json).tags||{},tag=Object.keys(tags).find(k=>k.toLowerCase()===mapping.tag.toLowerCase());if(tag&&typeof tags[tag]==='string')candidates.push({ref:source.id,values:{[mapping.field]:tags[tag]}})}
   }else if(mapping.source==='ad-ou'){
    const dn=String(node.ad_dn||'').toLowerCase(),ou=mapping.dn.toLowerCase();if(dn.endsWith(','+ou))candidates.push({ref:mapping.dn,values:mapping.values})
   }else if(one('SELECT node_id FROM node_group_members WHERE node_id=? AND group_id=?',node.id,mapping.groupId))candidates.push({ref:mapping.groupId,values:mapping.values})
   for(const candidate of candidates){const ref='mapping:'+mapping.id+':'+candidate.ref;activeRefs.add(ref);propose(mapping.source,ref,candidate.values)}
  }
  // A removed tag, OU membership or mapping is a reviewed withdrawal, never an immediate reassignment.
  const previous=new Map();for(const p of all("SELECT * FROM application_metadata_proposals WHERE node_id=? AND source_ref LIKE 'mapping:%' AND status='approved' ORDER BY rowid",node.id))previous.set(p.source_ref,p)
  for(const [ref,p] of previous)if(!activeRefs.has(ref)&&Object.values(JSON.parse(p.values_json)).some(v=>v!==null))propose(p.source,ref,Object.fromEntries(Object.keys(JSON.parse(p.values_json)).map(field=>[field,null])))
 }
 run("INSERT INTO app_settings(key,value) VALUES('application_metadata_cursor',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",nodes.length===size?nodes.at(-1).id:'');return {created,scanned:nodes.length}
}
export function notifyDependencyChanges(){
 const config=metadataSources();if(!config.dependencyAlerts||!config.alertsSince)return
 const cursor=Number(one("SELECT value FROM app_settings WHERE key='application_dependency_cursor'")?.value||0),rows=all('SELECT m.*,m.rowid sequence,s.application source_application,d.application destination_application FROM network_map_pairs m LEFT JOIN nodes s ON s.id=m.source_node_id LEFT JOIN nodes d ON d.id=m.destination_node_id WHERE m.rowid>? AND m.first_seen_at>=? AND (s.application IS NOT NULL OR d.application IS NOT NULL) ORDER BY m.rowid LIMIT 200',cursor,config.alertsSince)
 for(const r of rows)emitNotification({eventKey:'application-dependency:'+digest([r.map_key,r.source_application,r.destination_application]),category:'security_policy',title:'New application dependency observed',body:`${r.source_application||r.source_ip} → ${r.destination_application||r.destination_ip}: ${r.protocol}/${r.destination_port||'unspecified'}. Review flow evidence in Mapping before changing policy.`,entityType:'node',entityId:r.source_node_id||r.destination_node_id})
 if(rows.length)run("INSERT INTO app_settings(key,value) VALUES('application_dependency_cursor',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",String(rows.at(-1).sequence))
}
