import {z} from 'zod'
import {isIP} from 'node:net'
import {db,all,one,run,id,now,json,audit} from '../db.js'
import {remote,tcpProbe} from '../connector.js'
import {isLocalAssetNode,normalizeCidrs,subnetMatcher,assertDirectManagement} from './networkBoundary.js'
import {canReadResource} from '../access.js'
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})},parse=v=>JSON.parse(v||'null')
export const containmentSchema=z.object({nodeIds:z.array(z.string()).max(100).default([]),groupId:z.string().optional(),seconds:z.number().int().min(180).max(3600).default(600),protectedCidrs:z.array(z.string()).max(100).default([]),reason:z.string().trim().min(1).max(2000),incidentId:z.string().trim().max(200).default('')}).strict()
const targetContext=n=>({ip:n.ip,fqdn:n.fqdn,transport:n.transport,connectionMode:n.connection_mode,scopeId:n.scope_id})
const pilot=id=>String(process.env.WINFIRE_POLICY_SAFETY_PILOT_NODES||'').split(',').map(v=>v.trim()).includes(id)
export function blockedAddressRanges(protectedCidrs){
 const out=[];for(const family of [4,6]){const end=(1n<<BigInt(family===4?32:128))-1n,excluded=protectedCidrs.map(subnetMatcher).filter(m=>m.family===family).map(m=>[m.network<<m.shift,((m.network+1n)<<m.shift)-1n]).sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:0);let cursor=0n;const address=n=>family===4?[24n,16n,8n,0n].map(s=>Number(n>>s&255n)).join('.'):Array.from({length:8},(_,i)=>(n>>BigInt((7-i)*16)&65535n).toString(16)).join(':');for(const [start,last] of excluded){if(start>cursor)out.push(address(cursor)+'-'+address(start-1n));if(last>=cursor)cursor=last+1n}if(cursor<=end)out.push(address(cursor)+'-'+address(end))}return out
}
export function containmentPreview(input,user){
 const q=containmentSchema.parse(input);let nodeIds=[...q.nodeIds]
 if(q.groupId){const g=one('SELECT * FROM node_groups WHERE id=?',q.groupId);if(!g||!canReadResource(user,'node_group',g))fail('Node group not found',404);nodeIds.push(...all('SELECT node_id FROM node_group_members WHERE group_id=?',q.groupId).map(r=>r.node_id))}
 nodeIds=[...new Set(nodeIds)].sort();if(!nodeIds.length||nodeIds.length>100)fail('Select 1–100 assets')
 const controlCidrs=normalizeCidrs(String(process.env.WINFIRE_CONTAINMENT_CONTROL_CIDRS||'').split(',')),dependencies=all("SELECT id,ip,hostname,workload_role FROM nodes WHERE workload_role IN ('domain-controller','dns-server','management-server')").filter(n=>isIP(n.ip||'')&&isLocalAssetNode(n)),protectedCidrs=normalizeCidrs([...controlCidrs,...q.protectedCidrs,...dependencies.map(n=>n.ip+'/'+(isIP(n.ip)===4?32:128)),'127.0.0.0/8','169.254.0.0/16','224.0.0.0/4','255.255.255.255/32','::1/128','fe80::/10','ff00::/8'])
 const targets=nodeIds.map(key=>{const n=one('SELECT * FROM nodes WHERE id=?',key);if(!n||!isLocalAssetNode(n))fail('Local asset not found',404);assertDirectManagement(n);const supported=n.connection_mode!=='agent'&&(['winrm','winrms'].includes(n.transport)&&!/^(5\.|6\.[01]\.)/.test(n.os_version||'')||n.transport==='ssh');return {context:targetContext(n),nodeId:n.id,hostname:n.hostname,transport:n.transport,supported,pilotEnabled:pilot(n.id),reason:!supported?'Host isolation requires modern Windows WinRM or Linux SSH with nftables':!controlCidrs.length?'Configure verified controller CIDRs on the API server':!pilot(n.id)?'Controlled pilot authorization is required':null}})
 return {config:{...q,nodeIds,protectedCidrs},targets,controlCidrs,protectedDependencies:dependencies,blockedRanges:blockedAddressRanges(protectedCidrs),productionEnabled:false,restoration:'Host-native expiry, followed by removal and readback of only this incident’s rules',canStart:controlCidrs.length>0&&targets.every(t=>t.supported&&t.pilotEnabled)}
}
export function containment(key){const j=one('SELECT * FROM containment_jobs WHERE id=?',key);if(!j)fail('Containment not found',404);return {...j,config:parse(j.config_json),config_json:undefined,targets:all('SELECT * FROM containment_targets WHERE job_id=? ORDER BY node_id',key).map(t=>({...t,snapshot:parse(t.snapshot_json),snapshot_json:undefined}))}}
export function containments(input={}){const q=z.object({page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(25),status:z.enum(['queued','active','partial','restoring','restored']).optional()}).parse(input),where=q.status?'WHERE status=?':'',args=q.status?[q.status]:[];return {items:all(`SELECT id FROM containment_jobs ${where} ORDER BY created_at DESC,id LIMIT ? OFFSET ?`,...args,q.pageSize,(q.page-1)*q.pageSize).map(j=>containment(j.id)),total:one(`SELECT count(*) n FROM containment_jobs ${where}`,...args).n,page:q.page,pageSize:q.pageSize}}
export function queueContainment(input,user){const p=containmentPreview(input,user);if(!p.canStart)fail('Containment requires authorized pilot assets and verified controller CIDRs',409);return db.transaction(()=>{for(const n of p.targets){if(one("SELECT t.job_id FROM containment_targets t JOIN containment_jobs j ON j.id=t.job_id WHERE t.node_id=? AND j.status<>'restored'",n.nodeId)||one("SELECT t.job_id FROM policy_deployment_targets t JOIN policy_deployment_jobs j ON j.id=t.job_id WHERE t.node_id=? AND j.status IN ('queued','running','paused','partial','cancelling','restoring')",n.nodeId))fail('A selected asset has an unresolved containment or staged deployment',409)}const key=id(),stamp=now();run('INSERT INTO containment_jobs(id,status,config_json,requested_by,created_at,expires_at,updated_at) VALUES(?,?,?,?,?,?,?)',key,'queued',json({...p.config,blockedRanges:p.blockedRanges,targetContexts:Object.fromEntries(p.targets.map(n=>[n.nodeId,n.context]))}),user.id,stamp,new Date(Date.now()+p.config.seconds*1000).toISOString(),stamp);for(const n of p.targets)run('INSERT INTO containment_targets(job_id,node_id,transaction_id) VALUES(?,?,?)',key,n.nodeId,id());audit(user.id,'containment.queue','containment',key,null,p.config);return containment(key)}).immediate()}
export function restoreContainment(key,reason,user){if(typeof reason!=='string'||!reason.trim()||reason.length>2000)fail('A restoration reason is required');const j=containment(key);if(j.status!=='restored')run("UPDATE containment_jobs SET status='restoring',updated_at=? WHERE id=?",now(),key);audit(user.id,'containment.restore.request','containment',key,null,{reason});return containment(key)}
const driverDefault={async health(n){await remote(n,'auth');const port=n.transport==='ssh'?22:n.transport==='winrms'?5986:5985;const r=await tcpProbe(n.ip||n.fqdn,port,4000);if(r.status!=='open')throw Error('Independent control-path health check failed')},async start(n,args){if(n.transport==='ssh')return remote(n,'containment_start',args);const state=await remote(n,'safety_arm',{id:args.id,policyId:args.id,seconds:args.seconds,requireContainment:true});if(state.before.length)throw Error('Containment group was not empty');if(state.phase==='restored')return state;return remote(n,'safety_apply',{id:args.id,rules:['in','out'].map(direction=>({name:'Incident containment',direction,action:'block',protocol:'Any',profile:'Any',localPort:'Any',remotePort:'Any',program:'Any',remoteAddress:args.blockedRanges.join(',')}))})},async restore(n,args){return remote(n,n.transport==='ssh'?'containment_restore':'safety_restore',{...args,manual:true})}}
let running=false
export async function processContainment({driver=driverDefault,at=Date.now()}={}){if(running)return;running=true;try{
 const stamp=new Date(at).toISOString(),j=one("SELECT * FROM containment_jobs WHERE (status IN ('queued','restoring') OR status IN ('active','partial') AND expires_at<=?) AND (lease_until IS NULL OR lease_until<=?) ORDER BY created_at LIMIT 1",stamp,stamp);if(!j||j.lease_until&&j.lease_until>stamp)return;const claimed=run('UPDATE containment_jobs SET lease_until=? WHERE id=? AND (lease_until IS NULL OR lease_until<=?)',new Date(at+600000).toISOString(),j.id,stamp);if(!claimed.changes)return;const q=parse(j.config_json),targets=all('SELECT * FROM containment_targets WHERE job_id=?',j.id)
 const update=(t,status,snapshot=null,error=null)=>{run('UPDATE containment_targets SET status=?,snapshot_json=COALESCE(?,snapshot_json),error=? WHERE job_id=? AND node_id=?',status,snapshot?json(snapshot):null,error,j.id,t.node_id);t.status=status}
 const restoring=()=>Date.parse(j.expires_at)<=Math.max(at,Date.now())||one('SELECT status FROM containment_jobs WHERE id=?',j.id).status==='restoring'
 for(const t of targets){run('UPDATE containment_jobs SET lease_until=? WHERE id=?',new Date(Date.now()+600000).toISOString(),j.id);const n=one('SELECT * FROM nodes WHERE id=?',t.node_id);try{
  if(restoring()){if(['pending','failed','restored'].includes(t.status)){update(t,'restored');continue}const s=await driver.restore(n,{id:t.transaction_id});if(s.phase!=='restored')throw Error('Restoration readback not confirmed');update(t,'restored',s)}
  else if(t.status==='pending'){if(!n||json(targetContext(n))!==json(q.targetContexts[n.id]))throw Error('Asset address or management context changed; preview a new incident');if(!pilot(n.id))throw Error('Pilot authorization was removed');await driver.health(n);if(restoring())continue;if(Date.parse(j.expires_at)-Date.now()<120000)throw Error('Insufficient native recovery time remains; start a new reviewed incident');update(t,'unknown');const s=await driver.start(n,{id:t.transaction_id,seconds:Math.max(1,Math.floor((Date.parse(j.expires_at)-Date.now())/1000)),protectedCidrs:q.protectedCidrs,blockedRanges:q.blockedRanges});if(s.phase!=='applied'||!s.nativeRecovery)throw Error('Host-native expiry or containment readback not confirmed');await driver.health(n);update(t,'contained',s)}
  else if(t.status==='unknown')throw Error('Interrupted containment needs restoration readback')
 }catch(error){const message=error.message;if(!['pending','failed','restored'].includes(t.status)){try{const s=await driver.restore(n,{id:t.transaction_id});if(s.phase!=='restored')throw Error('Restoration not confirmed');update(t,'restored',s,message)}catch(restoreError){update(t,'restore-failed',null,message+'; '+restoreError.message)}}else update(t,'failed',null,message)}}
 const rows=all('SELECT status FROM containment_targets WHERE job_id=?',j.id),restore=restoring(),status=rows.every(t=>t.status==='restored')?'restored':restore?'restoring':rows.every(t=>t.status==='contained')?'active':'partial';run('UPDATE containment_jobs SET status=?,lease_until=?,updated_at=? WHERE id=?',status,status==='restoring'?new Date(Date.now()+60000).toISOString():null,now(),j.id);audit(j.requested_by,'containment.'+status,'containment',j.id,null,{targets:rows})
 }finally{running=false}}
