import {z} from 'zod'
import {all,one,run,id,now,json,audit} from '../db.js'
import {canReadResource,canWriteResource} from '../access.js'
import {emitNotification} from '../notifications.js'
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})}
function policy(key,user,write=false){const p=one('SELECT * FROM policies WHERE id=?',key);if(!p)fail('Policy not found',404);if(!(write?canWriteResource:canReadResource)(user,'policy',p))fail('Insufficient policy permission',403);return p}
export const exceptionSchema=z.object({versionId:z.string().min(1),ruleId:z.string().min(1).max(200),owner:z.string().trim().min(1).max(200),justification:z.string().trim().min(1).max(4000),requestRef:z.string().max(500).default(''),reviewAt:z.string().datetime({offset:true}),expiresAt:z.string().datetime({offset:true}).nullable().default(null)}).strict()
export function createException(policyId,input,user){const p=policy(policyId,user,true),q=exceptionSchema.parse(input);if(q.versionId!==p.current_version_id)fail('Policy changed; reload before recording an exception',409);const v=one('SELECT * FROM policy_versions WHERE id=?',q.versionId),graph=JSON.parse(v.graph_json),rule=graph.nodes.find(n=>n.id===q.ruleId);if(!rule||!['allow','deny','program'].includes(rule.type))fail('Choose a compiled rule owned by this policy');if(rule.data?.localUserSid||graph.nodes.some(n=>n.type==='mfaGate'))fail('JIT/identity dependencies require their own lifecycle; they cannot be ordinary exceptions',409);if(Date.parse(q.reviewAt)<=Date.now()||q.expiresAt&&Date.parse(q.expiresAt)<=Date.now())fail('Review and expiry must be in the future');if(one("SELECT id FROM rule_exceptions WHERE policy_id=? AND rule_id=? AND status<>'retired'",policyId,q.ruleId))fail('This rule already has an active exception record',409);const key=id();run('INSERT INTO rule_exceptions(id,policy_id,version_id,rule_id,owner,justification,request_ref,review_at,expires_at,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',key,policyId,q.versionId,q.ruleId,q.owner,q.justification,q.requestRef,q.reviewAt,q.expiresAt,user.id,now(),now());audit(user.id,'rule.exception.create','rule-exception',key,null,q);return exception(key,user)}
export function exception(key,user){const e=one('SELECT * FROM rule_exceptions WHERE id=?',key);if(!e)fail('Exception not found',404);const p=policy(e.policy_id,user);return {...e,policyName:p.name,stale:p.current_version_id!==e.version_id,reviewDue:Date.parse(e.review_at)<=Date.now(),expired:!!e.expires_at&&Date.parse(e.expires_at)<=Date.now()}}
export function exceptions(user,input={}){const q=z.object({policyId:z.string().optional(),state:z.enum(['all','due','expired','retirement-requested']).default('all'),q:z.string().max(200).default(''),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(250).default(25)}).parse(input);const rows=all('SELECT e.* FROM rule_exceptions e ORDER BY review_at,id').filter(e=>(!q.policyId||e.policy_id===q.policyId)&&canReadResource(user,'policy',one('SELECT * FROM policies WHERE id=?',e.policy_id))).map(e=>exception(e.id,user)).filter(e=>!q.q||[e.owner,e.justification,e.policyName].join(' ').toLowerCase().includes(q.q.toLowerCase())).filter(e=>q.state==='all'||q.state==='due'&&e.reviewDue||q.state==='expired'&&e.expired||q.state==='retirement-requested'&&e.status==='retirement-requested');return {items:rows.slice((q.page-1)*q.pageSize,q.page*q.pageSize),total:rows.length,page:q.page,pageSize:q.pageSize}}
export function reviewException(key,input,user){const e=exception(key,user);policy(e.policy_id,user,true);if(['retiring','retired'].includes(e.status))fail('Finish or restore the withdrawal deployment before changing this exception',409);const q=z.object({action:z.enum(['recertify','retire']),reason:z.string().trim().min(1).max(2000),reviewAt:z.string().datetime({offset:true}).optional(),expiresAt:z.string().datetime({offset:true}).nullable().optional()}).strict().parse(input);if(e.stale)fail('Policy version changed; review the current rule before recertification or retirement',409);if(q.action==='recertify'){if(!q.reviewAt||Date.parse(q.reviewAt)<=Date.now())fail('Choose a future review date');if(q.expiresAt&&Date.parse(q.expiresAt)<=Date.now())fail('Choose a future expiry date');run("UPDATE rule_exceptions SET status='active',review_at=?,expires_at=?,updated_at=? WHERE id=?",q.reviewAt,q.expiresAt===undefined?e.expires_at:q.expiresAt,now(),key)}else run("UPDATE rule_exceptions SET status='retirement-requested',updated_at=? WHERE id=?",now(),key);audit(user.id,'rule.exception.'+q.action,'rule-exception',key,e,q);return exception(key,user)}
export function retirementPreview(key,user){const e=exception(key,user);policy(e.policy_id,user,true);if(e.status!=='retirement-requested'||e.stale)fail('Request retirement of the current policy version first',409);const graph=JSON.parse(one('SELECT graph_json FROM policy_versions WHERE id=?',e.version_id).graph_json);return {exceptionId:key,policyId:e.policy_id,baseVersionId:e.version_id,graph:{nodes:graph.nodes.filter(n=>n.id!==e.rule_id),edges:graph.edges.filter(edge=>edge.source!==e.rule_id&&edge.target!==e.rule_id)},state:'awaiting-simulation-and-staged-deployment',requiresVerifiedWithdrawal:true,foreignRulesAffected:false}}
export function ruleHygiene(policyId,user){const p=policy(policyId,user),version=one('SELECT * FROM policy_versions WHERE id=?',p.current_version_id);if(!version)return {items:[]};const rules=JSON.parse(version.rules_compiled_json),items=[],groups=new Map();for(const r of rules){const key=json(['action','direction','protocol','localPort','remotePort','remoteAddress','program','profile','localUserSid','schedule'].map(f=>r[f]??null));const previous=groups.get(key);if(previous)items.push({ruleId:r.sourceNodeId,kind:'equivalent-match',otherRuleId:previous.sourceNodeId,reason:'Identical compiled match conditions; review both owners before retirement'});else groups.set(key,r);if(r.action==='allow'&&r.remoteAddress==='Any'&&(r.localPort==='Any'&&r.remotePort==='Any'||r.protocol==='Any'))items.push({ruleId:r.sourceNodeId,kind:'broad-allow',reason:'Unrestricted peer scope with broad service access'});if(r.localUserSid)items.push({ruleId:r.sourceNodeId,kind:'protected-identity',reason:'Identity rule; excluded from automatic retirement'})}for(let i=0;i<Math.min(rules.length,1000);i++)for(let j=0;j<i;j++){
 const a=rules[i],b=rules[j];if(a.localUserSid||b.localUserSid||a.schedule||b.schedule||a.direction!==b.direction)continue
 const fields=['protocol','localPort','remotePort','remoteAddress','program','profile'],covers=(x,y)=>fields.every(f=>!x[f]||x[f]==='Any'||x[f]===y[f]);if(!covers(a,b)&&!covers(b,a))continue
 if(a.action===b.action&&fields.some(f=>a[f]!==b[f]))items.push({ruleId:a.sourceNodeId,otherRuleId:b.sourceNodeId,kind:'contained-match',reason:'One ordinary compiled match contains the other; review ownership and effective Windows policy before retirement'})
 else if(a.action!==b.action)items.push({ruleId:a.sourceNodeId,otherRuleId:b.sourceNodeId,kind:'block-allow-overlap',reason:'Overlapping ordinary Windows block and allow rules: the block takes precedence; authenticated bypass is outside this comparison'})
 }return {policyId,versionId:version.id,items,unusedConclusion:'not-established',coverageRequired:true,automaticallyRemoved:false}}
export function notifyExceptionReviews(){for(const e of all("SELECT * FROM rule_exceptions WHERE status='active' AND (review_at<=? OR expires_at<=?) ORDER BY review_at LIMIT 100",now(),now()))emitNotification({eventKey:`exception-review:${e.id}:${e.review_at}:${e.expires_at||''}`,category:'security_policy',title:'Firewall exception needs review',body:`Exception owned by ${e.owner} is due for review or expired. Withdrawal requires a reviewed policy change and verified deployment.`,entityType:'policy',entityId:e.policy_id})}
