exports.up=async knex=>{
  await knex.schema.createTable('internet_enrollment_tokens',table=>{
    table.text('id').primary()
    table.text('token_hash').notNullable().unique()
    table.text('node_id').references('id').inTable('nodes').onDelete('SET NULL')
    table.text('node_group_id').references('id').inTable('node_groups').onDelete('SET NULL')
    table.text('collection_level').notNullable().defaultTo('host')
    table.text('created_by').references('id').inTable('users').onDelete('SET NULL')
    table.text('created_at').notNullable()
    table.text('expires_at').notNullable()
    table.text('used_at')
  })
  await knex.schema.createTable('internet_extension_devices',table=>{
    table.text('id').primary()
    table.text('node_id').references('id').inTable('nodes').onDelete('SET NULL')
    table.text('node_group_id').references('id').inTable('node_groups').onDelete('SET NULL')
    table.text('user_id').references('id').inTable('users').onDelete('SET NULL')
    table.text('browser').notNullable()
    table.text('extension_version').notNullable()
    table.text('install_id_hash').notNullable()
    table.text('token_hash').notNullable().unique()
    table.text('collection_level').notNullable().defaultTo('host')
    table.text('status').notNullable().defaultTo('active')
    table.text('capabilities_json').notNullable().defaultTo('{}')
    table.text('last_seen_at').notNullable()
    table.text('enrolled_at').notNullable()
    table.text('revoked_at')
  })
  await knex.schema.createTable('internet_url_patterns',table=>{
    table.text('id').primary()
    table.text('fingerprint').notNullable().unique()
    table.text('scheme').notNullable()
    table.text('hostname').notNullable()
    table.text('registrable_domain').notNullable()
    table.text('path_prefix')
    table.integer('reference_count').notNullable().defaultTo(0)
    table.text('created_at').notNullable()
  })
  await knex.schema.createTable('internet_events',table=>{
    table.text('id').primary()
    table.text('device_id').notNullable().references('id').inTable('internet_extension_devices').onDelete('CASCADE')
    table.text('client_event_id').notNullable()
    table.text('observed_at').notNullable()
    table.text('received_at').notNullable()
    table.text('browser').notNullable()
    table.text('hostname').notNullable()
    table.text('registrable_domain').notNullable()
    table.text('path_prefix')
    table.text('pattern_id').references('id').inTable('internet_url_patterns').onDelete('SET NULL')
    table.text('action').notNullable().defaultTo('observed')
    table.text('tab_session_hash')
    table.text('redaction_level').notNullable().defaultTo('query-stripped')
    table.text('created_at').notNullable()
    table.unique(['device_id','client_event_id'])
  })
  await knex.schema.createTable('internet_policy_versions',table=>{
    table.text('id').primary()
    table.integer('version_no').notNullable()
    table.text('status').notNullable().defaultTo('staged')
    table.text('rules_json').notNullable().defaultTo('[]')
    table.text('fail_mode').notNullable().defaultTo('open')
    table.text('comment')
    table.text('created_by').references('id').inTable('users').onDelete('SET NULL')
    table.text('created_at').notNullable()
    table.text('published_at')
    table.text('rolled_back_at')
    table.unique(['version_no'])
  })
  await knex.raw('CREATE INDEX idx_internet_enrollment_expires ON internet_enrollment_tokens(expires_at,used_at)')
  await knex.raw('CREATE INDEX idx_internet_devices_status ON internet_extension_devices(status,last_seen_at)')
  await knex.raw('CREATE INDEX idx_internet_events_time ON internet_events(observed_at,id)')
  await knex.raw('CREATE INDEX idx_internet_events_domain ON internet_events(registrable_domain,hostname)')
  await knex.raw('CREATE INDEX idx_internet_events_device ON internet_events(device_id,observed_at)')
  await knex.raw('CREATE INDEX idx_internet_events_pattern ON internet_events(pattern_id)')
  await knex.raw('CREATE INDEX idx_internet_policy_status ON internet_policy_versions(status,version_no)')
}

exports.down=async knex=>{
  await knex.raw('DROP INDEX IF EXISTS idx_internet_events_pattern')
  await knex.raw('DROP INDEX IF EXISTS idx_internet_policy_status')
  await knex.raw('DROP INDEX IF EXISTS idx_internet_events_device')
  await knex.raw('DROP INDEX IF EXISTS idx_internet_events_domain')
  await knex.raw('DROP INDEX IF EXISTS idx_internet_events_time')
  await knex.raw('DROP INDEX IF EXISTS idx_internet_devices_status')
  await knex.raw('DROP INDEX IF EXISTS idx_internet_enrollment_expires')
  await knex.schema.dropTableIfExists('internet_events')
  await knex.schema.dropTableIfExists('internet_url_patterns')
  await knex.schema.dropTableIfExists('internet_extension_devices')
  await knex.schema.dropTableIfExists('internet_enrollment_tokens')
  await knex.schema.dropTableIfExists('internet_policy_versions')
}
