exports.up=async k=>{
 await k.schema.createTable('ai_reporters',t=>{
  t.text('id').primary();t.text('name').notNullable();t.text('credential_hash').unique();t.text('issuer');t.text('subject');t.text('client_id');t.text('actor_id').references('id').inTable('users').onDelete('SET NULL');t.text('coverage').notNullable().defaultTo('self-reported');t.text('status').notNullable().defaultTo('active');t.text('created_at').notNullable();t.text('updated_at').notNullable();t.text('last_report_at');t.text('last_heartbeat_at');t.text('health_json').notNullable().defaultTo('{}');t.integer('accepted').notNullable().defaultTo(0);t.integer('rejected').notNullable().defaultTo(0);t.integer('duplicates').notNullable().defaultTo(0);t.unique(['issuer','subject','client_id'])
 })
 await k.schema.createTable('ai_reporter_nodes',t=>{t.text('reporter_id').notNullable().references('id').inTable('ai_reporters').onDelete('CASCADE');t.text('node_id').notNullable().references('id').inTable('nodes').onDelete('CASCADE');t.primary(['reporter_id','node_id'])})
 await k.schema.createTable('ai_usage_events',t=>{
  t.text('id').primary();t.text('reporter_id').notNullable().references('id').inTable('ai_reporters');t.text('operation_id').notNullable();t.text('node_id').references('id').inTable('nodes').onDelete('SET NULL');t.text('actor_id').references('id').inTable('users').onDelete('SET NULL');t.text('operation').notNullable();t.text('original_operation');t.text('tool');t.text('provider');t.text('model');t.text('response_model');t.text('hostname');t.text('session_id');t.text('trace_id');t.text('span_id');t.text('parent_span_id');t.text('request_id');t.text('process_guid');t.text('process_started_at');t.integer('process_id');t.text('outcome').notNullable();t.text('error_code');t.text('coverage').notNullable();t.text('started_at');t.text('ended_at');t.text('observed_at').notNullable();t.text('received_at').notNullable();t.float('duration_ms');t.integer('input_tokens');t.integer('output_tokens');t.text('cost_amount');t.text('currency');t.text('cost_source');t.text('adapter_version');t.text('started_receipt');t.text('ended_receipt');t.unique(['reporter_id','operation_id']);t.index(['observed_at','id']);t.index(['node_id','observed_at']);t.index(['provider','observed_at']);t.index(['operation','observed_at']);t.index(['reporter_id','observed_at']);t.index(['trace_id','request_id'])
 })
 await k.schema.createTable('ai_receipts',t=>{t.text('id').primary();t.text('reporter_id').notNullable().references('id').inTable('ai_reporters');t.text('event_id').notNullable();t.text('payload_hash').notNullable();t.text('usage_id').references('id').inTable('ai_usage_events').onDelete('SET NULL');t.text('received_at').notNullable();t.unique(['reporter_id','event_id']);t.index('received_at')})
 await k.schema.createTable('ai_service_rules',t=>{t.text('id').primary();t.text('hostname').notNullable();t.text('match').notNullable();t.text('provider').notNullable();t.text('service').notNullable();t.text('role').notNullable();t.text('source_url').notNullable();t.text('reviewed_at').notNullable();t.integer('version').notNullable().defaultTo(1);t.boolean('enabled').notNullable().defaultTo(true);t.boolean('builtin').notNullable().defaultTo(false);t.text('updated_at').notNullable();t.unique(['hostname','match'])})
 await k.schema.createTable('ai_rule_history',t=>{t.increments('id');t.text('rule_id').notNullable();t.integer('version').notNullable();t.text('snapshot_json').notNullable();t.text('at').notNullable();t.unique(['rule_id','version'])})
 await k.schema.createTable('ai_dns_observations',t=>{t.text('id').primary();t.text('reporter_id').notNullable().references('id').inTable('ai_reporters');t.text('event_id').notNullable();t.text('payload_hash').notNullable();t.text('node_id').notNullable().references('id').inTable('nodes').onDelete('CASCADE');t.text('hostname').notNullable();t.text('answers_json').notNullable();t.text('process_guid');t.integer('process_id');t.text('process_started_at');t.text('observed_at').notNullable();t.text('expires_at').notNullable();t.boolean('expiry_known').notNullable();t.text('channel').notNullable();t.text('provider').notNullable();t.unique(['reporter_id','event_id']);t.index(['node_id','observed_at','expires_at'])})
 await k.schema.createTable('ai_network_observations',t=>{t.text('id').primary();t.text('source').notNullable();t.text('source_id').notNullable();t.text('node_id').references('id').inTable('nodes').onDelete('SET NULL');t.text('collector_node_id').references('id').inTable('nodes').onDelete('SET NULL');t.text('observed_at').notNullable();t.text('received_at').notNullable();t.text('hostname');t.text('peer_ip');t.text('program');t.integer('process_id');t.text('process_guid');t.text('process_started_at');t.text('trace_id');t.text('request_id');t.text('action').notNullable();t.text('provider');t.text('service');t.text('role');t.text('category').notNullable();t.text('confidence').notNullable();t.text('rule_id');t.integer('rule_version');t.text('evidence_json').notNullable();t.boolean('source_expired').notNullable().defaultTo(false);t.unique(['source','source_id']);t.index(['observed_at','id']);t.index(['node_id','observed_at']);t.index(['provider','observed_at'])})
 await k.schema.createTable('ai_usage_evidence',t=>{t.text('usage_id').notNullable().references('id').inTable('ai_usage_events').onDelete('CASCADE');t.text('observation_id').notNullable().references('id').inTable('ai_network_observations').onDelete('CASCADE');t.text('reason').notNullable();t.text('association').notNullable();t.primary(['usage_id','observation_id'])})
 await k.schema.createTable('ai_work_queue',t=>{t.text('kind').notNullable();t.text('source_id').notNullable();t.text('queued_at').notNullable();t.primary(['kind','source_id']);t.index('queued_at')})
 await k.schema.createTable('ai_settings',t=>{t.integer('id').primary();t.text('json').notNullable()})
 await k('ai_settings').insert({id:1,json:JSON.stringify({enabled:true,retentionDays:90,correlationWindowSeconds:120,dnsWindowSeconds:120,staleReporterMinutes:15})})
 await k.schema.createTable('ai_worker_state',t=>{t.integer('id').primary();t.integer('firewall_cursor').notNullable().defaultTo(0);t.integer('browser_cursor').notNullable().defaultTo(0);t.integer('enrichment_cursor').notNullable().defaultTo(0);t.integer('rule_revision').notNullable().defaultTo(0);t.integer('dropped').notNullable().defaultTo(0);t.integer('schema_errors').notNullable().defaultTo(0);t.text('last_success_at');t.text('last_error')})
 await k('ai_worker_state').insert({id:1})
 // Queues are bounded at intake; log triggers keep the latest source revision durable.
 for(const [table,kind] of [['log_events','firewall'],['internet_events','browser']]){
  for(const op of ['INSERT','UPDATE'])await k.raw(`CREATE TRIGGER ai_${kind}_${op.toLowerCase()} AFTER ${op} ON ${table} BEGIN INSERT OR IGNORE INTO ai_work_queue(kind,source_id,queued_at) SELECT '${kind}',NEW.id,strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE (SELECT count(*) FROM ai_work_queue)<100000; UPDATE ai_worker_state SET dropped=dropped+1 WHERE id=1 AND (SELECT count(*) FROM ai_work_queue)>=100000; END`)
 }
}
exports.down=async k=>{
 for(const kind of ['firewall','browser'])for(const op of ['insert','update'])await k.raw(`DROP TRIGGER IF EXISTS ai_${kind}_${op}`)
 for(const table of ['ai_work_queue','ai_usage_evidence','ai_network_observations','ai_dns_observations','ai_rule_history','ai_service_rules','ai_receipts','ai_usage_events','ai_reporter_nodes','ai_reporters','ai_settings','ai_worker_state'])await k.schema.dropTableIfExists(table)
}
