import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import crypto from 'node:crypto'
import os from 'node:os'
import path from 'node:path'
import {createServer} from 'node:net'
import supertest from 'supertest'
import {compilePolicy,rulesConflict,validateAddressExpression,validatePortExpression,validateProgramPath} from '@winfire/shared'
import {normalizeWindowsEvent} from '../src/eventNormalizer.js'

const dir=fs.mkdtempSync(path.join(os.tmpdir(),'winfire-test-'))
process.env.DATA_DIR=dir
process.env.BOOTSTRAP_EMAIL='owner@example.test'
process.env.BOOTSTRAP_PASSWORD='test-password-12345'
process.env.AUTH_RATE_LIMIT='100'
const {app}=await import('../src/app.js')
const {classifyVerification}=await import('../src/verifier.js')
const {bootstrap}=await import('../src/security.js')
const {db}=await import('../src/db.js')
const {recordNodeSuccess,recordNodeTransportFailure}=await import('../src/connector.js')
const request=supertest(app)
await bootstrap()
test.after(()=>{db.close();fs.rmSync(dir,{recursive:true,force:true})})

test('policy compiler validates the graph and emits tagged rules',()=>{
  const graph={nodes:[{id:'a',type:'portGroup',data:{ports:'3389'}},{id:'b',type:'allow',data:{name:'RDP'}}],edges:[{id:'e',source:'a',target:'b'}]}
  const rules=compilePolicy(graph,'policy-1')
  assert.equal(rules.length,1)
  assert.equal(rules[0].localPort,'3389')
  assert.equal(rules[0].group,'WinFireSecure:policy-1')
  const scoped=compilePolicy({nodes:[{id:'addr',type:'addressGroup',data:{addresses:'192.0.2.0/24'}},{id:'profile',type:'profile',data:{profile:'Domain'}},{id:'scoped-rule',type:'allow',data:{name:'Scoped RDP',remoteAddress:'Any',profile:'Any'}}],edges:[{id:'addr-edge',source:'addr',target:'scoped-rule'},{id:'profile-edge',source:'profile',target:'scoped-rule'}]},'policy-scoped')
  assert.equal(scoped[0].remoteAddress,'192.0.2.0/24')
  assert.equal(scoped[0].profile,'Domain')
  assert.throws(()=>compilePolicy({nodes:graph.nodes,edges:[{id:'e1',source:'a',target:'b'},{id:'e2',source:'b',target:'a'}]},'policy-1'),/cycle/)
  assert.throws(()=>compilePolicy({nodes:[{id:'gate',type:'mfaGate',data:{localPort:'3389'}}],edges:[]},'policy-1'),/MFA Gate/)
  assert.throws(()=>compilePolicy({nodes:[{id:'timed',type:'schedule',data:{}}],edges:[]},'policy-1'),/Schedule nodes/)
  assert.throws(()=>compilePolicy({nodes:[{id:'unknown',type:'custom',data:{}}],edges:[]},'policy-1'),/Unsupported policy node type/)
  assert.throws(()=>compilePolicy({nodes:[graph.nodes[0],graph.nodes[0]],edges:[]},'policy-1'),/duplicate node IDs/)
  const outbound=compilePolicy({nodes:[{id:'ports',type:'portGroup',data:{ports:'443'}},{id:'outbound',type:'allow',data:{name:'HTTPS egress',direction:'out'}}],edges:[{id:'group',source:'ports',target:'outbound'}]},'policy-egress')
  assert.equal(outbound[0].localPort,'Any')
  assert.equal(outbound[0].remotePort,'443')
  assert.equal(rulesConflict({...outbound[0],action:'allow',remotePort:'443'},{...outbound[0],action:'block',remotePort:'3389'}),false)
  assert.equal(rulesConflict({...outbound[0],action:'allow',remotePort:'443'},{...outbound[0],action:'block',remotePort:'443'}),true)
})

test('policy fields reject invalid ports, addresses and program paths before apply',()=>{
  assert.equal(validatePortExpression('80,443,1000-2000'),true)
  assert.equal(validatePortExpression('2000-1000'),false)
  assert.equal(validateAddressExpression('192.0.2.0/24,2001:db8::/32'),true)
  assert.equal(validateAddressExpression('192.0.2.0/33'),false)
  assert.equal(validateAddressExpression('999.0.0.1'),false)
  assert.equal(validateProgramPath('C:\\Program Files\\Example\\app.exe'),true)
  assert.equal(validateProgramPath('app.exe'),false)
  assert.throws(()=>compilePolicy({nodes:[{id:'bad-address',type:'allow',data:{remoteAddress:'192.0.2.0/33'}}],edges:[]},'policy-invalid'),/Invalid remote address expression/)
  assert.throws(()=>compilePolicy({nodes:[{id:'bad-group',type:'addressGroup',data:{addresses:'999.0.0.1'}}],edges:[]},'policy-invalid'),/Invalid address group/)
  assert.throws(()=>compilePolicy({nodes:[{id:'bad-program',type:'program',data:{name:'Bad path',program:'app.exe'}}],edges:[]},'policy-invalid'),/absolute Windows program path/)
})

test('deny checks require managed-rule evidence',()=>{
  assert.equal(classifyVerification({action:'block'},'timeout',null).status,'inconclusive')
  assert.equal(classifyVerification({action:'block'},'refused',false).status,'inconclusive')
  assert.equal(classifyVerification({action:'block'},'timeout',true).status,'pass')
  assert.equal(classifyVerification({action:'block'},'open',true).status,'fail')
})

test('Windows Security events retain firewall and logon meaning',()=>{
  const logon=normalizeWindowsEvent({RecordId:42,Id:4625,TimeCreated:'2026-09-19T12:00:00Z',Fields:{IpAddress:'10.2.3.4',IpPort:'49152',TargetUserSid:'S-1-5-21-123',LogonType:'10'}})
  assert.equal(logon.eventType,'logon')
  assert.equal(logon.action,'failure')
  assert.equal(logon.srcPort,49152)
  assert.equal(logon.accountSid,'S-1-5-21-123')
  const firewall=normalizeWindowsEvent({RecordId:43,Id:5157,Fields:{Protocol:'6',Direction:'%%14592',SourceAddress:'10.2.3.4',DestPort:'3389'}})
  assert.equal(firewall.eventType,'firewall')
  assert.equal(firewall.action,'block')
  assert.equal(firewall.protocol,'TCP')
  assert.equal(firewall.dstPort,3389)
  assert.equal(firewall.direction,'in')
})

test('repeated transport failures back off and a successful call restores node health',()=>{
  const nodeId=crypto.randomUUID()
  db.prepare('INSERT INTO nodes(id,hostname) VALUES(?,?)').run(nodeId,'health-test')
  for(let attempt=1;attempt<=3;attempt++){
    recordNodeTransportFailure(nodeId)
    const node=db.prepare('SELECT failures,status,next_retry_at FROM nodes WHERE id=?').get(nodeId)
    assert.equal(node.failures,attempt)
    assert.equal(node.status,attempt<3?'degraded':'unreachable')
    assert.ok(new Date(node.next_retry_at)>new Date())
  }
  recordNodeSuccess(nodeId)
  const restored=db.prepare('SELECT failures,status,next_retry_at,last_seen_at FROM nodes WHERE id=?').get(nodeId)
  assert.equal(restored.failures,0)
  assert.equal(restored.status,'reachable')
  assert.equal(restored.next_retry_at,null)
  assert.ok(restored.last_seen_at)
})

test('refresh tokens rotate once and reject replay',async()=>{
  const login=await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'test-password-12345'}).expect(200)
  const rotated=await request.post('/api/v1/auth/refresh').send({refreshToken:login.body.refreshToken}).expect(200)
  assert.notEqual(rotated.body.refreshToken,login.body.refreshToken)
  await request.post('/api/v1/auth/refresh').send({refreshToken:login.body.refreshToken}).expect(401)
  await request.post('/api/v1/auth/refresh').send({refreshToken:rotated.body.refreshToken}).expect(200)
})

test('admins cannot take over an owner and the last owner cannot be demoted',async()=>{
  const owner=await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'test-password-12345'}).expect(200)
  const asOwner=req=>req.set('Authorization',`Bearer ${owner.body.accessToken}`)
  const admin=await asOwner(request.post('/api/v1/users')).send({email:'admin@example.test',password:'admin-password-12345',role:'admin'}).expect(201)
  const adminLogin=await request.post('/api/v1/auth/login').send({email:'admin@example.test',password:'admin-password-12345'}).expect(200)
  const asAdmin=req=>req.set('Authorization',`Bearer ${adminLogin.body.accessToken}`)
  await asAdmin(request.post('/api/v1/users')).send({email:'new-owner@example.test',password:'new-owner-password',role:'owner'}).expect(403)
  await asAdmin(request.patch(`/api/v1/users/${owner.body.user.id}`)).send({password:'changed-password-12345'}).expect(403)
  await asAdmin(request.patch(`/api/v1/users/${owner.body.user.id}/profile`)).send({email:'stolen@example.test'}).expect(403)
  await asAdmin(request.post(`/api/v1/users/${owner.body.user.id}/revoke-sessions`)).send({}).expect(403)
  await asOwner(request.patch(`/api/v1/users/${owner.body.user.id}`)).send({role:'admin'}).expect(400)
  assert.equal(admin.body.role,'admin')
})

test('an invitation creates a scoped user once without storing the token',async()=>{
  const owner=await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'test-password-12345'}).expect(200)
  const asOwner=req=>req.set('Authorization',`Bearer ${owner.body.accessToken}`)
  const team=await asOwner(request.post('/api/v1/teams')).send({name:'Invite team'}).expect(201)
  const invite=await asOwner(request.post('/api/v1/invites')).send({email:'invited@example.test',role:'editor',teamId:team.body.id}).expect(201)
  assert.equal(invite.body.delivered,false)
  assert.ok(invite.body.inviteUrl.startsWith('/accept-invite?token='))
  const token=new URL(invite.body.inviteUrl,'http://localhost').searchParams.get('token')
  assert.ok(token)
  const accepted=await request.post('/api/v1/invites/accept').send({token,password:'invite-password-12345'}).expect(201)
  assert.equal(accepted.body.role,'editor')
  assert.equal(accepted.body.teamId,team.body.id)
  await request.post('/api/v1/invites/accept').send({token,password:'invite-password-12345'}).expect(400)
  assert.equal(db.prepare('SELECT email_verified FROM users WHERE id=?').get(accepted.body.id).email_verified,0)
  assert.equal(db.prepare('SELECT token_hash FROM invites WHERE id=?').get(invite.body.id).token_hash===token,false)
})

test('avatar upload validates image bytes and can be removed',async()=>{
  const owner=await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'test-password-12345'}).expect(200)
  const userId=owner.body.user.id,asOwner=req=>req.set('Authorization',`Bearer ${owner.body.accessToken}`)
  const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/sN8AAAAASUVORK5CYII='
  await asOwner(request.put(`/api/v1/users/${userId}/avatar`)).send({mimeType:'image/jpeg',base64:png}).expect(400)
  const uploaded=await asOwner(request.put(`/api/v1/users/${userId}/avatar`)).send({mimeType:'image/png',base64:png}).expect(200)
  assert.ok(uploaded.body.avatarUrl.startsWith(`/api/v1/avatars/${userId}`))
  const fetched=await request.get(`/api/v1/avatars/${userId}`).expect(200)
  assert.equal(fetched.headers['content-type'],'image/png')
  assert.equal(fetched.body.subarray(0,8).toString('hex'),'89504e470d0a1a0a')
  await asOwner(request.delete(`/api/v1/users/${userId}/avatar`)).expect(204)
  await request.get(`/api/v1/avatars/${userId}`).expect(404)
})

test('team membership moves cleanly and team deletion clears references',async()=>{
  const owner=await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'test-password-12345'}).expect(200)
  const auth=req=>req.set('Authorization',`Bearer ${owner.body.accessToken}`)
  const user=await auth(request.post('/api/v1/users')).send({email:'team-member@example.test',password:'team-member-password',role:'auditor'}).expect(201)
  const first=await auth(request.post('/api/v1/teams')).send({name:'First team'}).expect(201)
  const second=await auth(request.post('/api/v1/teams')).send({name:'Second team'}).expect(201)
  await auth(request.patch(`/api/v1/teams/${first.body.id}`)).send({name:'Renamed team'}).expect(200)
  await auth(request.post(`/api/v1/teams/${first.body.id}/members`)).send({userId:user.body.id}).expect(200)
  await auth(request.post(`/api/v1/teams/${second.body.id}/members`)).send({userId:user.body.id}).expect(200)
  assert.equal(db.prepare('SELECT COUNT(*) n FROM team_members WHERE user_id=?').get(user.body.id).n,1)
  assert.equal(db.prepare('SELECT team_id FROM users WHERE id=?').get(user.body.id).team_id,second.body.id)
  await auth(request.delete(`/api/v1/teams/${second.body.id}/members/${user.body.id}`)).expect(204)
  assert.equal(db.prepare('SELECT team_id FROM users WHERE id=?').get(user.body.id).team_id,null)
  await auth(request.post(`/api/v1/teams/${first.body.id}/members`)).send({userId:user.body.id}).expect(200)
  await auth(request.delete(`/api/v1/teams/${first.body.id}`)).expect(204)
  assert.equal(db.prepare('SELECT team_id FROM users WHERE id=?').get(user.body.id).team_id,null)
})

test('email changes require verification and invalidate existing sessions',async()=>{
  const owner=await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'test-password-12345'}).expect(200)
  const user=await request.post('/api/v1/users').set('Authorization',`Bearer ${owner.body.accessToken}`).send({email:'email-old@example.test',password:'email-test-password',role:'auditor'}).expect(201)
  const login=await request.post('/api/v1/auth/login').send({email:'email-old@example.test',password:'email-test-password'}).expect(200)
  await request.patch(`/api/v1/users/${user.body.id}/profile`).set('Authorization',`Bearer ${login.body.accessToken}`).send({email:'email-new@example.test'}).expect(503)
  assert.equal(db.prepare('SELECT email FROM users WHERE id=?').get(user.body.id).email,'email-old@example.test')
  const token=crypto.randomBytes(32).toString('base64url')
  db.prepare('INSERT INTO email_verifications(id,user_id,new_email,token_hash,expires_at) VALUES(?,?,?,?,?)').run(crypto.randomUUID(),user.body.id,'email-new@example.test',crypto.createHash('sha256').update(token).digest('hex'),new Date(Date.now()+60_000).toISOString())
  const verified=await request.post('/api/v1/auth/verify-email').send({token}).expect(200)
  assert.equal(verified.body.email,'email-new@example.test')
  await request.post('/api/v1/auth/verify-email').send({token}).expect(400)
  await request.get('/api/v1/auth/me').set('Authorization',`Bearer ${login.body.accessToken}`).expect(401)
  await request.post('/api/v1/auth/login').send({email:'email-new@example.test',password:'email-test-password'}).expect(200)
})

test('learning proposals preserve traffic direction and require approval before application',async()=>{
  const owner=await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'test-password-12345'}).expect(200)
  const auth=req=>req.set('Authorization',`Bearer ${owner.body.accessToken}`)
  const node=await auth(request.post('/api/v1/nodes')).send({hostname:'learning-agent',ip:'127.0.0.1',connectionMode:'agent'}).expect(201)
  const agentId=crypto.randomUUID()
  db.prepare('INSERT INTO agents(id,node_id,cert_thumbprint,cert_expires_at,version) VALUES(?,?,?,?,?)').run(agentId,node.body.id,'TEST',new Date(Date.now()+864e5).toISOString(),'test')
  db.prepare('UPDATE nodes SET agent_id=? WHERE id=?').run(agentId,node.body.id)
  const started=await auth(request.post('/api/v1/learning-sessions')).send({nodeId:node.body.id,durationHours:24}).expect(201)
  const insert=db.prepare('INSERT INTO log_events(id,node_id,record_id,event_id,action,protocol,src_ip,dst_ip,dst_port,direction) VALUES(?,?,?,?,?,?,?,?,?,?)')
  insert.run(crypto.randomUUID(),node.body.id,1001,5156,'allow','TCP','10.0.0.5','192.0.2.10',443,'out')
  insert.run(crypto.randomUUID(),node.body.id,1002,5156,'allow','TCP','192.0.2.20','10.0.0.5',3389,'in')
  const timed=db.prepare('INSERT INTO log_events(id,node_id,record_id,event_id,action,protocol,src_ip,dst_ip,dst_port,direction,event_time) VALUES(?,?,?,?,?,?,?,?,?,?,?)')
  timed.run(crypto.randomUUID(),node.body.id,1003,5156,'allow','TCP','10.0.0.5','192.0.2.30',445,'out',new Date(Date.now()-864e5).toISOString())
  timed.run(crypto.randomUUID(),node.body.id,1004,5156,'allow','TCP','10.0.0.5','192.0.2.40',445,'out',new Date(Date.now()+48*36e5).toISOString())
  const proposal=await auth(request.post(`/api/v1/learning-sessions/${started.body.id}/finalize`)).send({}).expect(200)
  assert.equal(proposal.body.status,'review')
  assert.equal(proposal.body.ruleCount,2)
  assert.equal(db.prepare('SELECT firewall_state FROM nodes WHERE id=?').get(node.body.id).firewall_state,'review')
  const rules=JSON.parse(db.prepare('SELECT rules_compiled_json FROM policy_versions WHERE id=?').get(proposal.body.versionId).rules_compiled_json)
  assert.deepEqual(rules.map(rule=>[rule.direction,rule.localPort,rule.remotePort,rule.remoteAddress]).sort(),[['in','3389','Any','192.0.2.20'],['out','Any','443','192.0.2.10']])
  await auth(request.post(`/api/v1/policies/${proposal.body.policyId}/assignments`)).send({nodeId:node.body.id}).expect(409)
  const approved=await auth(request.post(`/api/v1/learning-sessions/${started.body.id}/approve`)).send({}).expect(200)
  assert.equal(approved.body.status,'applying')
  assert.equal(db.prepare('SELECT COUNT(*) n FROM agent_jobs WHERE agent_id=?').get(agentId).n,1)
  await auth(request.post(`/api/v1/learning-sessions/${started.body.id}/approve`)).send({}).expect(409)
})

test('group policy assignments count in coverage and compliance',async()=>{
  const owner=await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'test-password-12345'}).expect(200)
  const auth=req=>req.set('Authorization',`Bearer ${owner.body.accessToken}`)
  const node=await auth(request.post('/api/v1/nodes')).send({hostname:'group-coverage',ip:'127.0.0.1'}).expect(201)
  const group=await auth(request.post('/api/v1/node-groups')).send({name:'Coverage group'}).expect(201)
  await auth(request.post(`/api/v1/node-groups/${group.body.id}/members`)).send({nodeId:node.body.id}).expect(200)
  const policy=await auth(request.post('/api/v1/policies')).send({name:'Group coverage policy'}).expect(201)
  await auth(request.post(`/api/v1/policies/${policy.body.id}/versions`)).send({graph:{nodes:[{id:'group-rule',type:'allow',data:{name:'HTTPS',localPort:'443'}}],edges:[]}}).expect(201)
  await auth(request.post(`/api/v1/policies/${policy.body.id}/assignments`)).send({nodeGroupId:group.body.id}).expect(201)
  const coverage=await auth(request.get('/api/v1/reports/coverage')).expect(200)
  const compliance=await auth(request.get('/api/v1/reports/compliance')).expect(200)
  assert.equal(coverage.body.find(row=>row.id===node.body.id).policy_count,1)
  assert.equal(compliance.body.find(row=>row.hostname==='group-coverage').policies,1)
})

test('drift checks record unknown agent state and appear in coverage',async()=>{
  const owner=await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'test-password-12345'}).expect(200)
  const auth=req=>req.set('Authorization',`Bearer ${owner.body.accessToken}`)
  const node=await auth(request.post('/api/v1/nodes')).send({hostname:'drift-agent',ip:'127.0.0.1',connectionMode:'agent'}).expect(201)
  const policy=await auth(request.post('/api/v1/policies')).send({name:'Drift test policy'}).expect(201)
  await auth(request.post(`/api/v1/policies/${policy.body.id}/versions`)).send({graph:{nodes:[{id:'drift-rule',type:'allow',data:{name:'HTTPS',localPort:'443'}}],edges:[]}}).expect(201)
  await auth(request.post(`/api/v1/policies/${policy.body.id}/assignments`)).send({nodeId:node.body.id}).expect(201)
  const checked=await auth(request.post('/api/v1/drift/checks')).send({nodeId:node.body.id,policyId:policy.body.id}).expect(201)
  assert.equal(checked.body.checks.length,1)
  assert.equal(checked.body.checks[0].status,'unknown')
  assert.match(checked.body.checks[0].error,/Agent firewall readback/)
  const listing=await auth(request.get(`/api/v1/drift/checks?nodeId=${node.body.id}`)).expect(200)
  assert.equal(listing.body[0].status,'unknown')
  const coverage=await auth(request.get('/api/v1/reports/coverage')).expect(200)
  assert.equal(coverage.body.find(row=>row.id===node.body.id).drift_status,'unknown')
})

test('policy assignment rejects overlapping opposite rules',async()=>{
  assert.equal(rulesConflict({action:'allow',direction:'in',protocol:'TCP',localPort:'3300-3400',remoteAddress:'Any',program:'Any',profile:'Any'},{action:'block',direction:'in',protocol:'TCP',localPort:'3389',remoteAddress:'Any',program:'Any',profile:'Any'}),true)
  const login=await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'test-password-12345'}).expect(200)
  const auth=req=>req.set('Authorization',`Bearer ${login.body.accessToken}`)
  const node=await auth(request.post('/api/v1/nodes')).send({hostname:'conflict-local',ip:'127.0.0.1'}).expect(201)
  const allow=await auth(request.post('/api/v1/policies')).send({name:'Allow conflict test'}).expect(201)
  const block=await auth(request.post('/api/v1/policies')).send({name:'Block conflict test'}).expect(201)
  for(const [policy,type] of [[allow,'allow'],[block,'deny']])await auth(request.post(`/api/v1/policies/${policy.body.id}/versions`)).send({graph:{nodes:[{id:'rule',type,data:{name:'RDP',localPort:'3389'}}],edges:[]}}).expect(201)
  await auth(request.post(`/api/v1/policies/${allow.body.id}/assignments`)).send({nodeId:node.body.id}).expect(201)
  const response=await auth(request.post(`/api/v1/policies/${block.body.id}/assignments`)).send({nodeId:node.body.id}).expect(409)
  assert.equal(response.body.conflicts[0].otherPolicyId,allow.body.id)
})

test('verifier records real TCP evidence and reports it',async()=>{
  const login=await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'test-password-12345'}).expect(200)
  const auth=req=>req.set('Authorization',`Bearer ${login.body.accessToken}`)
  const listener=createServer(socket=>socket.end())
  await new Promise(resolve=>listener.listen(0,'127.0.0.1',resolve))
  const port=listener.address().port
  try {
    const node=await auth(request.post('/api/v1/nodes')).send({hostname:'verifier-local',ip:'127.0.0.1'}).expect(201)
    const policy=await auth(request.post('/api/v1/policies')).send({name:'Verifier local'}).expect(201)
    await auth(request.post(`/api/v1/policies/${policy.body.id}/versions`)).send({graph:{nodes:[{id:'allow-local',type:'allow',data:{name:'Test listener',localPort:String(port)}}],edges:[]}}).expect(201)
    await auth(request.post(`/api/v1/policies/${policy.body.id}/assignments`)).send({nodeId:node.body.id}).expect(201)
    const verify=await auth(request.post('/api/v1/verifier/runs')).send({nodeId:node.body.id,policyId:policy.body.id}).expect(201)
    assert.equal(verify.body.results[0].status,'pass')
    assert.equal(verify.body.results[0].probeStatus,'open')
    const report=await auth(request.get('/api/v1/reports/verification')).expect(200)
    assert.equal(report.body.find(row=>row.policy==='Verifier local').status,'pass')
  } finally {await new Promise(resolve=>listener.close(resolve))}
})

test('auth, vault, nodes, version history and reports work together',async()=>{
  const login=await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'test-password-12345'}).expect(200)
  assert.ok(login.body.accessToken)
  const token=login.body.accessToken
  const auth=req=>req.set('Authorization',`Bearer ${token}`)
  const credential=await auth(request.post('/api/v1/credentials')).send({name:'Lab',type:'local',username:'Administrator',password:'secret-for-lab'}).expect(201)
  assert.equal(credential.body.password,undefined)
  const listing=await auth(request.get('/api/v1/credentials')).expect(200)
  assert.equal(listing.body[0].encrypted_blob,undefined)
  assert.equal(JSON.stringify(listing.body).includes('secret-for-lab'),false)
  const node=await auth(request.post('/api/v1/nodes')).send({hostname:'localhost',credentialIds:[credential.body.id]}).expect(201)
  assert.equal(node.body.hostname,'localhost')
  const policy=await auth(request.post('/api/v1/policies')).send({name:'Lab policy'}).expect(201)
  const graph={nodes:[{id:'r1',type:'allow',position:{x:20,y:20},data:{name:'RDP',localPort:'3389'}}],edges:[]}
  const v1=await auth(request.post(`/api/v1/policies/${policy.body.id}/versions`)).send({graph,comment:'Initial'}).expect(201)
  assert.equal(v1.body.rules[0].localPort,'3389')
  graph.nodes[0].data.localPort='5985'
  const v2=await auth(request.post(`/api/v1/policies/${policy.body.id}/versions`)).send({graph,comment:'WinRM'}).expect(201)
  assert.equal(v2.body.versionNo,2)
  const diff=await auth(request.get(`/api/v1/policies/${policy.body.id}/diff?from=${v1.body.id}&to=${v2.body.id}`)).expect(200)
  assert.equal(diff.body.added[0].localPort,'5985')
  assert.equal(diff.body.removed[0].localPort,'3389')
  assert.equal(diff.body.graph.changedNodes[0].before.data.localPort,'3389')
  assert.equal(diff.body.graph.changedNodes[0].after.data.localPort,'5985')
  assert.equal(diff.body.graph.addedNodes.length,0)
  const recalled=await auth(request.post(`/api/v1/policies/${policy.body.id}/versions/${v1.body.id}/recall`)).send({}).expect(200)
  assert.equal(recalled.body.versionId,v1.body.id)
  const coverage=await auth(request.get('/api/v1/reports/coverage')).expect(200)
  assert.ok(coverage.body.some(row=>row.hostname==='localhost'))
  const csv=await auth(request.get('/api/v1/reports/coverage?export=csv')).expect(200)
  assert.match(csv.text,/localhost/)
  const audit=await auth(request.get('/api/v1/audit')).expect(200)
  assert.ok(audit.body.some(entry=>entry.action==='policy.recall'))
})

test('invalid login is rejected without exposing account details',async()=>{
  const response=await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'wrong'}).expect(401)
  assert.equal(response.body.error,'Invalid credentials or account locked')
})

test('account changes never put submitted passwords in audit records',async()=>{
  const login=await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'test-password-12345'}).expect(200)
  const auth=req=>req.set('Authorization',`Bearer ${login.body.accessToken}`)
  const user=await auth(request.post('/api/v1/users')).send({email:'audit@example.test',password:'initial-audit-pass-123',role:'editor'}).expect(201)
  const initial=await request.post('/api/v1/auth/login').send({email:'audit@example.test',password:'initial-audit-pass-123'}).expect(200)
  await auth(request.patch(`/api/v1/users/${user.body.id}`)).send({password:'replacement-audit-pass-123'}).expect(200)
  await request.get('/api/v1/auth/me').set('Authorization',`Bearer ${initial.body.accessToken}`).expect(401)
  const replacement=await request.post('/api/v1/auth/login').send({email:'audit@example.test',password:'replacement-audit-pass-123'}).expect(200)
  await auth(request.patch(`/api/v1/users/${user.body.id}/profile`)).send({password:'profile-audit-pass-123'}).expect(200)
  await request.get('/api/v1/auth/me').set('Authorization',`Bearer ${replacement.body.accessToken}`).expect(401)
  const current=await request.post('/api/v1/auth/login').send({email:'audit@example.test',password:'profile-audit-pass-123'}).expect(200)
  await auth(request.post(`/api/v1/users/${user.body.id}/revoke-sessions`)).send({}).expect(200)
  await request.get('/api/v1/auth/me').set('Authorization',`Bearer ${current.body.accessToken}`).expect(401)
  const audit=await auth(request.get('/api/v1/audit')).expect(200)
  const records=audit.body.filter(row=>row.entity_id===user.body.id)
  assert.ok(records.some(row=>row.action==='user.update'))
  assert.ok(records.some(row=>row.action==='user.profile'))
  assert.equal(JSON.stringify(records).includes('replacement-audit-pass-123'),false)
  assert.equal(JSON.stringify(records).includes('profile-audit-pass-123'),false)
})

test('private vault credentials cannot be attached by another editor',async()=>{
  const owner=await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'test-password-12345'}).expect(200)
  const ownerAuth=req=>req.set('Authorization',`Bearer ${owner.body.accessToken}`)
  const secret=await ownerAuth(request.post('/api/v1/credentials')).send({name:'Owner secret',type:'domain',username:'owner',password:'top-secret',visibility:'private'}).expect(201)
  await ownerAuth(request.post('/api/v1/users')).send({email:'editor@example.test',password:'editor-password-123',role:'editor'}).expect(201)
  const editor=await request.post('/api/v1/auth/login').send({email:'editor@example.test',password:'editor-password-123'}).expect(200)
  await request.post('/api/v1/nodes').set('Authorization',`Bearer ${editor.body.accessToken}`).send({hostname:'lab-host',credentialIds:[secret.body.id]}).expect(403)
})

test('TOTP enrollment gates login and can be disabled',async()=>{
  const prior=await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'test-password-12345'}).expect(200)
  const header=`Bearer ${prior.body.accessToken}`
  const setup=await request.post('/api/v1/auth/totp/setup').set('Authorization',header).send({}).expect(200)
  const {totpCode}=await import('../src/totp.js')
  await request.post('/api/v1/auth/totp/confirm').set('Authorization',header).send({code:totpCode(setup.body.secret)}).expect(200)
  await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'test-password-12345'}).expect(401)
  const verified=await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'test-password-12345',totp:totpCode(setup.body.secret)}).expect(200)
  assert.ok(verified.body.accessToken)
  await request.post('/api/v1/auth/totp/disable').set('Authorization',`Bearer ${verified.body.accessToken}`).send({password:'test-password-12345',code:totpCode(setup.body.secret)}).expect(200)
  await request.post('/api/v1/auth/login').send({email:'owner@example.test',password:'test-password-12345'}).expect(200)
})
