import {z} from 'zod'
import {parse as parseDomain} from 'tldts'
import {db,one,all,run,id,now,audit} from '../db.js'
import {hostSchema,hostname,tag,failure} from './schemas.js'
const source={openai:'https://help.openai.com/en/articles/9247338-network-recommendations-for-chatgpt-errors-on-web-and-apps',claude:'https://code.claude.com/docs/en/network-config',copilot:'https://docs.github.com/en/copilot/reference/copilot-allowlist-reference',gemini:'https://ai.google.dev/api',azure:'https://learn.microsoft.com/en-us/azure/ai-studio/ai-services/concepts/endpoints',microsoft:'https://learn.microsoft.com/en-us/microsoft-365/copilot/microsoft-365-copilot-requirements',bedrock:'https://docs.aws.amazon.com/bedrock/latest/userguide/models-endpoint-availability.html'}
const seeds=[
 ['chatgpt.com','suffix','openai','ChatGPT','web','openai'],['api.openai.com','exact','openai','OpenAI API','api','openai'],['auth.openai.com','suffix','openai','OpenAI authentication','auth','openai'],['auth0.openai.com','exact','openai','OpenAI authentication','auth','openai'],['oaistatic.com','suffix','openai','ChatGPT content','update','openai'],['oaiusercontent.com','suffix','openai','ChatGPT content','shared','openai'],
 ['api.anthropic.com','exact','anthropic','Claude API (mixed purpose)','api','claude'],['claude.ai','exact','anthropic','Claude web / authentication','web','claude'],['platform.claude.com','exact','anthropic','Claude account management','auth','claude'],['statsig.anthropic.com','exact','anthropic','Claude telemetry','telemetry','claude'],
 ['githubcopilot.com','suffix','github','GitHub Copilot','api','copilot'],['copilot-proxy.githubusercontent.com','exact','github','Copilot suggestions','api','copilot'],['copilot-telemetry.githubusercontent.com','exact','github','Copilot telemetry','telemetry','copilot'],
 ['generativelanguage.googleapis.com','exact','google','Gemini API','api','gemini'],['openai.azure.com','suffix','microsoft','Azure OpenAI','api','azure'],['services.ai.azure.com','suffix','microsoft','Foundry shared AI services','shared','azure'],['copilot.cloud.microsoft','exact','microsoft','Microsoft Copilot','web','microsoft'],
 ...['us-east-1','us-west-2','eu-west-1','eu-central-1','ap-northeast-1','ap-southeast-2'].map(region=>[`bedrock-runtime.${region}.amazonaws.com`,'exact','aws','Amazon Bedrock','api','bedrock'])
]
export function seedCatalog(){db.transaction(()=>{for(const [host,match,provider,service,role,key] of seeds){const ruleId=`builtin:${host}`;if(one('SELECT id FROM ai_service_rules WHERE id=?',ruleId))continue;const row={id:ruleId,hostname:host,match,provider,service,role,source_url:source[key],reviewed_at:'2026-09-24',version:1,enabled:1,builtin:1,updated_at:now()};run(`INSERT INTO ai_service_rules(${Object.keys(row).join(',')}) VALUES(${Object.keys(row).map(()=>'?').join(',')})`,...Object.values(row));run('INSERT INTO ai_rule_history(rule_id,version,snapshot_json,at) VALUES(?,?,?,?)',ruleId,1,JSON.stringify(row),now())}})()}
export const ruleSchema=z.strictObject({hostname:hostSchema,match:z.enum(['exact','suffix']),provider:tag,service:z.string().trim().min(1).max(100),role:z.enum(['api','web','auth','update','telemetry','shared']),sourceUrl:z.url().max(2048).refine(v=>{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password&&!u.search&&!u.hash},'Use an HTTPS documentation URL without credentials, query or fragment'),reviewedAt:z.iso.date(),enabled:z.boolean().default(true)})
export function listRules(){return all('SELECT * FROM ai_service_rules ORDER BY provider,hostname').map(r=>({...r,enabled:!!r.enabled,builtin:!!r.builtin}))}
export function saveRule(ruleId,input,actor){const v=ruleSchema.parse(input),parsed=parseDomain(v.hostname,{allowPrivateDomains:false});if(parsed.isIcann&&!parsed.domain||v.match==='suffix'&&!parsed.domain)throw failure(400,'public_suffix_rule_forbidden');const before=ruleId?one('SELECT * FROM ai_service_rules WHERE id=?',ruleId):null;if(ruleId&&!before)throw failure(404,'rule_not_found');const conflict=one('SELECT id FROM ai_service_rules WHERE hostname=? AND match=?',v.hostname,v.match);if(conflict&&conflict.id!==ruleId)throw failure(409,'conflicting_service_rule');const newId=ruleId||id(),version=(before?.version||0)+1,row={id:newId,hostname:v.hostname,match:v.match,provider:v.provider,service:v.service,role:v.role,source_url:v.sourceUrl,reviewed_at:v.reviewedAt,version,enabled:Number(v.enabled),builtin:before?.builtin||0,updated_at:now()};db.transaction(()=>{const keys=Object.keys(row);run(`INSERT INTO ai_service_rules(${keys.join(',')}) VALUES(${keys.map(()=>'?').join(',')}) ON CONFLICT(id) DO UPDATE SET ${keys.filter(k=>k!=='id').map(k=>`${k}=excluded.${k}`).join(',')}`,...Object.values(row));run('INSERT INTO ai_rule_history(rule_id,version,snapshot_json,at) VALUES(?,?,?,?)',newId,version,JSON.stringify(row),now());audit(actor,'ai.catalog.update','ai-service-rule',newId,before,row)})();return {...row,enabled:!!row.enabled}}
let revision=-1,cache=[]
export function matchService(raw){const host=hostname(raw);if(!host)return null;const current=one('SELECT max(id) n FROM ai_rule_history').n||0;if(current!==revision){cache=all('SELECT * FROM ai_service_rules ORDER BY length(hostname) DESC, CASE match WHEN \'exact\' THEN 0 ELSE 1 END');revision=current}const rule=cache.find(r=>host===r.hostname||r.match==='suffix'&&host.endsWith('.'+r.hostname));return rule?.enabled?rule:null}
export const registrableDomain=raw=>{const host=hostname(raw);return host?parseDomain(host,{allowPrivateDomains:true}).domain||host:null}
