import {z} from 'zod'
import {eventSchema,receiptSchema,dnsSchema,reporterSchema,settingsSchema,querySchema} from './schemas.js'
import {ruleSchema} from './catalog.js'
const json=schema=>{const {$schema,...rest}=z.toJSONSchema(schema,{io:'input',unrepresentable:'any'});return rest}
export const aiSchemas={AiUsageEvent:json(eventSchema),AiUsageReceipt:json(receiptSchema),AiDnsObservation:json(dnsSchema),AiReporterRequest:json(reporterSchema),AiCollectionSettings:json(settingsSchema),AiServiceRuleRequest:json(ruleSchema),AiUsageBatch:{type:'object',additionalProperties:false,required:['events'],properties:{events:{type:'array',minItems:1,maxItems:100,items:{$ref:'#/components/schemas/AiUsageEvent'},description:'Each event is independently validated. Invalid records return rejected receipts without corrupting accepted operations.'}}},AiHeartbeat:{type:'object',properties:{queued:{type:'integer',minimum:0,maximum:100000},dropped:{type:'integer',minimum:0,maximum:100000},schemaErrors:{type:'integer',minimum:0,maximum:100000},adapterVersion:{type:'string',maxLength:80}}}}
const requests={'POST /ai/usage:batch':'AiUsageBatch','POST /ai/dns':'AiDnsObservation','POST /ai/heartbeat':'AiHeartbeat','POST /ai/reporters':'AiReporterRequest','PATCH /ai/reporters/{id}':'AiReporterRequest','PATCH /ai/settings':'AiCollectionSettings','POST /ai/service-rules':'AiServiceRuleRequest','PATCH /ai/service-rules/{id}':'AiServiceRuleRequest'}
export function describeAiOperation(operation,method,path){
 if(!path.startsWith('/ai/')&&path!=='/nodes/{id}/ai-usage')return
 const key=method.toUpperCase()+' '+path,reporter=['POST /ai/usage:batch','POST /ai/dns','POST /ai/heartbeat'].includes(key)
 operation.tags=['AI usage'];operation.security=[{[reporter?'aiReporterBearer':'bearerAuth']:[]}];operation['x-required-permissions']=reporter?['reporter:bound-nodes']:method==='get'?['auditor']:['admin']
 operation.description=reporter?'Reporter-scoped metadata ingestion. 256 KiB body, 120 requests/minute, no fleet reads. Stable reporter/event IDs return durable idempotent receipts.':'AI metadata and classification evidence. All filtering, sorting and pagination happen on the API. Reported metrics never include inferred traffic operations. Administrative changes and exports are audited.'
 if(requests[key])operation.requestBody={required:true,content:{'application/json':{schema:{$ref:'#/components/schemas/'+requests[key]}}}}
 if(key==='POST /ai/usage:batch')operation.responses={200:{description:'Durable per-event receipts',content:{'application/json':{schema:{$ref:'#/components/schemas/AiUsageReceipt'}}}},400:{description:'Invalid batch'},401:{description:'Invalid or revoked reporter'},413:{description:'Body limit exceeded'},429:{description:'Rate limit exceeded'},503:{description:'Collection paused or temporarily unavailable'}}
 if(['POST /ai/reporters','POST /ai/dns','POST /ai/service-rules'].includes(key)){operation.responses[201]=operation.responses[200];delete operation.responses[200]}
 if(key==='POST /ai/backfill'){operation.responses[202]=operation.responses[200];delete operation.responses[200]}
 if(method==='get'&&(/^\/ai\/(usage|observations)(\/(summary|export))?$/.test(path)||path==='/nodes/{id}/ai-usage'))operation.parameters.push(...Object.entries(json(querySchema).properties).filter(([name])=>name!=='nodeId'||path!=='/nodes/{id}/ai-usage').map(([name,schema])=>({name,in:'query',schema})))
 if(method==='get'&&['/ai/reporters','/ai/service-rules'].includes(path))operation.parameters.push(...Object.entries({q:{type:'string',maxLength:200},page:{type:'integer',minimum:1,default:1},limit:{type:'integer',minimum:1,maximum:1000,default:25},sort:{type:'string',description:'Reporters: name/coverage/status. Catalog: hostname/provider/service/role.'},order:{type:'string',enum:['asc','desc'],default:'asc'}}).map(([name,schema])=>({name,in:'query',schema})))
 if(path.endsWith('/suggestions'))operation.parameters.push(...['ip','mac','hostname','at'].map(name=>({name,in:'query',schema:{type:'string'},description:'Suggestion evidence only; never changes bindings.'})))
}
