import {z} from 'zod'
const zConfig=z.object({q:z.string().max(200).default(''),page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(1000).default(25),sort:z.string().default(''),order:z.enum(['asc','desc']).default('asc')})
import {db,one,all,run,now} from '../db.js'
import {canReadResource} from '../access.js'
import {querySchema,failure} from './schemas.js'
import {settings,listReporters,bindings,publicReporter} from './reporters.js'
// Sum decimal costs exactly; do not blend currencies or estimate missing metrics.
db.aggregate('ai_decimal_sum',{start:()=>0n,step:(total,value)=>{if(value==null)return total;const [whole,fraction='']=String(value).split('.');return total+BigInt(whole)*1000000000n+BigInt(fraction.padEnd(9,'0'))},result:total=>`${total/1000000000n}.${String(total%1000000000n).padStart(9,'0')}`.replace(/\.?0+$/,'')||'0'})
db.aggregate('ai_token_sum',{start:()=>({total:0n,known:false}),step:(state,value)=>{if(value!=null){state.total+=BigInt(value);state.known=true}return state},result:state=>!state.known?null:state.total<=BigInt(Number.MAX_SAFE_INTEGER)?Number(state.total):String(state.total)})
const escape=v=>'%'+v.replace(/[\\%_]/g,'\\$&')+'%'
function selection(input,kind,user){
 const q=querySchema.parse(input),reported=kind==='usage',clauses=[],args=[],alias='a'
 if(q.groupId){const group=one('SELECT * FROM node_groups WHERE id=?',q.groupId);if(!canReadResource(user,'node_group',group))throw failure(403,'group_not_authorized');clauses.push('EXISTS(SELECT 1 FROM node_group_members m WHERE m.node_id=a.node_id AND m.group_id=?)');args.push(q.groupId)}
 for(const [key,col] of [['nodeId','node_id'],['provider','provider']])if(q[key]){clauses.push(`a.${col}=?`);args.push(q[key])}
 if(reported){for(const [key,col] of [['reporterId','reporter_id'],['actorId','actor_id'],['model','model'],['operation','operation'],['tool','tool'],['outcome','outcome']])if(q[key]){clauses.push(`a.${col}=?`);args.push(q[key])}if(q.category&&q.category!=='reported'||q.confidence&&q.confidence!=='reported')clauses.push('0')}
 else {for(const key of ['reporterId','actorId','model','operation','tool'])if(q[key])clauses.push('0');for(const [key,col] of [['category','category'],['confidence','confidence'],['outcome','action']])if(q[key]){clauses.push(`a.${col}=?`);args.push(q[key])}}
 if(q.mapped!=='all')clauses.push(`a.node_id IS ${q.mapped==='mapped'?'NOT ':''}NULL`)
 if(q.from){clauses.push('a.observed_at>=?');args.push(q.from)}if(q.to){clauses.push('a.observed_at<=?');args.push(q.to)}
 if(q.q){const columns=reported?['n.hostname','a.hostname','a.provider','a.model','a.operation','a.tool','r.name','u.email']:['n.hostname','a.hostname','a.peer_ip','a.provider','a.program','a.service'];clauses.push('('+columns.map(c=>`${c} LIKE ? ESCAPE '\\'`).join(' OR ')+')');args.push(...columns.map(()=>escape(q.q)))}
 const from=`FROM ${reported?'ai_usage_events':'ai_network_observations'} a LEFT JOIN nodes n ON n.id=a.node_id ${reported?'LEFT JOIN ai_reporters r ON r.id=a.reporter_id LEFT JOIN users u ON u.id=a.actor_id':''} WHERE ${clauses.join(' AND ')||'1'}`
 const sorting={time:'a.observed_at',node:'n.hostname',provider:'a.provider',operation:reported?'a.operation':'a.category',outcome:reported?'a.outcome':'a.action',model:reported?'a.model':'a.service',reporter:reported?'r.name':'a.source',hostname:'a.hostname'}
 return {q,args,from,sort:sorting[q.sort],reported}
}
const publicUsage=r=>({...r,category:'reported',confidence:'reported',metricsCoverage:r.input_tokens===null&&r.output_tokens===null?'unreported':'partial or reported',actorSource:r.actor_id?'administrator-bound':'unknown'})
const publicObservation=({evidence_json,...r})=>({...r,evidence:JSON.parse(evidence_json),sourceExpired:!!r.source_expired,sourceUrl:r.source==='firewall'?`/logs?event=${encodeURIComponent(r.source_id)}`:`/internet?tab=activity&event=${encodeURIComponent(r.source_id)}`})
function summary(s){const base=one(`SELECT count(*) total,count(DISTINCT a.node_id) nodes ${s.from}`,...s.args);if(s.reported){const metrics=one(`SELECT ai_token_sum(a.input_tokens) inputTokens,ai_token_sum(a.output_tokens) outputTokens,sum(a.input_tokens IS NOT NULL OR a.output_tokens IS NOT NULL) operationsWithMetrics,sum(a.outcome='incomplete') incomplete ${s.from}`,...s.args);const costs=all(`SELECT a.currency,a.cost_source source,ai_decimal_sum(a.cost_amount) amount,count(*) operations ${s.from} AND a.cost_amount IS NOT NULL GROUP BY a.currency,a.cost_source`,...s.args);return {...base,...metrics,costs,coverage:'Reported metrics only; uninstrumented operations are unknown'}}return {...base,categories:all(`SELECT a.category,count(*) total ${s.from} GROUP BY a.category`,...s.args),outcomes:all(`SELECT a.action,count(*) total ${s.from} GROUP BY a.action`,...s.args),coverage:'Service observations are not completed AI operations'}}
export function listAi(input,kind,user,{exportAll=false}={}){return db.transaction(()=>{const s=selection(input,kind,user),stats=summary(s);if(exportAll&&stats.total>10000)throw failure(400,'narrow_export_to_10000');const page=Math.min(s.q.page,Math.max(1,Math.ceil(stats.total/s.q.limit))),limit=exportAll?10000:s.q.limit;const items=all(`SELECT a.*,n.hostname node_hostname ${s.reported?',r.name reporter_name,u.email actor_email':''} ${s.from} ORDER BY ${s.sort} ${s.q.order},a.id LIMIT ? OFFSET ?`,...s.args,limit,exportAll?0:(page-1)*limit).map(s.reported?publicUsage:publicObservation);return {items,page,limit,total:stats.total,pages:Math.max(1,Math.ceil(stats.total/s.q.limit)),summary:stats}})()}
export const summarizeAi=(input,kind,user)=>summary(selection(input,kind,user))
export function aiDetails(recordId,kind){if(kind==='usage'){const r=one('SELECT a.*,n.hostname node_hostname,r.name reporter_name,u.email actor_email FROM ai_usage_events a LEFT JOIN nodes n ON n.id=a.node_id JOIN ai_reporters r ON r.id=a.reporter_id LEFT JOIN users u ON u.id=a.actor_id WHERE a.id=?',recordId);if(!r)throw failure(404,'activity_not_found');return {...publicUsage(r),receipts:all('SELECT id,event_id,received_at FROM ai_receipts WHERE usage_id=?',recordId),evidence:all('SELECT o.*,e.reason,e.association FROM ai_usage_evidence e JOIN ai_network_observations o ON o.id=e.observation_id WHERE e.usage_id=? ORDER BY o.observed_at LIMIT 100',recordId).map(publicObservation)}}const r=one('SELECT a.*,n.hostname node_hostname FROM ai_network_observations a LEFT JOIN nodes n ON n.id=a.node_id WHERE a.id=?',recordId);if(!r)throw failure(404,'observation_not_found');return {...publicObservation(r),activities:all('SELECT e.usage_id,e.reason,e.association FROM ai_usage_evidence e WHERE e.observation_id=? LIMIT 100',recordId)}}
export function health(){const state=one('SELECT * FROM ai_worker_state WHERE id=1'),cfg=settings(),reporters=listReporters();return {settings:cfg,worker:state,backlog:one('SELECT count(*) n FROM ai_work_queue').n,backfill:{firewallRemaining:one('SELECT count(*) n FROM log_events WHERE rowid>?',state.firewall_cursor).n,browserRemaining:one('SELECT count(*) n FROM internet_events WHERE rowid>?',state.browser_cursor).n},reporters:{total:reporters.length,active:reporters.filter(r=>r.status==='active').length,stale:reporters.filter(r=>r.status==='active'&&r.stale).length},dns:{nodes:one('SELECT count(DISTINCT node_id) n FROM ai_dns_observations').n,lastObservation:one('SELECT max(observed_at) at FROM ai_dns_observations').at},metadataOnly:true,now:now()}}
export function attributionSuggestions(reporterId,{ip,mac,hostname:host,at}={}){
 const allowed=bindings(reporterId),when=Date.parse(at||now());if(!Number.isFinite(when))throw failure(400,'invalid_time');const norm=v=>String(v||'').toLowerCase().replace(/[^a-f0-9]/g,'');const results=[]
 for(const n of all('SELECT id,hostname,fqdn,ip,mac_address,dhcp_lease_json,agent_id FROM nodes')){if(!allowed.includes(n.id))continue;const reasons=[];if(ip&&n.ip===ip)reasons.push('current-inventory-address');if(mac&&norm(n.mac_address)===norm(mac))reasons.push('inventory-mac');if(host&&[n.hostname,n.fqdn].some(h=>h?.toLowerCase()===host.toLowerCase()))reasons.push('inventory-name');let lease;try{lease=JSON.parse(n.dhcp_lease_json||'null')}catch{};if(lease&&ip===lease.ip&&Date.parse(lease.observedAt)<=when&&Date.parse(lease.leaseExpiry||lease.leaseExpiresAt||lease.expiresAt)>when)reasons.push('active-dhcp-lease');if(reasons.length)results.push({nodeId:n.id,hostname:n.hostname,reasons,agentEnrolled:!!n.agent_id})}
 return {candidates:results,uniqueAuthorizedMatch:results.length===1?results[0].nodeId:null,automaticBinding:false,reason:results.length===1?'Review unique authorized suggestion':'Unmapped: no unique authorized match'}
}
export function listAiConfiguration(input,kind){
 const q=zConfig.parse(input),table=kind==='reporters'?'ai_reporters':'ai_service_rules',columns=kind==='reporters'?['name','coverage','status']:['hostname','provider','service','role'],where=q.q?' WHERE ('+columns.map(c=>`${c} LIKE ? ESCAPE '\\'`).join(' OR ')+')':'',args=q.q?columns.map(()=>escape(q.q)):[]
 const total=one(`SELECT count(*) n FROM ${table}${where}`,...args).n,page=Math.min(q.page,Math.max(1,Math.ceil(total/q.limit))),sort=columns.includes(q.sort)?q.sort:columns[0]
 const rows=all(`SELECT * FROM ${table}${where} ORDER BY ${sort} ${q.order},id LIMIT ? OFFSET ?`,...args,q.limit,(page-1)*q.limit)
 return {items:rows.map(kind==='reporters'?publicReporter:r=>({...r,enabled:!!r.enabled,builtin:!!r.builtin})),total,page,pages:Math.max(1,Math.ceil(total/q.limit)),limit:q.limit}
}
