import crypto from 'node:crypto'
import {db,one,all,run,id,now,audit} from '../db.js'
import {hashToken} from '../security.js'
import {reporterSchema,settingsSchema,failure} from './schemas.js'
export const settings=()=>JSON.parse(one('SELECT json FROM ai_settings WHERE id=1').json)
export function saveSettings(input,actor){const v=settingsSchema.parse(input),before=settings();run('UPDATE ai_settings SET json=? WHERE id=1',JSON.stringify(v));audit(actor,'ai.settings.update','ai-settings','1',before,v);return v}
export const bindings=reporterId=>all('SELECT node_id FROM ai_reporter_nodes WHERE reporter_id=? ORDER BY node_id',reporterId).map(r=>r.node_id)
export function publicReporter(row){if(!row)return null;const {credential_hash,health_json,issuer,subject,client_id,...safe}=row;return {...safe,userApiKeyId:one('SELECT id FROM user_api_keys WHERE reporter_id=?',row.id)?.id||null,nodeIds:bindings(row.id),oauth:!!issuer,oauthBinding:issuer?{issuer,subject,clientId:client_id}:null,health:JSON.parse(health_json),stale:!row.last_heartbeat_at||Date.now()-Date.parse(row.last_heartbeat_at)>settings().staleReporterMinutes*60000}}
export function listReporters(){return all('SELECT * FROM ai_reporters ORDER BY name,id').map(publicReporter)}
function validateBinding(v){for(const nodeId of v.nodeIds)if(!one('SELECT id FROM nodes WHERE id=?',nodeId))throw failure(400,'unknown_node');if(v.actorId&&!one('SELECT id FROM users WHERE id=? AND suspended=0',v.actorId))throw failure(400,'unknown_actor');if(v.coverage!=='collector'&&v.nodeIds.length>1)throw failure(400,'multiple_nodes_require_collector');if(v.issuer&&new URL(v.issuer).protocol!=='https:'&&process.env.NODE_ENV!=='test')throw failure(400,'issuer_requires_https')}
const secret=()=>`wfai_${crypto.randomBytes(36).toString('base64url')}`
export function enrollReporter(input,actor){
 const v=reporterSchema.parse(input);validateBinding(v);const reporterId=id(),credential=secret(),stamp=now()
 db.transaction(()=>{run('INSERT INTO ai_reporters(id,name,credential_hash,coverage,actor_id,issuer,subject,client_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)',reporterId,v.name,hashToken(credential),v.coverage,v.actorId||null,v.issuer||null,v.subject||null,v.clientId||null,stamp,stamp);for(const n of new Set(v.nodeIds))run('INSERT INTO ai_reporter_nodes VALUES(?,?)',reporterId,n);audit(actor,'ai.reporter.enroll','ai-reporter',reporterId,null,{name:v.name,nodeIds:v.nodeIds,coverage:v.coverage,oauth:!!v.issuer})})()
 return {reporter:publicReporter(one('SELECT * FROM ai_reporters WHERE id=?',reporterId)),credential}
}
export function editReporter(reporterId,input,actor){if(one('SELECT id FROM user_api_keys WHERE reporter_id=?',reporterId))throw failure(409,'manage_reporter_in_security_api_keys');const before=publicReporter(one('SELECT * FROM ai_reporters WHERE id=?',reporterId));if(!before)throw failure(404,'reporter_not_found');const v=reporterSchema.parse(input);validateBinding(v);db.transaction(()=>{run('UPDATE ai_reporters SET name=?,coverage=?,actor_id=?,issuer=?,subject=?,client_id=?,updated_at=? WHERE id=?',v.name,v.coverage,v.actorId||null,v.issuer||null,v.subject||null,v.clientId||null,now(),reporterId);run('DELETE FROM ai_reporter_nodes WHERE reporter_id=?',reporterId);for(const n of new Set(v.nodeIds))run('INSERT INTO ai_reporter_nodes VALUES(?,?)',reporterId,n);audit(actor,'ai.reporter.update','ai-reporter',reporterId,before,{...v})})();return publicReporter(one('SELECT * FROM ai_reporters WHERE id=?',reporterId))}
export function rotateReporter(reporterId,actor){if(one('SELECT id FROM user_api_keys WHERE reporter_id=?',reporterId))throw failure(409,'manage_reporter_in_security_api_keys');const r=one('SELECT * FROM ai_reporters WHERE id=?',reporterId);if(!r)throw failure(404,'reporter_not_found');if(r.status!=='active')throw failure(409,'reporter_revoked');const credential=secret();run('UPDATE ai_reporters SET credential_hash=?,updated_at=? WHERE id=?',hashToken(credential),now(),reporterId);audit(actor,'ai.reporter.rotate','ai-reporter',reporterId,null,{rotated:true});return {credential,reporter:publicReporter(one('SELECT * FROM ai_reporters WHERE id=?',reporterId))}}
export function revokeReporter(reporterId,actor){if(!one('SELECT id FROM ai_reporters WHERE id=?',reporterId))throw failure(404,'reporter_not_found');run("UPDATE ai_reporters SET status='revoked',credential_hash=NULL,updated_at=? WHERE id=?",now(),reporterId);run('UPDATE user_api_keys SET revoked_at=COALESCE(revoked_at,?),updated_at=? WHERE reporter_id=?',now(),now(),reporterId);audit(actor,'ai.reporter.revoke','ai-reporter',reporterId,null,{revoked:true});return {revoked:true}}
export function activeReporter(reporterId){const reporter=one("SELECT * FROM ai_reporters WHERE id=? AND status='active'",reporterId);if(!reporter)throw failure(401,'reporter_revoked');return reporter}
export function reporterAuth(req,res,next){const token=req.headers.authorization?.match(/^Bearer (wfai_[A-Za-z0-9_-]+)$/)?.[1];const r=token&&one("SELECT * FROM ai_reporters WHERE credential_hash=? AND status='active'",hashToken(token));if(!r)return res.status(401).json({error:'Valid AI reporter credential required',code:'reporter_auth_required'});req.aiReporter=r;next()}
export function boundNode(reporter,nodeId){const allowed=bindings(reporter.id);if(nodeId){if(!allowed.includes(nodeId))throw failure(403,'node_not_authorized');return nodeId}return allowed.length===1?allowed[0]:null}
export function heartbeat(reporterId,input){activeReporter(reporterId);const numeric=k=>Math.max(0,Math.min(100000,Number.isInteger(input[k])?input[k]:0));const health={queued:numeric('queued'),dropped:numeric('dropped'),schemaErrors:numeric('schemaErrors'),adapterVersion:typeof input.adapterVersion==='string'&&/^[\w.:-]{1,80}$/.test(input.adapterVersion)?input.adapterVersion:null};run('UPDATE ai_reporters SET last_heartbeat_at=?,health_json=? WHERE id=?',now(),JSON.stringify(health),reporterId);return {received:true}}
