<script setup>
import {computed,onMounted,ref} from 'vue'
import {api,session} from '../../services/api.js'
const canEdit=computed(()=>['owner','admin','editor'].includes(session.user?.role))
const policies=ref([]),policyDraft=ref([]),rulePattern=ref(''),ruleMatch=ref('hostname'),ruleAction=ref('block'),policyFailMode=ref('open'),policyComment=ref(''),policyBusy=ref(false),policyError=ref(''),policyMessage=ref('')
function addRule(){if(!rulePattern.value.trim())return;policyDraft.value.push({pattern:rulePattern.value.trim(),match:ruleMatch.value,action:ruleAction.value,nodeIds:[],nodeGroupIds:[],resourceTypes:['main_frame']});rulePattern.value=''}
async function stagePolicy(){policyBusy.value=true;policyError.value='';policyMessage.value='';try{await api('/internet/policies',{method:'POST',body:{rules:policyDraft.value,failMode:policyFailMode.value,comment:policyComment.value}});policyMessage.value='Internet policy staged. Publish it after review.';policyComment.value='';await load()}catch(error){policyError.value=error.message}finally{policyBusy.value=false}}
async function publishPolicy(policy){policyBusy.value=true;policyError.value='';try{await api(`/internet/policies/${policy.id}/publish`,{method:'POST'});policyMessage.value=`Internet policy version ${policy.version_no} published.`;await load()}catch(error){policyError.value=error.message}finally{policyBusy.value=false}}
async function rollbackPolicy(policy){policyBusy.value=true;policyError.value='';try{await api(`/internet/policies/${policy.id}/rollback`,{method:'POST'});policyMessage.value='Internet policy rolled back.';await load()}catch(error){policyError.value=error.message}finally{policyBusy.value=false}}

async function load(){try{policies.value=await api('/internet/policies')}catch(e){policyError.value=e.message}}
onMounted(load)
defineExpose({refresh:load})
</script>
<template>    <section class="panel glass internet-policy-panel"><div class="panel-title"><div><span class="eyebrow">CONTROL</span><h2>Internet policy studio</h2></div><span class="count-chip">{{policies.length}} versions</span></div><p class="hint">Stage declarative browser rules, review the compiled scope, then publish. Existing extensions keep their last confirmed rules while disconnected.</p><div v-if="policyError" class="error-msg">{{policyError}}</div><div v-if="policyMessage" class="success-msg">{{policyMessage}}</div><div v-if="canEdit" class="internet-policy-form"><input v-model.trim="rulePattern" placeholder="example.com or /admin" aria-label="Internet pattern"><select v-model="ruleMatch" aria-label="Pattern match"><option value="hostname">Hostname</option><option value="domain">Domain</option><option value="prefix">URL prefix</option></select><select v-model="ruleAction" aria-label="Rule action"><option value="block">Block</option><option value="allow">Allow</option></select><button class="button secondary" type="button" @click="addRule">Add rule</button></div><div v-if="policyDraft.length" class="table-wrap"><table><thead><tr><th>PATTERN</th><th>MATCH</th><th>ACTION</th><th></th></tr></thead><tbody><tr v-for="(rule,index) in policyDraft" :key="`${rule.pattern}-${index}`"><td class="mono">{{rule.pattern}}</td><td>{{rule.match}}</td><td><span class="status" :class="rule.action">{{rule.action}}</span></td><td><button class="button small danger" type="button" @click="policyDraft.splice(index,1)">Remove</button></td></tr></tbody></table></div><div v-if="canEdit" class="internet-policy-footer"><label>Offline behavior<select v-model="policyFailMode"><option value="open">Fail open</option><option value="closed">Fail closed</option></select></label><label>Comment<input v-model.trim="policyComment" placeholder="Reason for this staged version"></label><button class="button primary" :disabled="policyBusy||!policyDraft.length" @click="stagePolicy">{{policyBusy?'Saving…':'Stage version'}}</button></div><div class="table-wrap" v-if="policies.length"><table><thead><tr><th>VERSION</th><th>STATUS</th><th>RULES</th><th>CREATED</th><th></th></tr></thead><tbody><tr v-for="policy in policies" :key="policy.id"><td>v{{policy.version_no}}</td><td>{{policy.status}}</td><td>{{policy.rules.length}}</td><td>{{new Date(policy.created_at).toLocaleString()}}</td><td class="inline-actions"><button v-if="session.user?.role==='admin'||session.user?.role==='owner'" class="button small primary" :disabled="policyBusy||policy.status==='published'" @click="publishPolicy(policy)">Publish</button><button v-if="session.user?.role==='admin'||session.user?.role==='owner'" class="button small secondary" :disabled="policyBusy||policy.status!=='published'" @click="rollbackPolicy(policy)">Rollback</button></td></tr></tbody></table></div></section>
</template>
<style scoped src="./internet.css"></style>
