<script setup>
import {computed,onMounted,ref} from 'vue'
import GlassWindow from '../GlassWindow.vue'
import {api,session} from '../../services/api.js'
const devices=ref([]),nodes=ref([]),groups=ref([]),users=ref([]),error=ref('')
const enrollmentOpen=ref(false),enrollmentBusy=ref(false),enrollmentError=ref(''),enrollmentResult=ref(null),enrollmentForm=ref({target:'node',nodeId:'',nodeGroupId:'',userId:'',collectionLevel:'host'})
const canEnroll=computed(()=>['owner','admin','editor'].includes(session.user?.role))
async function openEnrollment(){try{const requests=[api('/nodes'),api('/node-groups')];if(['owner','admin'].includes(session.user?.role))requests.push(api('/users'));const [n,g,u]=await Promise.all(requests);nodes.value=n;groups.value=g;users.value=u||[]}catch(e){error.value=e.message;return}enrollmentError.value='';enrollmentResult.value=null;enrollmentForm.value={target:'node',nodeId:nodes.value[0]?.id||'',nodeGroupId:'',userId:'',collectionLevel:'host'};enrollmentOpen.value=true}
async function createEnrollment(){enrollmentBusy.value=true;enrollmentError.value='';enrollmentResult.value=null;try{const body={collectionLevel:enrollmentForm.value.collectionLevel};if(enrollmentForm.value.target==='node')body.nodeId=enrollmentForm.value.nodeId;else body.nodeGroupId=enrollmentForm.value.nodeGroupId;if(enrollmentForm.value.userId)body.userId=enrollmentForm.value.userId;enrollmentResult.value=await api('/internet/enrollment',{method:'POST',body})}catch(cause){enrollmentError.value=cause.message}finally{enrollmentBusy.value=false}}
async function copyEnrollment(){if(!enrollmentResult.value?.token)return;try{await navigator.clipboard.writeText(enrollmentResult.value.token)}catch{enrollmentError.value='Copy failed; select the token text and copy it manually.'}}

async function load(){error.value='';try{devices.value=await api('/internet/devices')}catch(e){error.value=e.message}}
onMounted(load)
defineExpose({refresh:load})
</script>
<template><div><div v-if="error" class="error-msg" role="alert">{{error}}</div>    <section class="panel glass internet-devices"><div class="panel-title"><div><span class="eyebrow">ENROLLMENTS</span><h2>Browser devices</h2></div><div class="inline-actions"><span class="count-chip">{{devices.length}}</span><button v-if="canEnroll" class="button small primary" @click="openEnrollment">Create enrollment</button></div></div><div class="table-wrap"><table><thead><tr><th>DEVICE</th><th>NODE / GROUP</th><th>USER</th><th>BROWSER</th><th>VERSION</th><th>STATUS</th><th>LAST SEEN</th></tr></thead><tbody><tr v-for="device in devices" :key="device.id"><td class="mono">{{device.id}}</td><td>{{device.nodeHostname||device.nodeGroupName||'—'}}</td><td>{{device.userEmail||'Unmapped'}}</td><td>{{device.browser}}</td><td>{{device.extensionVersion}}</td><td><span class="status" :class="device.status==='active'?'reachable':'unreachable'">{{device.status}}</span></td><td>{{new Date(device.lastSeenAt).toLocaleString()}}</td></tr><tr v-if="!devices.length"><td colspan="7" class="empty-table">No browser devices enrolled.</td></tr></tbody></table></div></section>
    <GlassWindow v-model="enrollmentOpen" title="Create browser enrollment" width="620px"><form class="form-grid" @submit.prevent="createEnrollment"><p class="hint">Bind this one-time browser token to a managed node or group. Optionally select a WinFire or AD-backed operator so Internet events can be queried by user.</p><label>Target type<select v-model="enrollmentForm.target"><option value="node">Node</option><option value="group">Node group</option></select></label><label v-if="enrollmentForm.target==='node'">Node<select v-model="enrollmentForm.nodeId" required><option value="">Select node</option><option v-for="node in nodes" :key="node.id" :value="node.id">{{node.hostname}}</option></select></label><label v-else>Node group<select v-model="enrollmentForm.nodeGroupId" required><option value="">Select group</option><option v-for="group in groups" :key="group.id" :value="group.id">{{group.name}}</option></select></label><label v-if="session.user?.role==='admin'||session.user?.role==='owner'">Bind operator (optional)<select v-model="enrollmentForm.userId"><option value="">No user binding</option><option v-for="user in users" :key="user.id" :value="user.id">{{user.email}} · {{user.role}}</option></select></label><label>Collection level<select v-model="enrollmentForm.collectionLevel"><option value="host">Host only</option><option value="path">Host and path prefix</option></select></label><p v-if="enrollmentError" class="error-msg" role="alert">{{enrollmentError}}</p><div v-if="enrollmentResult" class="enrollment-result"><label>One-time token<textarea :value="enrollmentResult.token" readonly rows="2"></textarea></label><p>Assigned user: {{enrollmentResult.userEmail||'Unmapped'}} · expires {{new Date(enrollmentResult.expiresAt).toLocaleString()}}</p><button type="button" class="button secondary" @click="copyEnrollment">Copy token</button></div><div class="form-actions"><button type="button" class="button secondary" @click="enrollmentOpen=false">Close</button><button class="button primary" :disabled="enrollmentBusy||!!enrollmentResult">{{enrollmentBusy?'Creating…':'Create token'}}</button></div></form></GlassWindow>
</div></template>
<style scoped src="./internet.css"></style>
