<script setup>
import {computed,onMounted,onActivated,onDeactivated,onBeforeUnmount,ref} from 'vue'
import {api,session} from '../../services/api.js'
import {internetConnections as service} from '../../services/internetConnections.js'
import TransactionDetailsDialog from '../TransactionDetailsDialog.vue'
import GlassWindow from '../GlassWindow.vue'
const fields=[['q','Search'],['nodeId','Reporting node'],['groupId','Node group'],['ip','Peer IP / CIDR'],['hostname','Reverse hostname'],['program','Program'],['protocol','Protocol'],['port','Destination port'],['direction','Direction'],['action','Action'],['dnsState','DNS state'],['from','From'],['to','To']]
const defaults=()=>Object.fromEntries(fields.map(([key])=>[key,key==='direction'?'out':'']))
const draft=ref(defaults()),applied=ref(defaults()),page=ref(1),limit=ref(25),sort=ref('time'),order=ref('desc'),nodes=ref([]),groups=ref([])
const choices=computed(()=>({nodeId:[['','All nodes'],...nodes.value.map(n=>[n.id,n.hostname])],groupId:[['','All groups'],...groups.value.map(g=>[g.id,g.name])],protocol:[['','All protocols'],...['TCP','UDP','ICMP','ICMPv6'].map(v=>[v,v])],direction:[['out','Outbound'],['in','Inbound'],['unknown','Unknown'],['all','All directions']],action:[['','All actions'],['allow','Allowed observation'],['block','Blocked attempt']],dnsState:[['','All states'],['pending','Pending'],['resolved','Resolved'],['not-found','No PTR'],['stale','Stale'],['error','Lookup error']]}))
const result=ref({items:[],total:0,page:1,pages:1,summary:{events:0,peers:0,allowed:0,blocked:0,scope:{}}}),loading=ref(false),error=ref(''),message=ref(''),busy=ref(false)
const detail=ref(null),detailOpen=ref(false),peer=ref(null),peerOpen=ref(false),confirmOpen=ref(false),action=ref('allow'),policies=ref([]),policyId=ref('')
const canManage=computed(()=>['owner','admin'].includes(session.user?.role)),canResolve=computed(()=>['owner','admin','editor'].includes(session.user?.role)),scope=computed(()=>result.value.summary.scope||{})
const columns=[['time','Time'],['node','Reporting node / Local IP'],['peer','Peer IP / Reverse DNS'],['direction','Direction'],['action','Observation'],['protocol','Protocol'],['port','Ports'],['program','Program']]
let sequence=0,timer
function query(){const values={...applied.value,page:page.value,limit:limit.value,sort:sort.value,order:order.value};for(const key of ['from','to'])if(values[key])values[key]=new Date(values[key]).toISOString();return new URLSearchParams(Object.entries(values).filter(([,v])=>v!==''))}
async function load(){const current=++sequence;loading.value=true;error.value='';try{const data=await service.list(query());if(current===sequence){result.value=data;page.value=data.page}}catch(e){if(current===sequence)error.value=e.message}finally{if(current===sequence)loading.value=false}}
function apply(){applied.value={...draft.value};page.value=1;load()}
function clear(){draft.value=defaults();apply()}
function sorting(key){if(sort.value===key)order.value=order.value==='asc'?'desc':'asc';else{sort.value=key;order.value='asc'}page.value=1;load()}
function move(next){page.value=next;load()}
async function open(row){error.value='';try{detail.value=await service.details(row.id);detailOpen.value=true}catch(e){error.value=e.message}}
async function showPeer(row){try{peer.value=await service.peer(row.peer_id);peerOpen.value=true}catch(e){error.value=e.message}}
async function resolve(){busy.value=true;try{await service.resolve(peer.value.id);message.value='Reverse-DNS refresh queued.';peer.value=await service.peer(peer.value.id)}catch(e){error.value=e.message}finally{busy.value=false}}
async function begin(kind){action.value=kind;policyId.value='';if(kind!=='ignore')try{policies.value=(await api('/policies')).filter(p=>p.origin!=='learned'&&p.scopes?.some(s=>s.node_group_id))}catch(e){error.value=e.message;return}confirmOpen.value=true}
async function save(){busy.value=true;try{if(action.value==='ignore'){await service.ignore(detail.value.id);message.value='Traffic ignore rule saved.'}else{const saved=await service.rule(detail.value.id,{action:action.value,...(policyId.value?{policyId:policyId.value}:{})});message.value=`Firewall rule saved to policy version ${saved.versionNo}; pending policy sync.`}confirmOpen.value=false;detailOpen.value=false;await load()}catch(e){error.value=e.message}finally{busy.value=false}}
async function exportRows(){busy.value=true;try{await service.export(query())}catch(e){error.value=e.message}finally{busy.value=false}}
const attribution=value=>({'reporting-node-address':'Host address match','legacy-inbound-corrected':'Legacy inbound layout','forwarded-local-endpoint':'Forwarded traffic','cidr-endpoint':'Local CIDR match','reported-direction-roaming':'Reported direction / roaming',ambiguous:'Ownership unknown'}[value]||value)
const time=value=>value?new Date(value).toLocaleString():'—'
onMounted(async()=>{try{[nodes.value,groups.value]=await Promise.all([api('/nodes'),api('/node-groups')])}catch(e){error.value=e.message}await load()})
onActivated(()=>{timer=setInterval(()=>{if(scope.value.pending&&!loading.value)load()},10000)})
onDeactivated(()=>clearInterval(timer));onBeforeUnmount(()=>clearInterval(timer))
defineExpose({refresh:load})
</script>
<template><div class="connections">
  <p v-if="error" class="error-msg" role="alert">{{error}}</p><p v-if="message" class="success-msg" role="status">{{message}}</p>
  <div v-if="scope.configurationNeeded" class="scope-notice"><strong>Configure local network CIDRs</strong><p>Internet classification needs the LAN boundary in <router-link to="/admin">Administration → Server config</router-link>. No addresses are assumed to be Internet without it.</p></div>
  <div v-if="scope.pending" class="scope-notice" role="status">Updating retained observations for boundary revision {{scope.desiredRevision}}. {{scope.revision?'The previous completed revision stays visible until processing finishes.':'Initial indexing is in progress.'}}</div>
  <p v-if="!scope.configurationNeeded&&scope.missingFamilies?.length" class="hint">No {{scope.missingFamilies.map(f=>`IPv${f}`).join(' or ')}} local CIDRs configured. Eligible peers in that address family are outside the configured LAN.</p>
  <section class="metric-grid"><article v-for="[key,label] in [['events','EVENTS'],['peers','UNIQUE PEERS'],['allowed','ALLOWED OBSERVATIONS'],['blocked','BLOCKED ATTEMPTS']]" :key="key" class="metric glass"><div class="metric-top">{{label}}</div><strong>{{result.summary[key].toLocaleString()}}</strong><small>Matching current filters</small></article></section>
  <section class="panel glass internet-panel"><div class="panel-title"><h2>Internet connections</h2><div class="inline-actions"><label class="rows-label">Rows<select v-model.number="limit" @change="page=1;load()"><option :value="25">25</option><option :value="50">50</option><option :value="100">100</option></select></label><button class="button small secondary" :disabled="busy||!result.total" @click="exportRows">Export JSON</button></div></div>
    <p class="hint">Unicast peers outside configured local CIDRs, including private networks outside that boundary. Reverse DNS is a PTR name, not proof of the website visited. Allowed events do not prove a completed session.</p>
    <form class="internet-filters" @submit.prevent="apply"><label v-for="[key,label] in fields" :key="key">{{label}}<select v-if="choices[key]" v-model="draft[key]" :aria-label="label"><option v-for="[value,title] in choices[key]" :key="value" :value="value">{{title}}</option></select><input v-else v-model.trim="draft[key]" :aria-label="label" :type="['from','to'].includes(key)?'datetime-local':key==='port'?'number':'text'" :min="key==='port'?1:undefined" :max="key==='port'?65535:undefined"></label><div class="form-actions"><button class="button primary" :disabled="loading">Apply filters</button><button type="button" class="button secondary" @click="clear">Clear</button></div></form>
    <div class="table-wrap connection-scroll" tabindex="0" aria-label="Internet connection observations"><table><thead><tr><th v-for="[key,label] in columns" :key="key" :aria-sort="sort===key?(order==='asc'?'ascending':'descending'):undefined"><button class="table-sort" @click="sorting(key)">{{label}} {{sort===key?(order==='asc'?'↑':'↓'):'↕'}}</button></th><th>DNS evidence</th></tr></thead><tbody><tr v-for="row in result.items" :key="row.id" @click="open(row)"><td><button class="detail-link" @click.stop="open(row)">{{time(row.observed_at)}}</button></td><td>{{row.node_hostname||'Unknown reporter'}}<small>{{row.local_ip||'Ownership unknown'}}</small><small>{{attribution(row.attribution)}}</small></td><td class="peer-cell">{{row.peer_ip}}<small>{{row.ptrNames.join(', ')||'No reverse hostname'}}</small><small>{{row.category}} · PTR / reverse DNS{{row.dnsStale?' · stale':''}}</small></td><td>{{({in:'Inbound',out:'Outbound',unknown:'Unknown'})[row.direction]}}</td><td><span class="status" :class="row.action">{{row.observation}}</span></td><td>{{row.protocol||'—'}}</td><td>{{row.source_port??'—'}} → {{row.destination_port??'—'}}</td><td class="program-cell" :title="row.program">{{row.program||'—'}}</td><td><button class="button small secondary" @click.stop="showPeer(row)">{{row.dnsStale?'stale':row.dns_status||'pending'}}</button></td></tr><tr v-if="!result.items.length"><td colspan="9" class="empty-table">{{loading?'Loading…':scope.pending?'Indexing retained observations…':'No Internet connections match these filters.'}}</td></tr></tbody></table></div>
    <div class="internet-pagination"><span>{{result.total.toLocaleString()}} events · {{result.summary.peers.toLocaleString()}} unique peers · boundary {{scope.revision||'pending'}}</span><div><button class="button small secondary" :disabled="loading||page<=1" @click="move(page-1)">Previous</button><span>Page {{page}} / {{result.pages}}</span><button class="button small secondary" :disabled="loading||page>=result.pages" @click="move(page+1)">Next</button></div></div>
  </section>
  <TransactionDetailsDialog v-model="detailOpen" :transaction="detail" title="Internet transaction details" :can-allow="canManage&&detail?.ruleEligible" :can-deny="canManage&&detail?.ruleEligible" :can-ignore="canManage&&detail?.ignoreEligible" :busy="busy" @allow="begin('allow')" @deny="begin('block')" @ignore="begin('ignore')"><template #links><div v-if="detail" class="transaction-links"><router-link :to="detail.activitiesUrl">Original event in Activities</router-link><router-link :to="detail.mappingUrl">Reporting node in Mapping</router-link></div></template></TransactionDetailsDialog>
  <GlassWindow v-model="confirmOpen" :title="action==='ignore'?'Ignore like traffic':'Create firewall rule'" width="520px"><form class="form-grid" @submit.prevent="save"><p>{{action==='ignore'?'Matching firewall observations will be hidden by a traffic ignore rule.':`Create an IP-scoped ${action} rule from this firewall event. This does not create a browser-domain rule.`}}</p><label v-if="action!=='ignore'">Policy<select v-model="policyId"><option value="">Personal node policy</option><option v-for="policy in policies" :key="policy.id" :value="policy.id">{{policy.name}}</option></select></label><p v-if="error" class="error-msg" role="alert">{{error}}</p><div class="form-actions"><button type="button" class="button secondary" @click="confirmOpen=false">Cancel</button><button class="button primary" :disabled="busy">{{busy?'Saving…':'Save'}}</button></div></form></GlassWindow>
  <GlassWindow v-model="peerOpen" title="Reverse-DNS evidence" width="680px"><div v-if="peer" class="peer-details"><strong>{{peer.ip}}</strong><p>{{peer.names.join(', ')||'No PTR hostname'}}{{peer.stale?' · stale':''}}</p><p>Source: reverse DNS · Resolver: {{peer.resolver_context}} · Status: {{peer.status}}</p><p>Last check: {{time(peer.checked_at)}} · Next refresh: {{time(peer.next_lookup_at)}}</p><p class="hint">Application cache policy: {{peer.cachePolicy.positiveHours}} hours for successful answers, {{peer.cachePolicy.negativeHours}} hours for missing answers. These are not authoritative DNS TTLs. PTR names do not identify a requested website.</p><p v-if="error" class="error-msg">{{error}}</p><button v-if="canResolve" class="button secondary" :disabled="busy" @click="resolve">Queue DNS refresh</button><div class="table-wrap"><table><thead><tr><th>Checked</th><th>Status</th><th>PTR answers</th></tr></thead><tbody><tr v-for="(entry,index) in peer.history" :key="index"><td>{{time(entry.checked_at)}}</td><td>{{entry.status}} {{entry.error||''}}</td><td>{{entry.names.join(', ')||'—'}}</td></tr></tbody></table></div></div></GlassWindow>
</div></template>
<style scoped src="./internet.css"></style>
<style scoped>
.connections{display:grid;gap:1rem;min-width:0}.connections .metric-grid{margin:0}.scope-notice{padding:1rem;border:1px solid var(--border);border-radius:6px;color:var(--field-value);background:var(--panel)}.scope-notice p{margin:.5rem 0 0}.rows-label{display:flex;align-items:center;gap:.5rem;font-size:.75rem}.rows-label select{width:auto}.connection-scroll{overflow:auto;max-height:65vh;max-width:100%;min-width:0}.connection-scroll thead{position:sticky;top:0;z-index:1;background:var(--panel)}.connection-scroll th{white-space:normal}.connection-scroll .table-sort{white-space:normal;text-align:left}.connection-scroll th:nth-child(2){width:200px}.connection-scroll table{min-width:1450px;table-layout:fixed}.connection-scroll th:nth-child(3){width:270px}.connection-scroll th:nth-child(8){width:240px}.connection-scroll td{white-space:normal;overflow-wrap:anywhere;vertical-align:top}.connection-scroll td small{display:block;color:var(--muted);margin-top:.3rem}.connection-scroll tbody tr{cursor:pointer}.connection-scroll tbody tr:hover{background:color-mix(in srgb,var(--accent,#3864ae) 6%,transparent)}.detail-link{border:0;background:transparent;font:inherit;color:inherit;padding:0;text-align:left;cursor:pointer}.peer-details{display:grid;gap:.7rem;min-width:0;overflow-wrap:anywhere}.peer-details p{margin:0}.transaction-links{display:flex;gap:1rem;flex-wrap:wrap}.internet-filters{grid-template-columns:repeat(auto-fit,minmax(min(100%,180px),1fr))}
</style>
