<script setup>
import {ref,watch} from 'vue'
import {api} from '../../services/api.js'
import GlassWindow from '../GlassWindow.vue'
const props=defineProps({modelValue:Boolean,id:String,kind:{type:String,default:'usage'}}),emit=defineEmits(['update:modelValue'])
const record=ref(null),error=ref('');let sequence=0
watch(()=>[props.modelValue,props.id,props.kind],async()=>{if(!props.modelValue||!props.id)return;const current=++sequence;record.value=null;error.value='';try{const data=await api(`/ai/${props.kind}/${encodeURIComponent(props.id)}`);if(current===sequence)record.value=data}catch(e){if(current===sequence)error.value=e.message}},{immediate:true})
const fields=[['node_hostname','Node'],['actor_email','Actor'],['reporter_name','Reporter'],['coverage','Coverage'],['operation','Operation'],['tool','Tool'],['provider','Provider'],['model','Requested model'],['response_model','Response model'],['hostname','Service hostname'],['peer_ip','Peer IP'],['outcome','Outcome'],['action','Network action'],['category','Evidence category'],['confidence','Confidence'],['started_at','Started'],['ended_at','Ended'],['observed_at','Observed'],['duration_ms','Duration (ms)'],['input_tokens','Input tokens'],['output_tokens','Output tokens'],['cost_amount','Reported cost'],['currency','Currency'],['cost_source','Cost source'],['process_id','PID'],['process_guid','Process GUID'],['process_started_at','Process started'],['session_id','Session'],['trace_id','Trace'],['span_id','Span'],['parent_span_id','Parent span'],['request_id','Request'],['error_code','Error code'],['adapter_version','Adapter']]
</script>
<template><GlassWindow @keydown.stop :model-value="modelValue" title="AI activity details" width="780px" @update:model-value="emit('update:modelValue',$event)"><div class="ai-details"><p v-if="error" class="error-msg" role="alert">{{error}}</p><p v-else-if="!record" role="status">Loading details…</p><template v-else><p class="ai-note">{{kind==='usage'?'Reporter-supplied metadata. Missing identity and metrics remain unknown.':'An observed or suspected service connection is not proof of a completed model operation.'}}</p><dl><template v-for="[key,label] in fields" :key="key"><template v-if="record[key]!=null||['node_hostname','actor_email'].includes(key)"><dt>{{label}}</dt><dd>{{record[key]??'Unknown'}}</dd></template></template></dl><p v-if="record.sourceExpired" class="ai-note">The original transaction has expired; retained classification evidence remains below.</p><router-link v-if="record.sourceUrl&&!record.sourceExpired" :to="record.sourceUrl">Open original transaction</router-link><template v-if="Array.isArray(record.evidence)"><h3>Associated traffic</h3><p v-if="!record.evidence.length" class="ai-note">No matching traffic evidence. Local or unobserved usage is still recorded.</p><article v-for="e in record.evidence" :key="e.id" class="ai-card"><strong>{{e.hostname||e.peer_ip||'Unknown destination'}}</strong><p>{{e.association}} · {{e.reason}}</p><p>{{e.category}} · {{e.confidence}} confidence</p><router-link v-if="!e.sourceExpired" :to="e.sourceUrl">Original transaction</router-link><details><summary>Classification evidence</summary><pre>{{JSON.stringify(e.evidence,null,2)}}</pre></details></article></template><template v-else><h3>Classification evidence</h3><pre>{{JSON.stringify(record.evidence,null,2)}}</pre><h3>Candidate / linked operations</h3><p v-if="!record.activities?.length" class="ai-note">No reported operation has been associated.</p><p v-for="a in record.activities" :key="a.usage_id"><router-link :to="{path:'/ai-usage',query:{tab:'usage',detail:a.usage_id}}">{{a.association}}</router-link> · {{a.reason}}</p></template><details v-if="record.receipts"><summary>Durable receipts ({{record.receipts.length}})</summary><pre>{{JSON.stringify(record.receipts,null,2)}}</pre></details><p class="ai-note">Review original transactions and policy scope before creating an enforcement rule.</p></template></div></GlassWindow></template>
<style scoped src="./ai.css"></style>
