<script setup>
import {ref,computed,onMounted,onUnmounted} from 'vue'
import {api,session,download} from '../services/api.js'
import GlassWindow from './GlassWindow.vue'
import CloudSourceHistory from './CloudSourceHistory.vue'
const canEdit=computed(()=>['owner','admin'].includes(session.user?.role))
const connections=ref([]),scopes=ref([]),credentials=ref([]),resources=ref({items:[],total:0}),runs=ref({items:[],total:0}),conflicts=ref({items:[],total:0})
const error=ref(''),loadError=ref(''),loading=ref(false),connectionReady=ref(false),message=ref(''),busy=ref(false),tab=ref('connections'),dialog=ref(''),selected=ref(null),runDetail=ref(null)
const query=ref({q:'',state:'all',scopeId:'',connectionId:'',sort:'updated',direction:'desc',page:1,pageSize:25}),runPage=ref(1),conflictPage=ref(1),conflictState=ref('open')
const connectionForm=ref({}),scopeForm=ref({}),resolution=ref({action:'link',nodeId:'',reason:''})
const params=()=>new URLSearchParams(Object.fromEntries(Object.entries(query.value).filter(([,v])=>v!==''))).toString()
const list=value=>String(value||'').split(/[\n,]/).map(v=>v.trim()).filter(Boolean)
const when=value=>value?new Date(value).toLocaleString():'—'
let timer
async function load(){
  if(loading.value)return;loading.value=true
  try{
    const results=await Promise.allSettled([api('/discovery/azure/connections'),api('/inventory/scopes'),api('/credentials').then(rows=>rows.filter(c=>c.type==='azure')),api('/discovery/azure/resources?'+params()),api('/discovery/azure/runs?pageSize=25&page='+runPage.value),api('/inventory/conflicts?pageSize=25&page='+conflictPage.value+'&conflictState='+conflictState.value)])
    const refs=[connections,scopes,credentials,resources,runs,conflicts]
    const labels=['Connections','Network scopes','Credential vault','Resources','Run history','Identity conflicts']
    const failures=[]
    results.forEach((r,i)=>{
      if(r.status==='fulfilled')refs[i].value=r.value
      else failures.push(r.reason.status===404
        ? `${labels[i]}: this API endpoint is unavailable. Restart the WinFire API with the current application version, then refresh.`
        : `${labels[i]}: ${r.reason.message}`)
    })
    connectionReady.value=results.slice(0,3).every(r=>r.status==='fulfilled')
    loadError.value=failures.join(' ')
    if(runDetail.value)runDetail.value=await api('/discovery/azure/runs/'+runDetail.value.id)
  }catch(e){loadError.value=e.message}finally{loading.value=false}
}
async function act(fn){if(busy.value)return;busy.value=true;error.value='';message.value='';try{await fn();await load()}catch(e){error.value=e.message}finally{busy.value=false}}
function editConnection(c){if(!connectionReady.value)return;error.value='';selected.value=c;connectionForm.value=c?{...c,subscriptionsText:c.subscriptions.join('\n'),groupsText:c.resourceGroups.join('\n'),tagsText:JSON.stringify(c.tags,null,2),networkScopesText:JSON.stringify(c.networkScopes,null,2)}:{name:'',credentialId:'',subscriptionsText:'',groupsText:'',scopeId:'default',tagsText:'{}',networkScopesText:'[]',enabled:false,intervalMinutes:60};dialog.value='connection'}
async function saveConnection(){await act(async()=>{const f=connectionForm.value;await api('/discovery/azure/connections'+(selected.value?'/'+selected.value.id:''),{method:selected.value?'PUT':'POST',body:{name:f.name,credentialId:f.credentialId,subscriptions:list(f.subscriptionsText),resourceGroups:list(f.groupsText),scopeId:f.scopeId,tags:JSON.parse(f.tagsText),networkScopes:JSON.parse(f.networkScopesText),enabled:f.enabled,intervalMinutes:Number(f.intervalMinutes)}});dialog.value='';message.value='Connection saved. Test access, then preview the scope before syncing.'})}
function editScope(s){error.value='';selected.value=s;scopeForm.value={name:s?.name||'',kind:s?.kind||'azure-vnet',cidrsText:s?.cidrs?.join('\n')||'',directManagement:s?.directManagement||false};dialog.value='scope'}
async function saveScope(){await act(async()=>{const f=scopeForm.value;await api('/inventory/scopes'+(selected.value?'/'+selected.value.id:''),{method:selected.value?'PUT':'POST',body:{name:f.name,kind:f.kind,cidrs:list(f.cidrsText),directManagement:f.directManagement}});dialog.value='';message.value='Scope saved.'})}
async function start(c,action){await act(async()=>{runDetail.value=await api(`/discovery/azure/connections/${c.id}/${action}`,{method:'POST',body:{}});dialog.value='run'})}
function review(c){error.value='';selected.value=c;resolution.value={action:'link',nodeId:c.candidates[0]?.nodeId||'',reason:''};dialog.value='conflict'}
async function resolve(){await act(async()=>{await api(selected.value.sourceReview?`/discovery/azure/resources/${selected.value.id}/resolve`:`/inventory/conflicts/${selected.value.id}/resolve`,{method:'POST',body:resolution.value});dialog.value='';message.value='Identity decision saved with history.'})}
function filter(){query.value.page=1;load()}
function sort(key){query.value.direction=query.value.sort===key&&query.value.direction==='asc'?'desc':'asc';query.value.sort=key;filter()}
function reviewSource(r){review({...r,sourceReview:true,reason:'Review the source binding. Changing this link preserves both nodes and their policies.',candidates:r.node_id?[{nodeId:r.node_id,reason:'Current binding'}]:[]})}
function showRun(r){runDetail.value=r;dialog.value='run'}
onMounted(()=>{load();timer=setInterval(()=>{if(runs.value.items.some(r=>['queued','running'].includes(r.status)))load()},3000)})
onUnmounted(()=>clearInterval(timer))
</script>
<template>
  <section class="azure-discovery">
    <p class="muted">Import Azure VMs and existing Azure Arc servers. Choose an explicit network scope to keep overlapping private networks separate. Cloud observations do not verify host management or enable firewall enforcement.</p>
    <div v-if="loadError" class="error-msg" role="alert">{{loadError}}</div><div v-if="error&&!dialog" class="error-msg" role="alert">{{error}}</div><div v-if="message" class="success-msg" role="status">{{message}}</div>
    <nav class="azure-tabs" role="tablist" aria-label="Azure discovery"><button v-for="t in ['connections','resources','runs','conflicts','scopes']" :key="t" type="button" role="tab" :aria-selected="tab===t" :class="{active:tab===t}" @click="tab=t">{{t==='runs'?'Run history':t[0].toUpperCase()+t.slice(1)}}</button></nav>
    <div class="toolbar"><button class="button secondary" :disabled="busy||loading" @click="load">{{loading?'Loading…':'Refresh'}}</button><button v-if="canEdit&&tab==='connections'" class="button primary" :disabled="loading||!connectionReady" @click="editConnection(null)">Add connection</button><button v-if="canEdit&&tab==='scopes'" class="button primary" @click="editScope(null)">Add network scope</button><a v-if="canEdit" class="button secondary" href="/admin?tab=credentials">Open Credential Vault</a></div>
    <div v-if="tab==='connections'" class="table-wrap"><table><thead><tr><th>Connection</th><th>Network scope</th><th>Schedule</th><th>Last run</th><th>Actions</th></tr></thead><tbody><tr v-for="c in connections" :key="c.id"><td>{{c.name}}<small>{{c.subscriptions.length}} subscription(s)</small></td><td>{{scopes.find(s=>s.id===c.scopeId)?.name}}</td><td>{{c.enabled?'Every '+c.intervalMinutes+' min':'Paused'}}<small>{{when(c.nextRunAt)}}</small></td><td>{{c.lastStatus||'Not tested'}}<small>{{c.lastError}}</small></td><td><div v-if="canEdit" class="actions"><button class="button secondary" @click="editConnection(c)">Edit</button><button v-for="action in ['test','preview','sync']" :key="action" class="button secondary" :disabled="busy" @click="start(c,action)">{{action==='sync'?'Sync now':action==='test'?'Test access':'Preview'}}</button><button class="button danger" @click="selected=c;dialog='delete'">Delete</button></div></td></tr><tr v-if="!connections.length"><td colspan="5">{{loading?'Loading connections…':!connectionReady?'Connections could not be loaded. Use Refresh to retry.':'Add an Azure credential in the credential vault, then create a connection.'}}</td></tr></tbody></table></div>
    <template v-if="tab==='resources'">
      <form class="toolbar" @submit.prevent="filter"><input v-model="query.q" aria-label="Search cloud resources" placeholder="Search name or resource ID"><select v-model="query.state" aria-label="Resource state" @change="filter"><option v-for="state in ['all','linked','candidate','conflict','out-of-scope','missing','retired','ignored']" :key="state">{{state}}</option></select><select v-model="query.scopeId" aria-label="Network scope" @change="filter"><option value="">All scopes</option><option v-for="s in scopes" :key="s.id" :value="s.id">{{s.name}}</option></select><select v-model="query.connectionId" aria-label="Connection" @change="filter"><option value="">All connections</option><option v-for="c in connections" :key="c.id" :value="c.id">{{c.name}}</option></select><button class="button secondary">Search</button><button type="button" class="button secondary" @click="act(()=>download('/discovery/azure/resources/export?'+params(),'azure-resources.json'))">Export</button></form>
      <div class="table-wrap"><table><thead><tr><th><button class="sort" @click="sort('name')">Resource ↕</button></th><th>OS / version</th><th>Addresses</th><th><button class="sort" @click="sort('state')">State ↕</button></th><th><button class="sort" @click="sort('updated')">Fetched ↕</button></th><th>Details</th></tr></thead><tbody><tr v-for="r in resources.items" :key="r.id"><td>{{r.evidence.name}}<small>{{r.provider}} · {{r.evidence.location||'Unknown location'}}</small></td><td class="os"><span>{{r.evidence.osName||'Unknown OS'}}</span><small>{{r.evidence.osVersion||'Version unavailable'}}</small></td><td>{{r.evidence.addresses.join(', ')||'No address reported'}}</td><td>{{r.state}}</td><td>{{when(r.fetched_at)}}</td><td><button class="button secondary" @click="selected=r;dialog='resource'">View details</button></td></tr><tr v-if="!resources.items.length"><td colspan="6">No resources match these filters.</td></tr></tbody></table></div>
      <div class="toolbar"><span>{{resources.total}} resources · page {{query.page}}</span><label>Rows<select v-model.number="query.pageSize" @change="filter"><option :value="25">25</option><option :value="50">50</option><option :value="100">100</option></select></label><button class="button secondary" :disabled="query.page===1" @click="query.page--;load()">Previous</button><button class="button secondary" :disabled="query.page*query.pageSize>=resources.total" @click="query.page++;load()">Next</button></div>
    </template>
    <template v-if="tab==='runs'"><div class="table-wrap"><table><thead><tr><th>Started</th><th>Action</th><th>Status</th><th>Resources / diff</th><th>Actions</th></tr></thead><tbody><tr v-for="r in runs.items" :key="r.id"><td>{{when(r.created_at)}}</td><td>{{r.kind}}</td><td>{{r.status}}<small>{{r.error}}</small></td><td>{{r.result.records||0}}<small v-if="r.result.diff">{{r.result.diff.new}} new · {{r.result.diff.changed}} changed · {{r.result.diff.missing}} missing · {{r.result.diff.conflict}} conflicts</small></td><td><button class="button secondary" @click="showRun(r)">View run</button></td></tr><tr v-if="!runs.items.length"><td colspan="5">No runs yet.</td></tr></tbody></table></div><div class="toolbar"><span>{{runs.total}} runs · page {{runPage}}</span><button class="button secondary" :disabled="runPage===1" @click="runPage--;load()">Previous</button><button class="button secondary" :disabled="runPage*25>=runs.total" @click="runPage++;load()">Next</button></div></template>
    <template v-if="tab==='conflicts'"><label>Review state<select v-model="conflictState" @change="conflictPage=1;load()"><option value="open">Open</option><option value="resolved">Resolved</option><option value="all">All</option></select></label><p class="muted">Review weak or contradictory identity matches before linking records. Decisions retain the previous link for review and reversal.</p><div class="table-wrap"><table><thead><tr><th>Resource</th><th>Reason</th><th>Actions</th></tr></thead><tbody><tr v-for="c in conflicts.items" :key="c.id"><td class="resource-id">{{c.resource_id}}</td><td>{{c.reason}}</td><td><button v-if="canEdit" class="button secondary" @click="review(c)">Review</button></td></tr><tr v-if="!conflicts.items.length"><td colspan="3">No unresolved identity conflicts.</td></tr></tbody></table></div><div class="toolbar"><span>{{conflicts.total}} conflicts · page {{conflictPage}}</span><button class="button secondary" :disabled="conflictPage===1" @click="conflictPage--;load()">Previous</button><button class="button secondary" :disabled="conflictPage*25>=conflicts.total" @click="conflictPage++;load()">Next</button></div></template>
    <div v-if="tab==='scopes'" class="table-wrap"><table><thead><tr><th>Scope</th><th>Owned CIDRs</th><th>Management path</th><th>Actions</th></tr></thead><tbody><tr v-for="s in scopes" :key="s.id"><td>{{s.name}}</td><td><small v-for="cidr in s.cidrs" :key="cidr">{{cidr}}</small><span v-if="!s.cidrs.length">No cloud import allowed</span></td><td>{{s.directManagement?'Direct management approved':'Inventory only'}}</td><td><button v-if="canEdit&&s.id!=='default'" class="button secondary" @click="editScope(s)">Edit</button><span v-else-if="s.id==='default'" class="muted">CIDRs in Server config</span></td></tr></tbody></table></div>

    <GlassWindow :model-value="!!dialog" :title="dialog==='connection'?'Azure connection':dialog==='scope'?'Network scope':dialog==='run'?'Discovery run':dialog==='conflict'?'Review identity match':dialog==='delete'?'Delete connection':'Cloud resource details'" width="760px" @update:model-value="v=>{if(!v){dialog=''}}">
      <p v-if="error" class="error-msg" role="alert">{{error}}</p>
      <form v-if="dialog==='connection'" class="azure-form" @submit.prevent="saveConnection"><label>Connection name<input v-model.trim="connectionForm.name" required maxlength="180"></label><label>Azure credential<select v-model="connectionForm.credentialId" required><option value="">Select credential</option><option v-for="c in credentials" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label>Subscription IDs (one per line)<textarea v-model="connectionForm.subscriptionsText" required rows="3"></textarea></label><label>Resource groups (optional, one per line)<textarea v-model="connectionForm.groupsText" rows="3"></textarea><small>Empty selects the entire subscriptions. Reader access must cover every selected scope.</small></label><label>Inventory network scope<select v-model="connectionForm.scopeId" required><option v-for="s in scopes" :key="s.id" :value="s.id">{{s.name}}</option></select></label><label>Run every (minutes)<input v-model.number="connectionForm.intervalMinutes" type="number" min="5" max="10080" required></label><label class="wide switch-row">Scheduled sync<button type="button" role="switch" :aria-checked="connectionForm.enabled" :class="['azure-switch',{on:connectionForm.enabled}]" @click="connectionForm.enabled=!connectionForm.enabled"><span></span></button></label><details class="wide"><summary>Advanced scope mappings and tag filters</summary><label>Tag filter (JSON object)<textarea v-model="connectionForm.tagsText" rows="3"></textarea></label><label>VNet scope mappings (JSON array)<textarea v-model="connectionForm.networkScopesText" rows="3" placeholder='[{"networkId":"/subscriptions/…/virtualNetworks/vnet","scopeId":"…"}]'></textarea></label></details><div class="form-actions wide"><button type="button" class="button secondary" @click="dialog=''">Cancel</button><button class="button primary" :disabled="busy||loading||!connectionReady">Save connection</button></div></form>

      <form v-if="dialog==='scope'" class="azure-form" @submit.prevent="saveScope"><label>Name<input v-model.trim="scopeForm.name" required></label><label>Kind<select v-model="scopeForm.kind"><option value="azure-vnet">Azure VNet</option><option value="site">Site</option></select></label><label class="wide">Owned CIDRs (one per line)<textarea v-model="scopeForm.cidrsText" rows="4" required></textarea></label><label class="wide switch-row">Direct management path has been verified<button type="button" role="switch" :aria-checked="scopeForm.directManagement" :class="['azure-switch',{on:scopeForm.directManagement}]" @click="scopeForm.directManagement=!scopeForm.directManagement"><span></span></button></label><p class="muted wide">Enable direct management only when this API server routes to this scope without an overlapping address ambiguity. Importing Azure resources never adds CIDRs automatically.</p><div class="form-actions wide"><button type="button" class="button secondary" @click="dialog=''">Cancel</button><button class="button primary" :disabled="busy">Save scope</button></div></form>
      <template v-if="dialog==='run'&&runDetail"><p>{{runDetail.kind}} · {{runDetail.status}} · {{when(runDetail.created_at)}}</p><p v-if="runDetail.error" class="error-msg">{{runDetail.error}}</p><p v-if="runDetail.result.preview" class="muted">Preview shows up to {{runDetail.result.previewLimit}} of {{runDetail.result.records}} resources. No assets are written by preview.</p><pre class="detail-json">{{JSON.stringify(runDetail.result,null,2)}}</pre><button v-if="canEdit&&['queued','running'].includes(runDetail.status)" class="button danger" @click="act(async()=>{runDetail=await api('/discovery/azure/runs/'+runDetail.id+'/cancel',{method:'POST'})})">Cancel run</button></template>
      <form v-if="dialog==='conflict'" class="azure-form" @submit.prevent="resolve"><p class="wide">{{selected.reason}}</p><label>Decision<select v-model="resolution.action"><option value="link">Link to verified asset</option><option value="unlink">Unlink and hold for review</option><option value="ignore">Ignore source</option><option value="reopen">Reopen automatic review</option></select></label><label v-if="resolution.action==='link'">Node ID<input v-model="resolution.nodeId" required list="cloud-candidates"><datalist id="cloud-candidates"><option v-for="c in selected.candidates" :key="c.nodeId" :value="c.nodeId">{{c.reason}}</option></datalist></label><label class="wide">Reason<textarea v-model.trim="resolution.reason" required maxlength="1000" rows="3"></textarea></label><div class="form-actions wide"><button type="button" class="button secondary" @click="dialog=''">Cancel</button><button class="button primary" :disabled="busy">Save decision</button></div></form>
      <template v-if="dialog==='resource'"><p>{{selected.state}} · Fetched {{when(selected.fetched_at)}}</p><button v-if="canEdit" class="button secondary" @click="reviewSource(selected)">Review binding</button><CloudSourceHistory :source-id="selected.id"/><pre class="detail-json">{{JSON.stringify(selected.evidence,null,2)}}</pre><a v-if="selected.node_id" :href="'/inventory?node='+selected.node_id">Open linked asset</a></template>
      <template v-if="dialog==='delete'"><p>Delete “{{selected.name}}”? Existing inventory and source history are retained. Cancel active runs first.</p><div class="form-actions"><button class="button secondary" @click="dialog=''">Cancel</button><button class="button danger" :disabled="busy" @click="act(async()=>{await api('/discovery/azure/connections/'+selected.id,{method:'DELETE'});dialog=''})">Delete connection</button></div></template>
    </GlassWindow>
  </section>
</template>
<style scoped>
.azure-discovery{min-width:0}.azure-tabs{display:flex;flex-wrap:wrap;border-bottom:1px solid var(--border);margin:1rem 0}.azure-tabs button{border:0;border-bottom:2px solid transparent;background:transparent;color:var(--muted);padding:12px 16px;font:inherit;font-weight:600;cursor:pointer}.azure-tabs button.active{color:var(--field-value);border-bottom-color:var(--accent);background:color-mix(in srgb,var(--accent) 8%,transparent)}.toolbar,.actions{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.toolbar{margin:14px 0}.toolbar input{min-width:180px;flex:1}.toolbar label{display:flex;gap:8px;align-items:center}.table-wrap{max-width:100%;overflow:auto}table{width:100%;min-width:640px}td{vertical-align:top}small{display:block;color:var(--muted);margin-top:4px}.os{max-width:50ch}.os>*{display:block;max-width:50ch;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.resource-id{max-width:50ch;overflow-wrap:anywhere}.sort{border:0;background:transparent;color:inherit;font:inherit;cursor:pointer}.azure-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.azure-form label{display:grid;gap:6px;min-width:0}.azure-form input,.azure-form select,.azure-form textarea{width:100%;min-width:0}.wide{grid-column:1/-1}.azure-form .switch-row{display:flex;justify-content:space-between;align-items:center}.azure-switch{width:40px;height:22px;border:1px solid var(--border);border-radius:12px;background:var(--muted);padding:2px;cursor:pointer}.azure-switch span{display:block;width:16px;height:16px;border-radius:50%;background:#fff;transition:transform .15s}.azure-switch.on{background:var(--accent)}.azure-switch.on span{transform:translateX(17px)}.detail-json{max-height:55vh;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;background:var(--panel);padding:12px}.form-actions{justify-content:flex-end}.azure-form details label{margin-top:12px}@media(max-width:600px){.azure-form{grid-template-columns:minmax(0,1fr)}.azure-tabs button{padding:10px}.toolbar>*{max-width:100%}}
</style>
