<script setup>
import {ref,onMounted} from 'vue'
import {api} from '../services/api.js'
const result=ref({items:[],total:0,summary:{}}),q=ref(''),gap=ref(''),page=ref(1),error=ref(''),busy=ref(false)
const names=['discovery','authentication','facts','firewallRead','firewallWrite','policyReadback','events','verification']
const label=n=>n.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase())
async function load(){busy.value=true;error.value='';try{result.value=await api('/reports/capabilities?'+new URLSearchParams({q:q.value,gap:gap.value,page:page.value,pageSize:25}))}catch(e){error.value=e.message}finally{busy.value=false}}
function filter(){page.value=1;load()}
onMounted(load)
</script>
<template><section><p class="muted">Capability evidence is separate from reachability. Unsupported operations are excluded from each capability’s denominator. A successful read or write records what happened; it does not establish continuous coverage.</p><p v-if="error" class="error-msg">{{error}}</p><form class="coverage-toolbar" @submit.prevent="filter"><input v-model="q" aria-label="Search capability coverage" placeholder="Search host, address or OS"><select v-model="gap" aria-label="Coverage gap" @change="filter"><option value="">All coverage</option><option v-for="n in names" :key="n" :value="n">{{label(n)}} gap</option></select><button class="button secondary" :disabled="busy">Search</button></form><p>{{result.eligibleDenominator||0}} eligible assets · {{result.excluded||0}} excluded by network scope · {{result.total}} matching assets</p><div class="table-wrap"><table><thead><tr><th>Asset</th><th>Transport</th><th v-for="n in names" :key="n">{{label(n)}}<small v-if="result.summary[n]">{{result.summary[n].fresh}} / {{result.summary[n].supported}} fresh</small></th></tr></thead><tbody><tr v-for="r in result.items" :key="r.nodeId"><td><a :href="'/inventory?node='+r.nodeId">{{r.hostname}}</a><small>{{r.address}}</small></td><td>{{r.transport}}<small v-if="r.cloudObservationOnly">Cloud observation only</small></td><td v-for="n in names" :key="n"><span :class="['status',r.capabilities[n].state==='fresh'?'reachable':r.capabilities[n].state==='failed'?'unreachable':'pending']" :title="'Last success: '+(r.capabilities[n].lastSuccessAt||'none')+'; freshness: '+r.capabilities[n].thresholdHours+' hours'">{{r.capabilities[n].state}}</span></td></tr><tr v-if="!result.items.length"><td colspan="10">{{busy?'Loading…':'No assets match.'}}</td></tr></tbody></table></div><div class="coverage-toolbar"><span>Page {{page}} · 25 rows per page</span><button class="button secondary" :disabled="page===1||busy" @click="page--;load()">Previous</button><button class="button secondary" :disabled="page*25>=result.total||busy" @click="page++;load()">Next</button></div></section></template>
<style scoped>.coverage-toolbar{display:flex;flex-wrap:wrap;gap:10px;align-items:center;margin:16px 0}.coverage-toolbar input{flex:1;min-width:180px}.table-wrap{max-width:100%;overflow:auto}table{min-width:1100px;width:100%}small{display:block;margin-top:5px;color:var(--muted)}</style>
