<script setup>
import {computed,onMounted,ref} from 'vue'
import GlassWindow from './GlassWindow.vue'
import {api} from '../services/api.js'

const activeTab=ref('ports')
const rows=ref([]),total=ref(0),page=ref(1),pages=ref(1),loading=ref(false),error=ref(''),message=ref('')
const search=ref(''),protocol=ref(''),source=ref(''),enabled=ref(''),sortBy=ref('port'),sortDir=ref('asc')
const dialogOpen=ref(false),confirmOpen=ref(false),confirmChecked=ref(false),target=ref(null),busy=ref(false)
const draft=ref({protocol:'TCP',portStart:null,portEnd:null,service:'',description:'',priority:10,enabled:true})
const editing=computed(()=>!!target.value)
const noPortProtocol=computed(()=>['ICMP','ICMPv6','IGMP'].includes(draft.value.protocol))

const processRows=ref([]),processTotal=ref(0),processPage=ref(1),processPages=ref(1),processLoading=ref(false)
const processSearch=ref(''),processSource=ref(''),processEnabled=ref(''),processSortBy=ref('priority'),processSortDir=ref('asc')
const processDialogOpen=ref(false),processConfirmOpen=ref(false),processConfirmChecked=ref(false),processTarget=ref(null),processBusy=ref(false)
const processDraft=ref({executablePattern:'',service:'',description:'',priority:10,enabled:true})
const processEditing=computed(()=>!!processTarget.value)

function query(){
  const params={search:search.value,protocol:protocol.value,source:source.value,enabled:enabled.value,page:page.value,pageSize:100,sortBy:sortBy.value,sortDir:sortDir.value}
  return new URLSearchParams(Object.entries(params).filter(([,value])=>value!==''&&value!==null)).toString()
}
async function load(){loading.value=true;error.value='';try{const result=await api(`/settings/classifier?${query()}`);rows.value=result.items;total.value=result.total;page.value=result.page;pages.value=result.totalPages}catch(cause){error.value=cause.message}finally{loading.value=false}}
function searchRows(){page.value=1;load()}
function sort(column){if(sortBy.value===column)sortDir.value=sortDir.value==='asc'?'desc':'asc';else{sortBy.value=column;sortDir.value='asc'};searchRows()}
function move(next){if(next<1||next>pages.value)return;page.value=next;load()}
function portLabel(rule){if(rule.portStart===null||rule.portStart===undefined)return 'Any port';return rule.portStart===rule.portEnd?String(rule.portStart):`${rule.portStart}-${rule.portEnd}`}
function openNew(){target.value=null;draft.value={protocol:'TCP',portStart:null,portEnd:null,service:'',description:'',priority:10,enabled:true};dialogOpen.value=true}
function openEdit(rule){target.value=rule;draft.value={protocol:rule.protocol,portStart:rule.portStart,portEnd:rule.portEnd,service:rule.service,description:rule.description||'',priority:rule.priority,enabled:rule.enabled};dialogOpen.value=true}
function normalizeDraft(){const value={...draft.value};if(noPortProtocol.value){value.portStart=null;value.portEnd=null}else{value.portStart=value.portStart?Number(value.portStart):null;value.portEnd=value.portEnd?Number(value.portEnd):null}value.priority=Number(value.priority);return value}
async function save(){busy.value=true;error.value='';message.value='';try{const value=normalizeDraft();if(editing.value)await api(`/settings/classifier/rules/${target.value.id}`,{method:'PATCH',body:value});else await api('/settings/classifier/rules',{method:'POST',body:value});dialogOpen.value=false;message.value=editing.value?'Classifier rule updated':'Classifier rule added';await load()}catch(cause){error.value=cause.message}finally{busy.value=false}}
function askDelete(rule){target.value=rule;confirmChecked.value=false;confirmOpen.value=true}
async function remove(){if(!target.value||!confirmChecked.value)return;busy.value=true;error.value='';try{await api(`/settings/classifier/rules/${target.value.id}`,{method:'DELETE'});confirmOpen.value=false;message.value=target.value.source==='custom'?'Classifier override removed':'Classifier rule disabled';target.value=null;await load()}catch(cause){error.value=cause.message}finally{busy.value=false}}

function processQuery(){
  const params={search:processSearch.value,source:processSource.value,enabled:processEnabled.value,page:processPage.value,pageSize:100,sortBy:processSortBy.value,sortDir:processSortDir.value}
  return new URLSearchParams(Object.entries(params).filter(([,value])=>value!==''&&value!==null)).toString()
}
async function loadProcess(){processLoading.value=true;error.value='';try{const result=await api(`/settings/classifier/process-rules?${processQuery()}`);processRows.value=result.items;processTotal.value=result.total;processPage.value=result.page;processPages.value=result.totalPages}catch(cause){error.value=cause.message}finally{processLoading.value=false}}
function searchProcess(){processPage.value=1;loadProcess()}
function sortProcess(column){if(processSortBy.value===column)processSortDir.value=processSortDir.value==='asc'?'desc':'asc';else{processSortBy.value=column;processSortDir.value='asc'};searchProcess()}
function moveProcess(next){if(next<1||next>processPages.value)return;processPage.value=next;loadProcess()}
function openProcessNew(){processTarget.value=null;processDraft.value={executablePattern:'',service:'',description:'',priority:10,enabled:true};processDialogOpen.value=true}
function openProcessEdit(rule){processTarget.value=rule;processDraft.value={executablePattern:rule.executablePattern,service:rule.service,description:rule.description||'',priority:rule.priority,enabled:rule.enabled};processDialogOpen.value=true}
async function saveProcess(){processBusy.value=true;error.value='';message.value='';try{const value={...processDraft.value,priority:Number(processDraft.value.priority)};if(processEditing.value)await api(`/settings/classifier/process-rules/${processTarget.value.id}`,{method:'PATCH',body:value});else await api('/settings/classifier/process-rules',{method:'POST',body:value});processDialogOpen.value=false;message.value=processEditing.value?'Process classifier rule updated':'Process classifier rule added';await loadProcess()}catch(cause){error.value=cause.message}finally{processBusy.value=false}}
function askProcessToggle(rule){processTarget.value=rule;processConfirmChecked.value=false;processConfirmOpen.value=true}
async function toggleProcess(){if(!processTarget.value||!processConfirmChecked.value)return;processBusy.value=true;error.value='';try{const rule=processTarget.value;await api(`/settings/classifier/process-rules/${rule.id}`,{method:'PATCH',body:{executablePattern:rule.executablePattern,service:rule.service,description:rule.description||'',priority:rule.priority,enabled:!rule.enabled}});processConfirmOpen.value=false;message.value=rule.enabled?'Process identification disabled':'Process identification enabled';processTarget.value=null;await loadProcess()}catch(cause){error.value=cause.message}finally{processBusy.value=false}}
onMounted(()=>{load();loadProcess()})
</script>

<template>
  <section class="classifier-settings">
    <div class="panel-title"><div><span class="eyebrow">TRAFFIC ANALYSIS</span><h2>Classifier rules</h2></div><button v-if="activeTab==='ports'" class="button primary" @click="openNew"><i class="mdi mdi-plus"></i> Add rule</button><button v-else class="button primary" @click="openProcessNew"><i class="mdi mdi-plus"></i> Add process rule</button></div>
    <div class="admin-subtabs" role="tablist" aria-label="Classifier rule types"><button type="button" role="tab" :aria-selected="activeTab==='ports'" :class="{active:activeTab==='ports'}" @click="activeTab='ports'">Ports and protocols</button><button type="button" role="tab" :aria-selected="activeTab==='processes'" :class="{active:activeTab==='processes'}" @click="activeTab='processes'">Process identification</button></div>
    <template v-if="activeTab==='ports'">
      <p class="muted">Identify common traffic using the IANA service registry and WinFire’s built-in protocol catalog. Custom rules take precedence and can label internal applications for your environment.</p>
      <div class="classifier-meta"><span>{{total.toLocaleString()}} rules</span><span>Catalog snapshot: IANA {{rows.length?'available':'loading'}}</span><a href="https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.csv" target="_blank" rel="noreferrer">View IANA registry</a></div>
      <form class="classifier-filters" @submit.prevent="searchRows"><input v-model.trim="search" placeholder="Search service, port, or description" aria-label="Search classifier rules"><select v-model="protocol" aria-label="Filter protocol" @change="searchRows"><option value="">All protocols</option><option v-for="value in ['TCP','UDP','SCTP','DCCP','ICMP','ICMPv6','IGMP']" :key="value">{{value}}</option></select><select v-model="source" aria-label="Filter source" @change="searchRows"><option value="">All sources</option><option value="built-in">Built-in</option><option value="iana">IANA</option><option value="custom">Custom</option></select><select v-model="enabled" aria-label="Filter enabled" @change="searchRows"><option value="">Any state</option><option value="true">Enabled</option><option value="false">Disabled</option></select><button class="button small secondary">Search</button></form>
      <div class="table-wrap"><table><thead><tr><th><button class="table-sort" @click="sort('protocol')">PROTOCOL ↕</button></th><th><button class="table-sort" @click="sort('port')">PORT ↕</button></th><th><button class="table-sort" @click="sort('service')">SERVICE ↕</button></th><th>DESCRIPTION</th><th><button class="table-sort" @click="sort('source')">SOURCE ↕</button></th><th><button class="table-sort" @click="sort('enabled')">STATE ↕</button></th><th>ACTIONS</th></tr></thead><tbody><tr v-for="rule in rows" :key="rule.id"><td class="mono">{{rule.protocol}}</td><td class="mono">{{portLabel(rule)}}</td><td><strong>{{rule.service}}</strong></td><td class="classifier-description">{{rule.description||'—'}}</td><td><span class="status" :class="rule.source==='custom'?'learning':rule.source==='iana'?'neutral':'reachable'">{{rule.source}}</span></td><td><span class="status" :class="rule.enabled?'reachable':'unreachable'">{{rule.enabled?'Enabled':'Disabled'}}</span></td><td><div class="inline-actions"><button class="button small secondary" @click="openEdit(rule)">Edit</button><button class="button small danger" @click="askDelete(rule)">{{rule.enabled?'Disable':'Restore'}}</button></div></td></tr><tr v-if="!rows.length"><td colspan="7" class="empty-table">{{loading?'Loading classifier rules…':'No classifier rules match these filters.'}}</td></tr></tbody></table></div>
      <div class="pagination"><span>Page {{page}} of {{pages}} · {{total.toLocaleString()}} rules</span><div><button class="button small secondary" :disabled="page<=1||loading" @click="move(page-1)">Previous</button><button class="button small secondary" :disabled="page>=pages||loading" @click="move(page+1)">Next</button></div></div>
    </template>
    <template v-else>
      <p class="muted">Match a process executable or Windows device path to identify traffic that uses dynamic or ambiguous ports. Matching is case-insensitive and checks whether the path contains the configured pattern.</p>
      <div class="classifier-meta"><span>{{processTotal.toLocaleString()}} process rules</span><span>Built-ins include LSASS and DFSR</span></div>
      <form class="classifier-filters process-filters" @submit.prevent="searchProcess"><input v-model.trim="processSearch" placeholder="Search executable, service, or description" aria-label="Search process classifier rules"><select v-model="processSource" aria-label="Filter process rule source" @change="searchProcess"><option value="">All sources</option><option value="built-in">Built-in</option><option value="custom">Custom</option></select><select v-model="processEnabled" aria-label="Filter process rule state" @change="searchProcess"><option value="">Any state</option><option value="true">Enabled</option><option value="false">Disabled</option></select><button class="button small secondary">Search</button></form>
      <div class="table-wrap"><table><thead><tr><th><button class="table-sort" @click="sortProcess('pattern')">EXECUTABLE PATTERN ↕</button></th><th><button class="table-sort" @click="sortProcess('service')">SERVICE ↕</button></th><th>DESCRIPTION</th><th><button class="table-sort" @click="sortProcess('source')">SOURCE ↕</button></th><th><button class="table-sort" @click="sortProcess('priority')">PRIORITY ↕</button></th><th><button class="table-sort" @click="sortProcess('enabled')">STATE ↕</button></th><th>ACTIONS</th></tr></thead><tbody><tr v-for="rule in processRows" :key="rule.id"><td class="mono process-pattern">{{rule.executablePattern}}</td><td><strong>{{rule.service}}</strong></td><td class="classifier-description">{{rule.description||'—'}}</td><td><span class="status" :class="rule.source==='custom'?'learning':'reachable'">{{rule.source}}</span></td><td>{{rule.priority}}</td><td><span class="status" :class="rule.enabled?'reachable':'unreachable'">{{rule.enabled?'Enabled':'Disabled'}}</span></td><td><div class="inline-actions"><button class="button small secondary" @click="openProcessEdit(rule)">Edit</button><button class="button small danger" @click="askProcessToggle(rule)">{{rule.enabled?'Disable':'Enable'}}</button></div></td></tr><tr v-if="!processRows.length"><td colspan="7" class="empty-table">{{processLoading?'Loading process rules…':'No process rules match these filters.'}}</td></tr></tbody></table></div>
      <div class="pagination"><span>Page {{processPage}} of {{processPages}} · {{processTotal.toLocaleString()}} process rules</span><div><button class="button small secondary" :disabled="processPage<=1||processLoading" @click="moveProcess(processPage-1)">Previous</button><button class="button small secondary" :disabled="processPage>=processPages||processLoading" @click="moveProcess(processPage+1)">Next</button></div></div>
    </template>
    <p v-if="error" class="error-msg">{{error}}</p><p v-if="message" class="success-msg">{{message}}</p>
  </section>
  <GlassWindow v-model="dialogOpen" :title="editing?'Edit classifier rule':'Add classifier rule'" width="640px"><form class="form-grid classifier-form" @submit.prevent="save"><label>Protocol<select v-model="draft.protocol" required><option v-for="value in ['ANY','TCP','UDP','SCTP','DCCP','ICMP','ICMPv6','IGMP']" :key="value">{{value}}</option></select></label><label>Port start<input v-model.number="draft.portStart" type="number" min="1" max="65535" :disabled="noPortProtocol" placeholder="Any"></label><label>Port end<input v-model.number="draft.portEnd" type="number" min="1" max="65535" :disabled="noPortProtocol" placeholder="Same as start"></label><label>Service name<input v-model.trim="draft.service" required maxlength="160" placeholder="Internal Billing API"></label><label>Description<textarea v-model.trim="draft.description" rows="3" maxlength="500" placeholder="What this application does"></textarea></label><label>Priority<input v-model.number="draft.priority" type="number" min="1" max="10000" required><small>Lower values win when multiple rules match.</small></label><label class="switch-field"><span>Enabled</span><input v-model="draft.enabled" type="checkbox" role="switch"><span class="switch-control" aria-hidden="true"></span></label><div class="form-actions"><button type="button" class="button secondary" @click="dialogOpen=false">Cancel</button><button class="button primary" :disabled="busy">{{busy?'Saving…':'Save rule'}}</button></div></form></GlassWindow>
  <GlassWindow v-model="processDialogOpen" :title="processEditing?'Edit process identification rule':'Add process identification rule'" width="640px"><form class="form-grid classifier-form" @submit.prevent="saveProcess"><label>Executable path or name<input v-model.trim="processDraft.executablePattern" required maxlength="512" placeholder="lsass.exe or \\Device\\HarddiskVolume3\\App\\service.exe"><small>Case-insensitive substring match.</small></label><label>Service name<input v-model.trim="processDraft.service" required maxlength="160" placeholder="Internal application service"></label><label>Description<textarea v-model.trim="processDraft.description" rows="3" maxlength="500" placeholder="What this process provides"></textarea></label><label>Priority<input v-model.number="processDraft.priority" type="number" min="1" max="10000" required><small>Lower values win when patterns overlap.</small></label><label class="switch-field"><span>Enabled</span><input v-model="processDraft.enabled" type="checkbox" role="switch"><span class="switch-control" aria-hidden="true"></span></label><div class="form-actions"><button type="button" class="button secondary" @click="processDialogOpen=false">Cancel</button><button class="button primary" :disabled="processBusy">{{processBusy?'Saving…':'Save process rule'}}</button></div></form></GlassWindow>
  <GlassWindow v-model="confirmOpen" title="Change classifier rule" width="480px"><p>{{target?.enabled?'Disable':'Restore'}} <strong>{{target?.service}}</strong>? This changes how matching firewall and mapping traffic is labeled.</p><label class="check-label confirm-checkbox"><input v-model="confirmChecked" type="checkbox"> I understand this changes traffic classification.</label><div class="form-actions"><button class="button secondary" @click="confirmOpen=false">Cancel</button><button class="button danger" :disabled="!confirmChecked||busy" @click="remove">{{target?.enabled?'Disable':'Restore'}}</button></div></GlassWindow>
  <GlassWindow v-model="processConfirmOpen" title="Change process identification" width="480px"><p>{{processTarget?.enabled?'Disable':'Enable'}} <strong>{{processTarget?.service}}</strong> for paths containing <code>{{processTarget?.executablePattern}}</code>?</p><label class="check-label confirm-checkbox"><input v-model="processConfirmChecked" type="checkbox"> I understand this changes traffic classification.</label><div class="form-actions"><button class="button secondary" @click="processConfirmOpen=false">Cancel</button><button class="button danger" :disabled="!processConfirmChecked||processBusy" @click="toggleProcess">{{processTarget?.enabled?'Disable':'Enable'}}</button></div></GlassWindow>
</template>

<style scoped>
.classifier-settings{display:grid;gap:1rem}.classifier-meta{display:flex;gap:1rem;align-items:center;color:var(--muted);font-size:.78rem}.classifier-meta a{color:var(--accent);margin-left:auto}.classifier-filters{display:grid;grid-template-columns:minmax(220px,1fr) 150px 150px 130px auto;gap:.6rem;align-items:end}.process-filters{grid-template-columns:minmax(220px,1fr) 150px 130px auto}.classifier-filters input,.classifier-filters select{min-width:0}.table-sort{font:inherit;font-weight:700;color:inherit;background:none;border:0;padding:0;cursor:pointer}.classifier-description{max-width:360px;white-space:normal;color:var(--muted);font-size:.78rem}.process-pattern{max-width:320px;overflow-wrap:anywhere}.classifier-form small{display:block;color:var(--muted);font-weight:400}.pagination{display:flex;justify-content:space-between;align-items:center}.pagination>div{display:flex;gap:.5rem}@media(max-width:900px){.classifier-filters,.process-filters{grid-template-columns:1fr 1fr}.classifier-filters input,.process-filters input{grid-column:1/-1}.classifier-meta{flex-wrap:wrap}.classifier-meta a{margin-left:0}}
</style>
