<script setup>
import {computed,onMounted,ref} from 'vue'
import GlassWindow from './GlassWindow.vue'
import {api} from '../services/api.js'

const rows=ref([]),total=ref(0),page=ref(1),pages=ref(1),loading=ref(false),error=ref(''),message=ref('')
const search=ref(''),protocol=ref(''),source=ref(''),enabled=ref(''),sortBy=ref('port'),sortDir=ref('asc')
const dialogOpen=ref(false),confirmOpen=ref(false),confirmChecked=ref(false),target=ref(null),busy=ref(false)
const draft=ref({protocol:'TCP',portStart:null,portEnd:null,service:'',description:'',priority:10,enabled:true})
const editing= computed(()=>!!target.value)
const noPortProtocol=computed(()=>['ICMP','ICMPv6','IGMP'].includes(draft.value.protocol))
function query(){
  const params={search:search.value,protocol:protocol.value,source:source.value,enabled:enabled.value,page:page.value,pageSize:100,sortBy:sortBy.value,sortDir:sortDir.value}
  return new URLSearchParams(Object.entries(params).filter(([,value])=>value!==''&&value!==null)).toString()
}
async function load(){loading.value=true;error.value='';try{const result=await api(`/settings/classifier?${query()}`);rows.value=result.items;total.value=result.total;page.value=result.page;pages.value=result.totalPages}catch(cause){error.value=cause.message}finally{loading.value=false}}
function searchRows(){page.value=1;load()}
function sort(column){if(sortBy.value===column)sortDir.value=sortDir.value==='asc'?'desc':'asc';else{sortBy.value=column;sortDir.value='asc'};searchRows()}
function move(next){if(next<1||next>pages.value)return;page.value=next;load()}
function portLabel(rule){if(rule.portStart===null||rule.portStart===undefined)return 'Any port';return rule.portStart===rule.portEnd?String(rule.portStart):`${rule.portStart}-${rule.portEnd}`}
function openNew(){target.value=null;draft.value={protocol:'TCP',portStart:null,portEnd:null,service:'',description:'',priority:10,enabled:true};dialogOpen.value=true}
function openEdit(rule){target.value=rule;draft.value={protocol:rule.protocol,portStart:rule.portStart,portEnd:rule.portEnd,service:rule.service,description:rule.description||'',priority:rule.priority,enabled:rule.enabled};dialogOpen.value=true}
function normalizeDraft(){const value={...draft.value};if(noPortProtocol.value){value.portStart=null;value.portEnd=null}else{value.portStart=value.portStart?Number(value.portStart):null;value.portEnd=value.portEnd?Number(value.portEnd):null}value.priority=Number(value.priority);return value}
async function save(){busy.value=true;error.value='';message.value='';try{const value=normalizeDraft();if(editing.value)await api(`/settings/classifier/rules/${target.value.id}`,{method:'PATCH',body:value});else await api('/settings/classifier/rules',{method:'POST',body:value});dialogOpen.value=false;message.value=editing.value?'Classifier rule updated':'Classifier rule added';await load()}catch(cause){error.value=cause.message}finally{busy.value=false}}
function askDelete(rule){target.value=rule;confirmChecked.value=false;confirmOpen.value=true}
async function remove(){if(!target.value||!confirmChecked.value)return;busy.value=true;error.value='';try{await api(`/settings/classifier/rules/${target.value.id}`,{method:'DELETE'});confirmOpen.value=false;message.value=target.value.source==='custom'?'Classifier override removed':'Classifier rule disabled';target.value=null;await load()}catch(cause){error.value=cause.message}finally{busy.value=false}}
onMounted(load)
</script>

<template>
  <section class="classifier-settings">
    <div class="panel-title"><div><span class="eyebrow">TRAFFIC ANALYSIS</span><h2>Classifier rules</h2></div><button class="button primary" @click="openNew"><i class="mdi mdi-plus"></i> Add rule</button></div>
    <p class="muted">Identify common traffic using the IANA service registry and WinFire’s built-in protocol catalog. Custom rules take precedence and can label internal applications for your environment.</p>
    <div class="classifier-meta"><span>{{total.toLocaleString()}} rules</span><span>Catalog snapshot: IANA {{rows.length?'available':'loading'}}</span><a href="https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.csv" target="_blank" rel="noreferrer">View IANA registry</a></div>
    <form class="classifier-filters" @submit.prevent="searchRows"><input v-model.trim="search" placeholder="Search service, port, or description" aria-label="Search classifier rules"><select v-model="protocol" aria-label="Filter protocol" @change="searchRows"><option value="">All protocols</option><option v-for="value in ['TCP','UDP','SCTP','DCCP','ICMP','ICMPv6','IGMP']" :key="value">{{value}}</option></select><select v-model="source" aria-label="Filter source" @change="searchRows"><option value="">All sources</option><option value="built-in">Built-in</option><option value="iana">IANA</option><option value="custom">Custom</option></select><select v-model="enabled" aria-label="Filter enabled" @change="searchRows"><option value="">Any state</option><option value="true">Enabled</option><option value="false">Disabled</option></select><button class="button small secondary">Search</button></form>
    <p v-if="error" class="error-msg">{{error}}</p><p v-if="message" class="success-msg">{{message}}</p>
    <div class="table-wrap"><table><thead><tr><th><button class="table-sort" @click="sort('protocol')">PROTOCOL ↕</button></th><th><button class="table-sort" @click="sort('port')">PORT ↕</button></th><th><button class="table-sort" @click="sort('service')">SERVICE ↕</button></th><th>DESCRIPTION</th><th><button class="table-sort" @click="sort('source')">SOURCE ↕</button></th><th><button class="table-sort" @click="sort('enabled')">STATE ↕</button></th><th>ACTIONS</th></tr></thead><tbody><tr v-for="rule in rows" :key="rule.id"><td class="mono">{{rule.protocol}}</td><td class="mono">{{portLabel(rule)}}</td><td><strong>{{rule.service}}</strong></td><td class="classifier-description">{{rule.description||'—'}}</td><td><span class="status" :class="rule.source==='custom'?'learning':rule.source==='iana'?'neutral':'reachable'">{{rule.source}}</span></td><td><span class="status" :class="rule.enabled?'reachable':'unreachable'">{{rule.enabled?'Enabled':'Disabled'}}</span></td><td><div class="inline-actions"><button class="button small secondary" @click="openEdit(rule)">Edit</button><button class="button small danger" @click="askDelete(rule)">{{rule.enabled?'Disable':'Restore'}}</button></div></td></tr><tr v-if="!rows.length"><td colspan="7" class="empty-table">{{loading?'Loading classifier rules…':'No classifier rules match these filters.'}}</td></tr></tbody></table></div>
    <div class="pagination"><span>Page {{page}} of {{pages}} · {{total.toLocaleString()}} rules</span><div><button class="button small secondary" :disabled="page<=1||loading" @click="move(page-1)">Previous</button><button class="button small secondary" :disabled="page>=pages||loading" @click="move(page+1)">Next</button></div></div>
  </section>
  <GlassWindow v-model="dialogOpen" :title="editing?'Edit classifier rule':'Add classifier rule'" width="640px"><form class="form-grid classifier-form" @submit.prevent="save"><label>Protocol<select v-model="draft.protocol" required><option v-for="value in ['ANY','TCP','UDP','SCTP','DCCP','ICMP','ICMPv6','IGMP']" :key="value">{{value}}</option></select></label><label>Port start<input v-model.number="draft.portStart" type="number" min="1" max="65535" :disabled="noPortProtocol" placeholder="Any"></label><label>Port end<input v-model.number="draft.portEnd" type="number" min="1" max="65535" :disabled="noPortProtocol" placeholder="Same as start"></label><label>Service name<input v-model.trim="draft.service" required maxlength="160" placeholder="Internal Billing API"></label><label>Description<textarea v-model.trim="draft.description" rows="3" maxlength="500" placeholder="What this application does"></textarea></label><label>Priority<input v-model.number="draft.priority" type="number" min="1" max="10000" required><small>Lower values win when multiple rules match.</small></label><label class="check-label"><input v-model="draft.enabled" type="checkbox"> Enabled</label><div class="form-actions"><button type="button" class="button secondary" @click="dialogOpen=false">Cancel</button><button class="button primary" :disabled="busy">{{busy?'Saving…':'Save rule'}}</button></div></form></GlassWindow>
  <GlassWindow v-model="confirmOpen" title="Change classifier rule" width="480px"><p>{{target?.enabled?'Disable':'Restore'}} <strong>{{target?.service}}</strong>? This changes how matching firewall and mapping traffic is labeled.</p><label class="check-label confirm-checkbox"><input v-model="confirmChecked" type="checkbox"> I understand this changes traffic classification.</label><div class="form-actions"><button class="button secondary" @click="confirmOpen=false">Cancel</button><button class="button danger" :disabled="!confirmChecked||busy" @click="remove">{{target?.enabled?'Disable':'Restore'}}</button></div></GlassWindow>
</template>

<style scoped>
.classifier-settings{display:grid;gap:1rem}.classifier-meta{display:flex;gap:1rem;align-items:center;color:var(--muted);font-size:.78rem}.classifier-meta a{color:var(--accent);margin-left:auto}.classifier-filters{display:grid;grid-template-columns:minmax(220px,1fr) 150px 150px 130px auto;gap:.6rem;align-items:end}.classifier-filters input,.classifier-filters select{min-width:0}.table-sort{font:inherit;font-weight:700;color:inherit;background:none;border:0;padding:0;cursor:pointer}.classifier-description{max-width:360px;white-space:normal;color:var(--muted);font-size:.78rem}.classifier-form small{display:block;color:var(--muted);font-weight:400}.pagination{display:flex;justify-content:space-between;align-items:center}.pagination>div{display:flex;gap:.5rem}@media(max-width:900px){.classifier-filters{grid-template-columns:1fr 1fr}.classifier-filters input{grid-column:1/-1}.classifier-meta{flex-wrap:wrap}.classifier-meta a{margin-left:0}}
</style>
