<script setup>
import {ref,onMounted} from 'vue'
import {api} from '../services/api.js'
import GlassWindow from './GlassWindow.vue'
const policies=ref([]),incidents=ref({items:[],total:0}),error=ref(''),busy=ref(false),dialog=ref(''),form=ref({}),editing=ref(null),selected=ref(null),nodeSearch=ref(''),nodes=ref([]),nodeId=ref(''),ports=ref('443'),exclusions=ref(''),detail=ref(null),preview=ref([]),query=ref({page:1,pageSize:25,q:'',status:'all'})
const defaults=()=>({name:'',enabled:false,mode:'detect',nodeIds:[],protocol:'TCP',ports:[443],windowSeconds:60,eventThreshold:1000,sourceThreshold:20,perSourceThreshold:10,blockSeconds:300,observeSeconds:60,excludeLocal:true,excludedCidrs:[]})
const when=v=>v?new Date(v).toLocaleString():'—'
async function load(){try{[policies.value,incidents.value]=await Promise.all([api('/protection/ddos/policies'),api('/protection/ddos/incidents?'+new URLSearchParams(query.value))]);error.value=''}catch(e){error.value=e.message}}
async function act(fn){if(busy.value)return;busy.value=true;error.value='';try{await fn()}catch(e){error.value=e.message}finally{busy.value=false}}
async function searchNodes(){await act(async()=>{nodes.value=(await api('/nodes?page=1&pageSize=100&search='+encodeURIComponent(nodeSearch.value))).items})}
function edit(p=null){editing.value=p?.id||null;form.value=p?Object.fromEntries(Object.keys(defaults()).map(k=>[k,p[k]])):defaults();form.value.nodeIds=[...form.value.nodeIds];ports.value=form.value.ports.join(', ');exclusions.value=form.value.excludedCidrs.join('\n');dialog.value='form';nodeSearch.value='';nodeId.value='';searchNodes()}
function addNode(){if(nodeId.value&&!form.value.nodeIds.includes(nodeId.value))form.value.nodeIds.push(nodeId.value);nodeId.value=''}
async function save(){await act(async()=>{const payload={...form.value,ports:ports.value.split(/[,\s]+/).filter(Boolean).map(Number),excludedCidrs:exclusions.value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean)};await api('/protection/ddos/policies'+(editing.value?'/'+editing.value:''),{method:editing.value?'PUT':'POST',body:payload});dialog.value='';await load()})}
async function toggle(p){await act(async()=>{await api('/protection/ddos/policies/'+p.id,{method:'PUT',body:{...Object.fromEntries(Object.keys(defaults()).map(k=>[k,p[k]])),enabled:!p.enabled}});await load()})}
async function showPreview(p){await act(async()=>{preview.value=await api('/protection/ddos/policies/'+p.id+'/preview');dialog.value='preview'})}
async function inspect(i){await act(async()=>{detail.value=await api('/protection/ddos/incidents/'+i.id);dialog.value='detail'})}
function confirm(item,action){selected.value=item;dialog.value=action}
async function confirmed(){await act(async()=>{if(dialog.value==='delete')await api('/protection/ddos/policies/'+selected.value.id,{method:'DELETE'});else await api('/protection/ddos/incidents/'+selected.value.id+'/release',{method:'POST'});dialog.value='';await load()})}
function search(){query.value.page=1;load()}
onMounted(load)
</script>
<template><section class="ddos-settings">
 <div class="panel-title"><h2>DDoS protection</h2><div class="inline-actions"><button class="button secondary" :disabled="busy" @click="load">Refresh</button><button class="button primary" :disabled="busy" @click="edit()">Add protection policy</button></div></div>
 <p>Detect inbound traffic surges using collected firewall events. Policies start disabled in detection-only mode. Configure service ports and thresholds before enabling them.</p>
 <p class="muted">Automatic blocking supports modern Windows over WinRM and Linux over SSH with nftables and passwordless sudo. SNMP and API inventory alone cannot enforce blocks. Detection depends on event collection latency; this does not replace upstream protection against link saturation.</p>
 <p v-if="error&&!dialog" class="error-msg" role="alert">{{error}}</p>
 <div class="table-wrap"><table><thead><tr><th>Policy</th><th>Mode</th><th>Scope</th><th>Threshold</th><th>Enabled</th><th>Actions</th></tr></thead><tbody><tr v-for="p in policies" :key="p.id"><td>{{p.name}}</td><td>{{p.mode==='detect'?'Detection only':'Timed blocking'}}</td><td>{{p.nodeIds.length}} nodes<small>{{p.protocol}} · {{p.ports.join(', ')}}</small></td><td>{{p.eventThreshold}} events / {{p.windowSeconds}}s<small>{{p.sourceThreshold}} distinct sources</small></td><td><label class="switch-field"><span class="sr-only">Enable {{p.name}}</span><input type="checkbox" role="switch" :checked="p.enabled" :disabled="busy" @change="toggle(p)"><span class="switch-control" aria-hidden="true"></span></label></td><td><div class="inline-actions"><button class="button small secondary" @click="edit(p)">Edit</button><button class="button small secondary" :disabled="busy" @click="showPreview(p)">Preview</button><button class="button small danger" :disabled="busy" @click="confirm(p,'delete')">Delete</button></div></td></tr><tr v-if="!policies.length"><td colspan="6">No protection policies configured.</td></tr></tbody></table></div>
 <h3>Attack incidents</h3><form class="incident-toolbar" @submit.prevent="search"><input v-model.trim="query.q" placeholder="Search policy or hostname" aria-label="Search DDoS incidents"><select v-model="query.status" aria-label="Incident status" @change="search"><option value="all">All incidents</option><option value="active">Active</option><option value="closed">Closed</option></select><button class="button secondary">Search</button></form>
 <div class="table-wrap"><table><thead><tr><th>Started</th><th>Policy / Node</th><th>State</th><th>Evidence</th><th>Cycles / Expiry</th><th>Actions</th></tr></thead><tbody><tr v-for="i in incidents.items" :key="i.id"><td>{{when(i.created_at)}}</td><td>{{i.policyName}}<small>{{i.hostname}}</small></td><td>{{i.status}}<small v-if="i.last_error" class="incident-error">{{i.last_error}}</small></td><td>{{i.evidence.events}} events<small>{{i.evidence.uniqueSources}} sources</small></td><td>{{i.cycles}}<small>{{when(i.expires_at)}}</small></td><td><div class="inline-actions"><button class="button small secondary" :disabled="busy" @click="inspect(i)">Details</button><button v-if="!i.closed_at" class="button small danger" :disabled="busy" @click="confirm(i,'release')">Stop / release</button></div></td></tr><tr v-if="!incidents.items.length"><td colspan="6">No incidents match these filters.</td></tr></tbody></table></div>
 <div class="incident-toolbar"><span>{{incidents.total}} incidents · Page {{query.page}}</span><label>Rows<select v-model.number="query.pageSize" @change="search"><option :value="25">25</option><option :value="50">50</option><option :value="100">100</option></select></label><button class="button secondary" :disabled="query.page===1" @click="query.page--;load()">Previous</button><button class="button secondary" :disabled="query.page*query.pageSize>=incidents.total" @click="query.page++;load()">Next</button></div>
 <GlassWindow :model-value="!!dialog" :title="dialog==='form'?'Protection policy':dialog==='detail'?'Attack details':dialog==='preview'?'Current detection evidence':dialog==='delete'?'Delete protection policy':'Stop protection and release traffic'" width="900px" @update:model-value="v=>{if(!v&&!busy)dialog=''}">
  <p v-if="error" class="error-msg" role="alert">{{error}}</p>
  <form v-if="dialog==='form'" class="protection-form" @submit.prevent="save">
   <label>Name<input v-model.trim="form.name" maxlength="100" required></label><label>Mode<select v-model="form.mode"><option value="detect">Detection only</option><option value="block">Automatic timed blocking</option></select></label>
   <label class="switch-field"><span>Enable policy</span><input v-model="form.enabled" type="checkbox" role="switch"><span class="switch-control" aria-hidden="true"></span></label><label class="switch-field"><span>Exclude local source CIDRs</span><input v-model="form.excludeLocal" type="checkbox" role="switch"><span class="switch-control" aria-hidden="true"></span></label>
   <div class="full node-picker"><label>Find nodes<input v-model="nodeSearch" placeholder="Hostname or address" @keydown.enter.prevent="searchNodes"></label><button type="button" class="button secondary" :disabled="busy" @click="searchNodes">Find</button><label>Node<select v-model="nodeId"><option value="">Select node</option><option v-for="n in nodes" :key="n.id" :value="n.id">{{n.hostname}} · {{n.ip}} · {{n.transport||'unknown'}}</option></select></label><button type="button" class="button secondary" :disabled="!nodeId" @click="addNode">Add node</button></div>
   <div class="full selected-nodes"><span v-for="n in form.nodeIds" :key="n">{{nodes.find(item=>item.id===n)?.hostname||n}} <button type="button" class="button small secondary" @click="form.nodeIds=form.nodeIds.filter(item=>item!==n)">Remove</button></span><small v-if="!form.nodeIds.length">Select at least one node. Each node can have one enabled policy.</small></div>
   <label>Protocol<select v-model="form.protocol"><option>TCP</option><option>UDP</option></select></label><label>Destination ports<input v-model="ports" required placeholder="80, 443"><small>Exact service ports only. Management ports cannot be blocked.</small></label>
   <label>Detection window (seconds)<input v-model.number="form.windowSeconds" type="number" min="30" max="3600" required></label><label>Event threshold per window<input v-model.number="form.eventThreshold" type="number" min="10" max="100000" required></label>
   <label>Minimum distinct sources<input v-model.number="form.sourceThreshold" type="number" min="1" max="10000" required></label><label>Minimum events per blocked source<input v-model.number="form.perSourceThreshold" type="number" min="1" max="100000" required></label>
   <label>Block duration (seconds)<input v-model.number="form.blockSeconds" type="number" min="30" max="86400" required></label><label>Observation period after release (seconds)<input v-model.number="form.observeSeconds" type="number" :min="form.windowSeconds" max="3600" required></label>
   <label class="full">Excluded source CIDRs<textarea v-model="exclusions" rows="3" placeholder="Trusted clients and upstream proxies, one CIDR per line"></textarea><small>Exclusions apply to detection and blocking. Control-plane addresses and the target node are excluded automatically. Add WINFIRE_CONTROL_PLANE_IPS on the server if management traffic uses NAT.</small></label>
   <p class="full muted">After expiry, temporary block rules are removed and existing firewall policy resumes. A fresh observation window determines whether to block again. Missing telemetry is shown as unconfirmed; it never means the attack has ended. Blocks target up to 100 qualifying source addresses per cycle.</p>
   <div class="form-actions full"><button type="button" class="button secondary" :disabled="busy" @click="dialog=''">Cancel</button><button class="button primary" :disabled="busy||!form.nodeIds.length">Save policy</button></div>
  </form>
  <template v-else-if="dialog==='preview'"><p>Current event counts do not apply firewall changes.</p><div v-for="p in preview" :key="p.nodeId" class="preview-node"><strong>{{p.hostname||p.nodeId}}</strong><p>{{p.evidence?.events||0}} events · {{p.evidence?.uniqueSources||0}} sources · {{p.evidence?.thresholdMet?'Threshold met':'Below threshold'}} · {{p.evidence?.fresh?'Fresh telemetry':'No fresh telemetry'}}</p></div></template>
  <template v-else-if="dialog==='detail'&&detail"><p>State: <strong>{{detail.status}}</strong> · Block cycles: {{detail.cycles}}</p><p v-if="detail.last_error" class="error-msg">{{detail.last_error}}</p><p>{{detail.evidence.events}} events from {{detail.evidence.uniqueSources}} sources. {{when(detail.evidence.windowStart)}} — {{when(detail.evidence.windowEnd)}}.</p><h3>Qualifying sources</h3><div class="table-wrap"><table><thead><tr><th>Source</th><th>Events</th></tr></thead><tbody><tr v-for="s in detail.evidence.sources" :key="s.ip"><td>{{s.ip}}</td><td>{{s.count}}</td></tr></tbody></table></div><h3>History</h3><p v-for="(h,index) in detail.history" :key="index">{{when(h.created_at)}} · {{h.status}}<small>{{h.detail.summary}}</small></p></template>
  <template v-else><p>{{dialog==='delete'?'Delete this policy? Its incident history is retained. Active incidents must be released first.':'This disables the policy for all its nodes and removes this incident’s temporary blocks. Other active blocks are released by the next evaluation cycle. Existing firewall policy remains in effect.'}}</p><div class="form-actions"><button class="button secondary" :disabled="busy" @click="dialog=''">Cancel</button><button class="button danger" :disabled="busy" @click="confirmed">{{dialog==='delete'?'Delete policy':'Disable policy and release'}}</button></div></template>
 </GlassWindow>
</section></template>
<style scoped>
.ddos-settings{padding:16px;min-width:0}.protection-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.protection-form label{display:grid;align-content:start;gap:6px;min-width:0}.protection-form .switch-field{display:flex}.protection-form input,.protection-form select,.protection-form textarea{width:100%;min-width:0}.full{grid-column:1/-1}.table-wrap{max-width:100%;overflow:auto}table{width:100%;min-width:650px}td{max-width:40ch;overflow-wrap:anywhere;vertical-align:top}small{display:block;margin-top:4px;color:var(--muted)}.incident-error{color:var(--red)}.incident-toolbar,.selected-nodes,.node-picker{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:12px 0}.incident-toolbar>input{flex:1;min-width:180px}.incident-toolbar label{display:flex;align-items:center;gap:6px}.node-picker label{flex:1;min-width:160px}.selected-nodes>span,.preview-node{padding:8px;border:1px solid var(--border);border-radius:4px}.form-actions{flex-wrap:wrap}@media(max-width:650px){.protection-form{grid-template-columns:minmax(0,1fr)}.panel-title{flex-wrap:wrap;gap:8px}.node-picker label{flex-basis:100%}}
</style>
