<script setup>
import {onMounted, ref} from 'vue'
import {api} from '../services/api.js'
const cidrs=ref(''),scans=ref([]),busy=ref(false),error=ref(''),message=ref('')
async function load(){try{scans.value=await api('/discovery/scans')}catch(e){error.value=e.message}}
async function scan(){busy.value=true;error.value='';message.value='';try{const values=cidrs.value.split(/[\n,]/).map(value=>value.trim()).filter(Boolean);const result=await api('/discovery/scans',{method:'POST',body:{cidrs:values}});message.value=`Scan queued for ${result.addresses} address${result.addresses===1?'':'es'}.`;cidrs.value='';await load()}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(load)
</script>
<template><div class="discovery-settings"><div class="panel-title"><div><span class="eyebrow">NETWORK DISCOVERY</span><h2>IPv4 CIDR probes</h2></div></div><p class="muted">Probe bounded IPv4 CIDRs with ICMP first, then a same-subnet ARP request and a small TCP management-port fallback (445, 3389, 5985, 5986). Hosts that block ping can still be discovered and are marked with the liveness method used.</p><form class="form-grid" @submit.prevent="scan"><label>CIDRs (one per line)<textarea v-model="cidrs" rows="4" required placeholder="10.20.0.0/24&#10;192.168.50.0/24"></textarea></label><div class="form-actions"><button class="button primary" :disabled="busy">{{busy?'Starting…':'Start discovery scan'}}</button></div></form><div v-if="error" class="error-msg">{{error}}</div><div v-if="message" class="success-msg">{{message}}</div><div class="table-wrap"><table><thead><tr><th>CREATED</th><th>CIDRS</th><th>STATUS</th><th>PROBED</th><th>ALIVE</th><th>ARP</th><th>TCP</th><th>REGISTERED</th></tr></thead><tbody><tr v-for="scan in scans" :key="scan.id"><td>{{new Date(scan.created_at).toLocaleString()}}</td><td class="mono">{{scan.cidrs.join(', ')}}</td><td><span class="status" :class="scan.status==='complete'?'reachable':scan.status==='failed'?'failed':'pending'">{{scan.status}}</span></td><td>{{scan.probed}}</td><td>{{scan.alive}}</td><td>{{scan.arp_alive||0}}</td><td>{{scan.tcp_alive||0}}</td><td>{{scan.registered}}</td></tr><tr v-if="!scans.length"><td colspan="8" class="empty-table">No discovery scans yet.</td></tr></tbody></table></div></div></template>
<style scoped>.discovery-settings{display:grid;gap:1rem}.discovery-settings .panel-title{padding:0 0 .8rem}.discovery-settings .form-grid{padding:0 1rem}.discovery-settings textarea{width:100%;box-sizing:border-box}.discovery-settings .muted{padding:0 1rem}</style>
