<script setup>
import {onMounted, ref} from 'vue'
import {api} from '../services/api.js'
const cidrs=ref(''),scans=ref([]),passive=ref({summary:{},items:[]}),busy=ref(false),error=ref(''),message=ref('')
async function load(){try{const [scanResult,passiveResult]=await Promise.all([api('/discovery/scans'),api('/discovery/passive-candidates')]);scans.value=scanResult;passive.value=passiveResult}catch(e){error.value=e.message}}
async function scan(){busy.value=true;error.value='';message.value='';try{const values=cidrs.value.split(/[\n,]/).map(value=>value.trim()).filter(Boolean);const result=await api('/discovery/scans',{method:'POST',body:{cidrs:values}});message.value=`Scan queued for ${result.addresses} address${result.addresses===1?'':'es'}.`;cidrs.value='';await load()}catch(e){error.value=e.message}finally{busy.value=false}}
async function processPassive(){busy.value=true;error.value='';message.value='';try{const result=await api('/discovery/passive-candidates/process',{method:'POST',body:{}});message.value=`Processed ${result.processed} passive ARP candidate${result.processed===1?'':'s'}.`;await load()}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(load)
</script>
<template><div class="discovery-settings"><div class="panel-title"><div><span class="eyebrow">NETWORK DISCOVERY</span><h2>IPv4 CIDR probes</h2></div></div><p class="muted">Probe bounded IPv4 CIDRs with ICMP first, then a same-subnet ARP request and a small TCP management-port fallback (445, 3389, 5985, 5986). Hosts that block ping can still be discovered and are marked with the liveness method used.</p><form class="form-grid" @submit.prevent="scan"><label>CIDRs (one per line)<textarea v-model="cidrs" rows="4" required placeholder="10.20.0.0/24&#10;192.168.50.0/24"></textarea></label><div class="form-actions"><button class="button primary" :disabled="busy">{{busy?'Starting…':'Start discovery scan'}}</button></div></form><div v-if="error" class="error-msg">{{error}}</div><div v-if="message" class="success-msg">{{message}}</div><div class="table-wrap"><table><thead><tr><th>CREATED</th><th>CIDRS</th><th>STATUS</th><th>PROBED</th><th>ALIVE</th><th>ARP</th><th>TCP</th><th>REGISTERED</th></tr></thead><tbody><tr v-for="scan in scans" :key="scan.id"><td>{{new Date(scan.created_at).toLocaleString()}}</td><td class="mono">{{scan.cidrs.join(', ')}}</td><td><span class="status" :class="scan.status==='complete'?'reachable':scan.status==='failed'?'failed':'pending'">{{scan.status}}</span></td><td>{{scan.probed}}</td><td>{{scan.alive}}</td><td>{{scan.arp_alive||0}}</td><td>{{scan.tcp_alive||0}}</td><td>{{scan.registered}}</td></tr><tr v-if="!scans.length"><td colspan="8" class="empty-table">No discovery scans yet.</td></tr></tbody></table></div><section class="passive-discovery"><div class="panel-title"><div><span class="eyebrow">PASSIVE DISCOVERY</span><h2>Managed-node ARP candidates</h2></div><div class="inline-actions"><span class="count-chip">{{passive.summary.queued||0}} queued</span><button class="button small secondary" :disabled="busy" @click="processPassive">Process now</button></div></div><p class="muted">ARP entries collected from enrolled agents are queued here without interrupting telemetry. Processing sends candidates through DNS and the normal management verification path.</p><div class="table-wrap"><table><thead><tr><th>IP</th><th>MAC</th><th>SOURCE NODE</th><th>LAST SEEN</th><th>STATUS</th><th>ERROR</th></tr></thead><tbody><tr v-for="candidate in passive.items" :key="candidate.id"><td class="mono">{{candidate.ip}}</td><td class="mono">{{candidate.mac||'—'}}</td><td>{{candidate.source_hostname}}</td><td>{{new Date(candidate.last_seen_at).toLocaleString()}}</td><td><span class="status" :class="candidate.status==='registered'?'reachable':candidate.status==='failed'?'unreachable':'pending'">{{candidate.status}}</span></td><td class="danger-text">{{candidate.last_error||'—'}}</td></tr><tr v-if="!passive.items.length"><td colspan="6" class="empty-table">No passive ARP candidates are waiting.</td></tr></tbody></table></div></section></div></template>
<style scoped>.discovery-settings{display:grid;gap:1rem}.discovery-settings .panel-title{padding:0 0 .8rem}.discovery-settings .form-grid{padding:0 1rem}.discovery-settings textarea{width:100%;box-sizing:border-box}.discovery-settings .muted{padding:0 1rem}.passive-discovery{display:grid;gap:.75rem;border-top:1px solid var(--border);padding-top:1rem}.passive-discovery .panel-title{padding:0 1rem}.passive-discovery .danger-text{color:var(--danger)}</style>
