<script setup>
import {ref,onMounted,watch,computed} from 'vue'
import {api,session} from '../services/api.js'
const props=defineProps({nodeId:String}),data=ref({values:{},proposals:[]}),form=ref({application:'',environment:'',workload_role:'',business_owner:'',criticality:null}),error=ref(''),busy=ref(false),reason=ref(''),editing=ref(false)
const editable=computed(()=>['owner','admin'].includes(session.user?.role))
async function load(){try{data.value=await api(`/nodes/${props.nodeId}/application`);form.value={...data.value.values}}catch(e){error.value=e.message}}
async function propose(){busy.value=true;error.value='';try{await api(`/nodes/${props.nodeId}/application/proposals`,{method:'POST',body:{source:'manual',sourceRef:'node-edit',values:form.value}});editing.value=false;await load()}catch(e){error.value=e.message}finally{busy.value=false}}
async function review(p,approve){busy.value=true;error.value='';try{await api(`/application-proposals/${p.id}/review`,{method:'POST',body:{approve,reason:reason.value}});await load()}catch(e){error.value=e.message}finally{busy.value=false}}
watch(()=>props.nodeId,load);onMounted(load)
</script>
<template><section class="application-context"><h3>Application ownership</h3><p v-if="error" class="error-msg">{{error}}</p><dl><template v-for="(value,key) in data.values" :key="key"><dt>{{key.replaceAll('_',' ')}}</dt><dd>{{value||'Not assigned'}}</dd></template></dl><button v-if="editable" class="button secondary" @click="editing=!editing">Propose metadata change</button><form v-if="editing" @submit.prevent="propose"><label v-for="key in ['application','environment','workload_role','business_owner']" :key="key">{{key.replaceAll('_',' ')}}<input v-model="form[key]" maxlength="120"></label><label>Criticality<select v-model="form.criticality"><option :value="null">Not assigned</option><option v-for="v in ['low','medium','high','critical']" :key="v">{{v}}</option></select></label><button class="button primary" :disabled="busy">Preview change</button></form><p class="muted">Precedence: manual → approved Azure tags → AD OU → node group. Review metadata and affected groups before applying.</p><template v-for="p in data.proposals.filter(p=>p.status==='pending')" :key="p.id"><div class="proposal"><strong>{{p.source}} · {{p.stale?'Stale — create a fresh proposal':'Pending review'}}</strong><dl><template v-for="(value,key) in p.effective" :key="key"><dt>{{key}}</dt><dd>{{p.before[key]||'Not assigned'}} → {{value||'Not assigned'}}</dd></template></dl><p v-if="!p.groupChanges.length">No dynamic group match changes.</p><p v-for="change in p.groupChanges" :key="change.groupId">{{change.action}} {{change.name}} · {{change.policies.length}} assigned policies</p><div v-if="editable" class="actions"><input v-model="reason" placeholder="Review reason" aria-label="Metadata review reason"><button class="button primary" :disabled="busy||p.stale||!reason.trim()" @click="review(p,true)">Approve</button><button class="button secondary" :disabled="busy||p.stale||!reason.trim()" @click="review(p,false)">Reject</button></div></div></template></section></template>
<style scoped>.application-context{margin:18px 0}dl{display:grid;grid-template-columns:minmax(100px,1fr) 2fr;gap:8px}dt{text-transform:capitalize;color:var(--muted)}dd{margin:0;overflow-wrap:anywhere}form{display:grid;gap:12px;margin:14px 0}label{display:grid;gap:6px}.proposal{border:1px solid var(--border);padding:12px;border-radius:8px;margin-top:12px}.actions{display:flex;gap:10px;flex-wrap:wrap}</style>
