<script setup>
import {ref,watch} from 'vue'
import {api} from '../services/api.js'
const props=defineProps({nodeId:{type:String,required:true},collectedAt:String})
const data=ref({profiles:[],items:[],page:1,total:0,limit:25}),moduleId=ref(''),search=ref(''),error=ref(''),loading=ref(false)
let sequence=0
async function load(page=1){const current=++sequence;loading.value=true;error.value='';try{const response=await api(`/nodes/${encodeURIComponent(props.nodeId)}/snmp-mibs?${new URLSearchParams({moduleId:moduleId.value,search:search.value,page,limit:25})}`);if(current===sequence)data.value=response}catch(e){if(current===sequence)error.value=e.message}finally{if(current===sequence)loading.value=false}}
watch(()=>[props.nodeId,props.collectedAt],()=>{moduleId.value='';load()},{immediate:true})
</script>
<template>
  <section class="node-facts-section snmp-facts"><h3>SNMP library and collected data</h3><p class="muted">{{data.profiles.length}} matching sources · {{data.queryCount}} queries · {{data.collectedAt?new Date(data.collectedAt).toLocaleString():'Not collected'}}. Unsupported tables do not invalidate an authenticated SNMP poll.</p><p v-if="data.truncated" class="muted">Some data reached the collection limit. Narrow selected objects in Administration → Discovery → SNMP → MIB library.</p><div v-if="data.hardwareSummary" class="node-facts-grid"><div><span>Manufacturer</span><strong>{{data.hardwareSummary.manufacturer||'—'}}</strong></div><div><span>Model</span><strong>{{data.hardwareSummary.model||'—'}}</strong></div><div><span>Serial number</span><strong>{{data.hardwareSummary.serialNumber||'—'}}</strong></div><div><span>Firmware</span><strong>{{data.hardwareSummary.firmwareRevision||'—'}}</strong></div></div><p v-if="error" class="error-msg">{{error}}</p><div class="table-wrap"><table><thead><tr><th>MIB / Source</th><th>Match evidence</th><th>Collection</th><th>Values</th></tr></thead><tbody><tr v-for="profile in data.profiles" :key="profile.id"><td>{{profile.moduleName}}<small>{{profile.source}}{{profile.enabled?'':' · Disabled or removed since collection'}}</small></td><td>{{profile.evidence.method}} · {{profile.evidence.signal}}<small>{{profile.evidence.reused?'Existing device link':'New match'}}</small></td><td>{{profile.status}}</td><td>{{profile.valueCount}}</td></tr></tbody></table></div><details><summary>Browse collected objects</summary><form class="snmp-facts-tools" @submit.prevent="load()"><select v-model="moduleId" aria-label="Collected MIB source" @change="load()"><option value="">All sources</option><option v-for="profile in data.profiles" :key="profile.id" :value="profile.id">{{profile.moduleName}}</option></select><input v-model="search" placeholder="Search object, OID or value" aria-label="Search collected SNMP objects"><button class="button small secondary" :disabled="loading">Search</button></form><div class="table-wrap"><table><thead><tr><th>Module / Object</th><th>OID</th><th>Value</th><th>Result</th></tr></thead><tbody><tr v-for="(item,index) in data.items" :key="index"><td>{{item.moduleName}}<small>{{item.object}}</small></td><td>{{item.oid}}</td><td class="snmp-value">{{item.value??'—'}} {{item.units||''}}</td><td>{{item.status}}{{item.truncated?' · Limited':''}}<small v-if="item.error">{{item.error}}</small></td></tr><tr v-if="!data.items.length"><td colspan="4">No matching collected objects.</td></tr></tbody></table></div><div class="snmp-facts-tools"><span>{{data.total}} results · Page {{data.page}}</span><button class="button small secondary" :disabled="loading||data.page<=1" @click="load(data.page-1)">Previous</button><button class="button small secondary" :disabled="loading||data.page*data.limit>=data.total" @click="load(data.page+1)">Next</button></div></details></section>
</template>
<style scoped>
.snmp-facts{min-width:0}.snmp-facts p{line-height:1.5}.snmp-facts small{display:block;color:var(--muted);margin-top:.25rem}.snmp-facts td{white-space:normal;overflow-wrap:anywhere}.snmp-value{max-width:45ch}.snmp-facts-tools{display:flex;align-items:center;gap:.5rem;flex-wrap:wrap;margin:.8rem 0}.snmp-facts-tools select,.snmp-facts-tools input{width:auto;flex:1;min-width:140px}.snmp-facts summary{cursor:pointer;margin-top:1rem}
</style>
