<script setup>
import {ref,watch} from 'vue'
import {api} from '../services/api.js'
const props=defineProps({nodeId:{type:String,required:true}}),sources=ref([]),error=ref('')
let revision=0
watch(()=>props.nodeId,async id=>{const current=++revision;sources.value=[];error.value='';try{const data=await api(`/nodes/${id}/sources`);if(current===revision)sources.value=data}catch(e){if(current===revision)error.value=e.message}},{immediate:true})
</script>
<template><section v-if="sources.length||error" class="cloud-sources"><h3>Cloud discovery sources</h3><p v-if="error" class="error-msg">{{error}}</p><details v-for="s in sources" :key="s.id"><summary>{{s.evidence.name}} · {{s.provider}} · {{s.state}}</summary><dl><dt>Resource</dt><dd>{{s.resource_id}}</dd><dt>Fetched</dt><dd>{{new Date(s.fetched_at).toLocaleString()}}</dd><dt>Provider status</dt><dd>{{s.evidence.providerStatus||'Unknown'}} — provider observation only</dd><dt>Operating system</dt><dd>{{s.evidence.osName||'Unknown'}}<small>{{s.evidence.osVersion||'Version unavailable'}}</small></dd><dt>Network addresses</dt><dd>{{s.evidence.addresses?.join(', ')||'Not reported'}}</dd><dt>Hardware / VM UUID</dt><dd>{{s.evidence.uuid||'Not reported'}}</dd><dt>Network scope</dt><dd>{{s.scope_id}}</dd><dt>Field provenance</dt><dd v-for="(value,key) in s.evidence.provenance" :key="key">{{key}}: {{value}}</dd></dl><details><summary>All reported metadata</summary><pre>{{JSON.stringify(s.evidence,null,2)}}</pre></details></details></section></template>
<style scoped>.cloud-sources{margin-block:16px;min-width:0}.cloud-sources>details{border:1px solid var(--border);border-radius:6px;padding:12px;margin-top:8px}summary{cursor:pointer;font-weight:600}dl{display:grid;grid-template-columns:minmax(110px,1fr) minmax(0,3fr);gap:8px}dt{color:var(--muted)}dd{margin:0;overflow-wrap:anywhere}small{display:block;color:var(--muted)}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:360px;overflow:auto}@media(max-width:500px){dl{grid-template-columns:1fr}}</style>
