<script setup>
import {onMounted,ref,watch} from 'vue'
import {api} from '../services/api.js'
import GlassWindow from './GlassWindow.vue'
import ConfirmDialog from './ConfirmDialog.vue'
const result=ref({items:[],total:0,page:1,limit:25}),search=ref(''),source=ref('all'),sort=ref('name'),direction=ref('asc'),busy=ref(false),error=ref(''),message=ref('')
const readingFiles=ref(false),loading=ref(false)
const importing=ref(false),files=ref([]),replace=ref(false),preview=ref(null),importError=ref(''),fileInput=ref(null)
const editing=ref(false),detail=ref(null),objectSearch=ref(''),draft=ref({enabled:true,prefixes:'',descriptions:'',selectedObjects:[]}),editError=ref('')
const removing=ref(false),removeItem=ref(null)
let requestId=0,detailRequestId=0
async function load(page=1){const sequence=++requestId;loading.value=true;error.value='';try{const data=await api(`/discovery/snmp-library?${new URLSearchParams({search:search.value,source:source.value,sort:sort.value,direction:direction.value,page,limit:25})}`);if(sequence===requestId)result.value=data}catch(e){if(sequence===requestId)error.value=e.message}finally{if(sequence===requestId)loading.value=false}}
async function chooseFiles(event){preview.value=null;importError.value='';files.value=[];const selected=[...event.target.files];if(selected.length>20||selected.reduce((n,f)=>n+f.size,0)>1500000){importError.value='Choose up to 20 text MIB files, totaling no more than 1.5 MB.';return}readingFiles.value=true;try{files.value=await Promise.all(selected.map(async file=>({filename:file.name,content:await file.text()})))}catch(e){importError.value='Could not read selected files: '+e.message}finally{readingFiles.value=false}}
watch(replace,()=>{preview.value=null})
async function validateImport(){busy.value=true;importError.value='';try{preview.value=await api('/discovery/snmp-library/preview',{method:'POST',body:{files:files.value,replace:replace.value}})}catch(e){preview.value=null;importError.value=e.message}finally{busy.value=false}}
async function commitImport(){busy.value=true;importError.value='';try{const response=await api('/discovery/snmp-library/import',{method:'POST',body:{files:files.value,replace:replace.value}});message.value=`${response.modules.length} MIB module(s) processed. Matching devices will use them on their next SNMP poll.`;importing.value=false;files.value=[];preview.value=null;if(fileInput.value)fileInput.value.value='';await load()}catch(e){importError.value=e.message}finally{busy.value=false}}
async function openDetails(item){busy.value=true;editError.value='';objectSearch.value='';try{detail.value=await api(`/discovery/snmp-library/${encodeURIComponent(item.id)}`);draft.value={enabled:detail.value.enabled,prefixes:(detail.value.match.sysObjectIdPrefixes||[]).join('\n'),descriptions:(detail.value.match.sysDescrContains||[]).join('\n'),selectedObjects:[...detail.value.selectedObjects]};editing.value=true}catch(e){error.value=e.message}finally{busy.value=false}}
async function objectsPage(page=1){const sequence=++detailRequestId;editError.value='';try{const data=await api(`/discovery/snmp-library/${encodeURIComponent(detail.value.id)}?${new URLSearchParams({search:objectSearch.value,page,limit:25})}`);if(sequence===detailRequestId)detail.value=data}catch(e){if(sequence===detailRequestId)editError.value=e.message}}
function selectObject(name,event){const selected=new Set(draft.value.selectedObjects);if(event.target.checked)selected.add(name);else selected.delete(name);draft.value.selectedObjects=[...selected]}
const lines=text=>text.split(/[\n,]+/).map(s=>s.trim()).filter(Boolean)
async function saveDetails(){busy.value=true;editError.value='';try{const body={enabled:draft.value.enabled,selectedObjects:draft.value.selectedObjects};if(!detail.value.match.all)body.match={sysObjectIdPrefixes:lines(draft.value.prefixes),sysDescrContains:lines(draft.value.descriptions)};await api(`/discovery/snmp-library/${encodeURIComponent(detail.value.id)}`,{method:'PATCH',body});editing.value=false;message.value='MIB collection settings saved. Changes apply on the next poll.';await load(result.value.page)}catch(e){editError.value=e.message}finally{busy.value=false}}
async function toggle(item,event){const enabled=event.target.checked;busy.value=true;try{await api(`/discovery/snmp-library/${encodeURIComponent(item.id)}`,{method:'PATCH',body:{enabled}});await load(result.value.page)}catch(e){error.value=e.message;event.target.checked=item.enabled}finally{busy.value=false}}
async function remove(){busy.value=true;try{await api(`/discovery/snmp-library/${encodeURIComponent(removeItem.value.id)}`,{method:'DELETE'});removing.value=false;await load(result.value.page)}catch(e){error.value=e.message;removing.value=false}finally{busy.value=false}}
onMounted(()=>load())
</script>
<template>
  <section class="mib-library">
    <div class="panel-title"><div><h2>SNMP MIB library</h2><p class="muted">Match device identities to reusable discovery and collection sources.</p></div><button class="button primary" :disabled="busy" @click="importing=true;importError='';preview=null"><i class="mdi mdi-upload"></i> Import MIBs</button></div>
    <p class="mib-intro">Standard profiles probe supported capabilities. Vendor profiles match sysObjectID or sysDescr and are linked to the node after a poll. Import vendor MIBs together with their dependencies to add readable objects. Collection uses read-only queries.</p>
    <p v-if="message" class="success-msg" role="status">{{message}}</p><p v-if="error" class="error-msg" role="alert">{{error}}</p>
    <form class="mib-tools" @submit.prevent="load()"><input v-model="search" aria-label="Search MIB library" placeholder="Search module or filename"><select v-model="source" aria-label="MIB source" @change="load()"><option value="all">All sources</option><option value="builtin">Built-in</option><option value="imported">Imported</option></select><select v-model="sort" aria-label="Sort MIBs by" @change="load()"><option value="name">Module name</option><option value="source">Source</option><option value="updated">Updated</option></select><select v-model="direction" aria-label="MIB sort direction" @change="load()"><option value="asc">Ascending</option><option value="desc">Descending</option></select><button class="button secondary">Search</button></form>
    <div class="table-wrap"><table><thead><tr><th>Module</th><th>Source</th><th>Collection</th><th>Device matching</th><th>Linked nodes</th><th>Enabled</th><th>Actions</th></tr></thead><tbody>
      <tr v-for="item in result.items" :key="item.id"><td><strong>{{item.moduleName}}</strong><small class="mib-description">{{item.description}}</small></td><td>{{item.source==='builtin'?'Built-in':'Imported'}}</td><td>{{item.selectedCount}} / {{item.objectCount}} objects</td><td><span v-if="item.match.all">Standard capabilities</span><span v-else>{{[...(item.match.sysObjectIdPrefixes||[]),...(item.match.sysDescrContains||[])].join(', ')||'Configure a match'}}</span></td><td>{{item.linkedNodes}}</td><td><label class="switch-field"><span class="sr-only">Enable {{item.moduleName}}</span><input type="checkbox" role="switch" :checked="item.enabled" :disabled="busy" @change="toggle(item,$event)"><span class="switch-control" aria-hidden="true"></span></label></td><td><div class="inline-actions"><button class="button small secondary" :disabled="busy" @click="openDetails(item)">Details / Configure</button><button v-if="item.source==='imported'" class="button small danger" :disabled="busy" @click="removeItem=item;removing=true">Remove</button></div></td></tr>
      <tr v-if="!result.items.length"><td colspan="7" class="empty-table">{{loading?'Loading MIB library…':'No MIBs match these filters.'}}</td></tr>
    </tbody></table></div>
    <div class="mib-pagination"><span>{{result.total}} modules · Page {{result.page}} / {{Math.max(1,Math.ceil(result.total/result.limit))}}</span><button class="button small secondary" :disabled="result.page<=1" @click="load(result.page-1)">Previous</button><button class="button small secondary" :disabled="result.page*result.limit>=result.total" @click="load(result.page+1)">Next</button></div>
  </section>
  <GlassWindow v-model="importing" title="Import SNMP MIBs" width="800px">
    <div class="mib-import"><p>Select plain text ASN.1 MIB files (.mib, .my or .txt). Include vendor dependency files in the same batch; order does not matter. Up to 20 files / 1.5 MB per batch.</p><label>MIB files<input ref="fileInput" type="file" multiple accept=".mib,.my,.txt" :disabled="busy||readingFiles" @change="chooseFiles"></label><label class="switch-field"><span>Replace existing modules with the same name</span><input v-model="replace" type="checkbox" role="switch" :disabled="busy"><span class="switch-control" aria-hidden="true"></span></label><p v-if="importError" class="error-msg" role="alert">{{importError}}</p><p v-if="files.length">{{files.length}} files selected</p><button class="button secondary" :disabled="busy||readingFiles||!files.length" @click="validateImport">{{busy?'Processing…':'Validate and preview'}}</button><div v-if="preview" class="mib-preview"><div v-for="module in preview.modules" :key="module.moduleName"><strong>{{module.moduleName}} · {{module.action}}</strong><p>{{module.objectCount}} readable objects · {{module.selectedCount}} selected · {{module.imports.length}} dependencies</p><p v-for="warning in module.warnings" :key="warning" class="muted">{{warning}}</p></div></div><div class="form-actions"><button class="button secondary" :disabled="busy" @click="importing=false">Cancel</button><button class="button primary" :disabled="busy||!preview" @click="commitImport">Import validated MIBs</button></div></div>
  </GlassWindow>
  <GlassWindow v-model="editing" :title="detail?.moduleName||'MIB details'" width="1000px">
    <div v-if="detail" class="mib-detail"><p>{{detail.description}}</p><p v-if="detail.sourceUrl"><a :href="detail.sourceUrl" target="_blank" rel="noopener noreferrer">MIB reference documentation</a></p><p class="muted">{{detail.source}} · {{detail.imports?.length?`Dependencies: ${detail.imports.join(', ')}`:'No imported dependencies'}}. Match criteria use OR; OID matches respect numeric boundaries.</p><label class="switch-field"><span>Enable collection</span><input v-model="draft.enabled" type="checkbox" role="switch" :disabled="busy"><span class="switch-control" aria-hidden="true"></span></label><div v-if="!detail.match.all" class="form-grid"><label>sysObjectID prefixes (one per line)<textarea v-model="draft.prefixes" rows="3" placeholder="1.3.6.1.4.1.9"></textarea></label><label>sysDescr contains (one per line)<textarea v-model="draft.descriptions" rows="3" placeholder="Cisco"></textarea></label></div><p v-else class="muted">This standard profile probes every SNMP device. Unsupported objects are reported without failing identity verification.</p><p v-if="editError" class="error-msg" role="alert">{{editError}}</p>
      <h3>Collection objects · {{draft.selectedObjects.length}} / 64 selected</h3><form class="mib-tools" @submit.prevent="objectsPage()"><input v-model="objectSearch" aria-label="Search MIB objects" placeholder="Search object or OID"><button class="button secondary">Search objects</button></form><div class="table-wrap"><table><thead><tr><th>Collect</th><th>Object</th><th>OID</th><th>Query</th></tr></thead><tbody><tr v-for="object in detail.objects" :key="object.name"><td><label class="switch-field"><span class="sr-only">Collect {{object.name}}</span><input type="checkbox" role="switch" :checked="draft.selectedObjects.includes(object.name)" :disabled="busy||(!draft.selectedObjects.includes(object.name)&&draft.selectedObjects.length>=64)" @change="selectObject(object.name,$event)"><span class="switch-control" aria-hidden="true"></span></label></td><td><strong>{{object.name}}</strong><small class="mib-description">{{object.description}}</small></td><td class="mono">{{object.oid}}</td><td>{{object.kind==='scalar'?'GET':'Bounded walk'}}</td></tr><tr v-if="!detail.objects.length"><td colspan="4">No readable objects. This may be a dependency or notification-only MIB.</td></tr></tbody></table></div><div class="mib-pagination"><span>{{detail.total}} objects · Page {{detail.page}}</span><button class="button small secondary" :disabled="detail.page<=1" @click="objectsPage(detail.page-1)">Previous objects</button><button class="button small secondary" :disabled="detail.page*detail.limit>=detail.total" @click="objectsPage(detail.page+1)">Next objects</button></div>
      <details v-if="detail.bindings.length"><summary>Linked devices (most recent 100)</summary><div class="table-wrap"><table><thead><tr><th>Node</th><th>Collection</th><th>Match evidence</th><th>Last poll</th></tr></thead><tbody><tr v-for="binding in detail.bindings" :key="binding.nodeId"><td>{{binding.hostname}}</td><td>{{binding.status}}</td><td>{{binding.evidence.method}} · {{binding.evidence.signal}}</td><td>{{new Date(binding.lastPolledAt).toLocaleString()}}</td></tr></tbody></table></div></details><div class="form-actions"><button class="button secondary" :disabled="busy" @click="editing=false">Cancel</button><button class="button primary" :disabled="busy" @click="saveDetails">Save collection settings</button></div>
    </div>
  </GlassWindow>
  <ConfirmDialog v-model="removing" title="Remove imported MIB" :message="`Remove ${removeItem?.moduleName||'this module'} and its device links? Previously collected node facts remain available.`" :busy="busy" confirm-label="Remove MIB" @confirm="remove" />
</template>
<style scoped>
.mib-import,.mib-detail{font-size:.8rem;line-height:1.5}.mib-import p,.mib-detail p{margin:.25rem 0}.mib-preview{display:grid;gap:.5rem}.mib-library,.mib-import,.mib-detail{display:grid;gap:1rem;min-width:0}.mib-intro,.mib-tools,.mib-pagination{margin:0 1rem}.mib-intro{color:var(--muted);font-size:.8rem;line-height:1.5}.mib-tools{display:flex;gap:.5rem;flex-wrap:wrap;align-items:center}.mib-tools input{flex:1;min-width:160px}.mib-tools select{width:auto}.mib-library td{max-width:32rem;white-space:normal;overflow-wrap:anywhere}.mib-description{display:block;color:var(--muted);white-space:normal;max-width:50ch;margin-top:.3rem;line-height:1.45}.mib-pagination{display:flex;align-items:center;justify-content:flex-end;gap:.6rem;padding-bottom:1rem;font-size:.75rem;color:var(--muted)}.mib-pagination>span{margin-right:auto}.mib-preview>div{padding:.8rem;border:1px solid var(--border);border-radius:4px}.mib-import>label{display:grid;gap:.5rem}.mib-import .switch-field{display:flex}.mib-detail .form-grid{padding:0}.mib-detail summary{cursor:pointer}.mib-library .panel-title p{margin:.4rem 0 0}.mib-detail a{color:var(--enterprise-link,var(--cyan))}@media(max-width:600px){.mib-library .panel-title{align-items:flex-start;gap:1rem;flex-direction:column}.mib-pagination{flex-wrap:wrap}.mib-tools input{flex-basis:100%}.mib-tools select{flex:1 1 140px;min-width:140px}}
</style>
