<script setup>
import {ref,onMounted} from 'vue'
import {api,download} from '../services/api.js'
const result=ref({items:[],total:0,page:1,limit:25}),search=ref(''),status=ref('all'),error=ref(''),loading=ref(false)
let sequence=0
async function load(page=1){const current=++sequence;loading.value=true;error.value='';try{const data=await api(`/discovery/snmp-library/files?${new URLSearchParams({search:search.value,status:status.value,page,limit:25})}`);if(current===sequence)result.value=data}catch(e){if(current===sequence)error.value=e.message}finally{if(current===sequence)loading.value=false}}
async function save(file){try{await download(`/discovery/snmp-library/files/${encodeURIComponent(file.id)}/download`,file.filename.split('/').pop())}catch(e){error.value=e.message}}
onMounted(()=>load())
</script>
<template>
  <section class="mib-files"><div class="panel-title"><h2>MIB source files</h2><span>{{result.total.toLocaleString()}} files</span></div><p>Original source files are stored on the API server. Ready modules can be configured for collection. Alternate versions and files needing attention remain available for download.</p><p v-if="error" class="error-msg" role="alert">{{error}}</p><form @submit.prevent="load()"><input v-model="search" aria-label="Search MIB source files" placeholder="Search filename or module"><select v-model="status" aria-label="MIB file status" @change="load()"><option value="all">All files</option><option value="ready">Ready</option><option value="error">Needs attention</option><option value="archived">Alternate versions</option><option value="bundled">Bundled dependencies</option><option value="pending">Pending</option></select><button class="button secondary" :disabled="loading">Search</button></form><div class="table-wrap"><table><thead><tr><th>File / Module</th><th>Source</th><th>Size</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="file in result.items" :key="file.id"><td>{{file.filename}}<small>{{file.moduleName||'Unidentified module'}}</small></td><td>{{file.origin}}<small>{{file.revision?.slice(0,12)}}</small></td><td>{{(file.size/1024).toFixed(1)}} KiB</td><td>{{file.status}}<small v-if="file.error" class="file-error">{{file.error}}</small></td><td><button class="button small secondary" @click="save(file)">Download</button></td></tr><tr v-if="!result.items.length"><td colspan="5">{{loading?'Loading…':'No source files match.'}}</td></tr></tbody></table></div><div class="file-pages"><span>Page {{result.page}} / {{Math.max(1,Math.ceil(result.total/result.limit))}}</span><button class="button small secondary" :disabled="loading||result.page<=1" @click="load(result.page-1)">Previous</button><button class="button small secondary" :disabled="loading||result.page*result.limit>=result.total" @click="load(result.page+1)">Next</button></div></section>
</template>
<style scoped>
.mib-files{min-width:0;display:grid;gap:1rem}.mib-files>p,.mib-files form,.file-pages{margin:0 1rem}.mib-files>p{font-size:.8rem;line-height:1.5;color:var(--muted)}.mib-files form,.file-pages{display:flex;gap:.6rem;flex-wrap:wrap;align-items:center}.mib-files input{flex:1;min-width:160px}.mib-files select{width:auto;min-width:150px}.mib-files td{white-space:normal;overflow-wrap:anywhere;max-width:45ch}.mib-files small{display:block;color:var(--muted);margin-top:.3rem}.file-error{max-width:45ch}.file-pages{padding-bottom:1rem;justify-content:flex-end}.file-pages>span{margin-right:auto}
</style>
